// サタスペ データ定義ファイル

// ---------------------------------------------------
// 1. おたからデータ
// ---------------------------------------------------
const OTAKARA_DATA_LIST = [
  {
    id: 1,
    name: "シルバープレート",
    category: "汎用",
    note: "犯罪",
    source: "基本",
  },
  { id: 2, name: "へそくり", category: "汎用", note: "生活", source: "基本" },
  { id: 3, name: "思い出の品", category: "汎用", note: "恋愛", source: "基本" },
  {
    id: 4,
    name: "亜侠ファイル",
    category: "汎用",
    note: "2つ以上",
    source: "基本",
  },
  { id: 5, name: "往診鞄", category: "汎用", note: "教養", source: "基本" },
  {
    id: 6,
    name: "＋１エンブレム",
    category: "汎用",
    note: "戦闘",
    source: "基本",
  },
  {
    id: 19,
    name: "とっておきのチョコレート",
    category: "アウトドア",
    note: "1",
    source: "基本",
  },
  {
    id: 20,
    name: "カツカツな野外調理セット",
    category: "アウトドア",
    note: "2",
    source: "基本",
  },
  {
    id: 21,
    name: "夏の夜のテント",
    category: "アウトドア",
    note: "3",
    source: "基本",
  },
  {
    id: 22,
    name: "アウトドア-1(DW)",
    category: "アウトドア",
    note: "1",
    source: "DW",
  },
  {
    id: 23,
    name: "アウトドア-2(DW)",
    category: "アウトドア",
    note: "2",
    source: "DW",
  },
  {
    id: 24,
    name: "アウトドア-3(DW)",
    category: "アウトドア",
    note: "3",
    source: "DW",
  },
  { id: 25, name: "勝負下着", category: "アダルト", note: "1", source: "基本" },
  {
    id: 26,
    name: "エンジェル★ガーデン",
    category: "アダルト",
    note: "2",
    source: "基本",
  },
  {
    id: 27,
    name: "セックスフレンド",
    category: "アダルト",
    note: "3",
    source: "基本",
  },
  {
    id: 28,
    name: "アダルト-1(DW)",
    category: "アダルト",
    note: "1",
    source: "DW",
  },
  {
    id: 29,
    name: "アダルト-2(DW)",
    category: "アダルト",
    note: "2",
    source: "DW",
  },
  {
    id: 30,
    name: "アダルト-3(DW)",
    category: "アダルト",
    note: "3",
    source: "DW",
  },
  {
    id: 31,
    name: "伝説のビザール",
    category: "エクストリーム",
    note: "1",
    source: "基本",
  },
  {
    id: 32,
    name: "二代目のアラナワ",
    category: "エクストリーム",
    note: "2",
    source: "基本",
  },
  {
    id: 33,
    name: "背徳の注射器",
    category: "エクストリーム",
    note: "3",
    source: "基本",
  },
  {
    id: 34,
    name: "エクストリーム-1(DW)",
    category: "エクストリーム",
    note: "1",
    source: "DW",
  },
  {
    id: 35,
    name: "エクストリーム-2(DW)",
    category: "エクストリーム",
    note: "2",
    source: "DW",
  },
  {
    id: 36,
    name: "エクストリーム-3(DW)",
    category: "エクストリーム",
    note: "3",
    source: "DW",
  },
  {
    id: 37,
    name: "アゲアシ鳥",
    category: "アラサガシ",
    note: "1",
    source: "基本",
  },
  {
    id: 38,
    name: "ファンブルブック",
    category: "アラサガシ",
    note: "2",
    source: "基本",
  },
  {
    id: 39,
    name: "伝染し鏡",
    category: "アラサガシ",
    note: "3",
    source: "基本",
  },
  {
    id: 40,
    name: "アラサガシ-1(DW)",
    category: "アラサガシ",
    note: "1",
    source: "DW",
  },
  {
    id: 41,
    name: "アラサガシ-2(DW)",
    category: "アラサガシ",
    note: "2",
    source: "DW",
  },
  {
    id: 42,
    name: "アラサガシ-3(DW)",
    category: "アラサガシ",
    note: "3",
    source: "DW",
  },
  { id: 43, name: "忠実なペット", category: "育成", note: "1", source: "基本" },
  { id: 44, name: "不肖の弟子", category: "育成", note: "2", source: "基本" },
  { id: 45, name: "平和の呼子", category: "育成", note: "3", source: "基本" },
  { id: 46, name: "育成-1(DW)", category: "育成", note: "1", source: "DW" },
  { id: 47, name: "育成-2(DW)", category: "育成", note: "2", source: "DW" },
  { id: 48, name: "育成-3(DW)", category: "育成", note: "3", source: "DW" },
  { id: 49, name: "お食事券", category: "飲食", note: "1", source: "基本" },
  { id: 50, name: "視肉", category: "飲食", note: "2", source: "基本" },
  { id: 51, name: "名酒珠箒", category: "飲食", note: "3", source: "基本" },
  { id: 52, name: "飲食-1(DW)", category: "飲食", note: "1", source: "DW" },
  { id: 53, name: "飲食-2(DW)", category: "飲食", note: "2", source: "DW" },
  { id: 54, name: "飲食-3(DW)", category: "飲食", note: "3", source: "DW" },
  { id: 55, name: "隣人愛", category: "おせっかい", note: "1", source: "基本" },
  { id: 56, name: "老婆神", category: "おせっかい", note: "2", source: "基本" },
  {
    id: 57,
    name: "見合い写真",
    category: "おせっかい",
    note: "3",
    source: "基本",
  },
  {
    id: 58,
    name: "おせっかい-1(DW)",
    category: "おせっかい",
    note: "1",
    source: "DW",
  },
  {
    id: 59,
    name: "おせっかい-2(DW)",
    category: "おせっかい",
    note: "2",
    source: "DW",
  },
  {
    id: 60,
    name: "おせっかい-3(DW)",
    category: "おせっかい",
    note: "3",
    source: "DW",
  },
  {
    id: 61,
    name: "エル・マリアッチ",
    category: "音楽",
    note: "1",
    source: "基本",
  },
  {
    id: 62,
    name: "ケチャップセレクション",
    category: "音楽",
    note: "2",
    source: "基本",
  },
  {
    id: 63,
    name: "ヘルタースケルター",
    category: "音楽",
    note: "3",
    source: "基本",
  },
  { id: 64, name: "音楽-1(DW)", category: "音楽", note: "1", source: "DW" },
  { id: 65, name: "音楽-2(DW)", category: "音楽", note: "2", source: "DW" },
  { id: 66, name: "音楽-3(DW)", category: "音楽", note: "3", source: "DW" },
  { id: 67, name: "暗黒掃除機", category: "家事", note: "1", source: "基本" },
  {
    id: 68,
    name: "電子レンジのようなもの",
    category: "家事",
    note: "2",
    source: "基本",
  },
  {
    id: 69,
    name: "命のフライパン",
    category: "家事",
    note: "3",
    source: "基本",
  },
  { id: 70, name: "家事-1(DW)", category: "家事", note: "1", source: "DW" },
  { id: 71, name: "家事-2(DW)", category: "家事", note: "2", source: "DW" },
  { id: 72, name: "家事-3(DW)", category: "家事", note: "3", source: "DW" },
  {
    id: 73,
    name: "猫なでガス",
    category: "カワイイ",
    note: "1",
    source: "基本",
  },
  {
    id: 74,
    name: "四次元ポシェット",
    category: "カワイイ",
    note: "2",
    source: "基本",
  },
  {
    id: 75,
    name: "らぶりードーナツ",
    category: "カワイイ",
    note: "3",
    source: "基本",
  },
  {
    id: 76,
    name: "カワイイ-1(DW)",
    category: "カワイイ",
    note: "1",
    source: "DW",
  },
  {
    id: 77,
    name: "カワイイ-2(DW)",
    category: "カワイイ",
    note: "2",
    source: "DW",
  },
  {
    id: 78,
    name: "カワイイ-3(DW)",
    category: "カワイイ",
    note: "3",
    source: "DW",
  },
  { id: 79, name: "家庭教師", category: "ガリ勉", note: "1", source: "基本" },
  { id: 80, name: "キラリ眼鏡", category: "ガリ勉", note: "2", source: "基本" },
  {
    id: 81,
    name: "民明書房の研究書",
    category: "ガリ勉",
    note: "3",
    source: "基本",
  },
  { id: 82, name: "ガリ勉-1(DW)", category: "ガリ勉", note: "1", source: "DW" },
  { id: 83, name: "ガリ勉-2(DW)", category: "ガリ勉", note: "2", source: "DW" },
  { id: 84, name: "ガリ勉-3(DW)", category: "ガリ勉", note: "3", source: "DW" },
  {
    id: 85,
    name: "イカサマサイコロ",
    category: "ギャンブル",
    note: "1",
    source: "基本",
  },
  {
    id: 86,
    name: "両方表のコイン",
    category: "ギャンブル",
    note: "2",
    source: "基本",
  },
  {
    id: 87,
    name: "死の弾丸",
    category: "ギャンブル",
    note: "3",
    source: "基本",
  },
  {
    id: 88,
    name: "ギャンブル-1(DW)",
    category: "ギャンブル",
    note: "1",
    source: "DW",
  },
  {
    id: 89,
    name: "ギャンブル-2(DW)",
    category: "ギャンブル",
    note: "2",
    source: "DW",
  },
  {
    id: 90,
    name: "ギャンブル-3(DW)",
    category: "ギャンブル",
    note: "3",
    source: "DW",
  },
  { id: 91, name: "アフレックス", category: "健康", note: "1", source: "基本" },
  { id: 92, name: "超強力下剤", category: "健康", note: "2", source: "基本" },
  { id: 93, name: "偽造診察券", category: "健康", note: "3", source: "基本" },
  { id: 94, name: "健康-1(DW)", category: "健康", note: "1", source: "DW" },
  { id: 95, name: "健康-2(DW)", category: "健康", note: "2", source: "DW" },
  { id: 96, name: "健康-3(DW)", category: "健康", note: "3", source: "DW" },
  { id: 97, name: "魔改造セット", category: "工作", note: "1", source: "基本" },
  {
    id: 98,
    name: "グレムリンズ・スパナ",
    category: "工作",
    note: "2",
    source: "基本",
  },
  {
    id: 99,
    name: "バールのようなもの",
    category: "工作",
    note: "3",
    source: "基本",
  },
  { id: 100, name: "工作-1(DW)", category: "工作", note: "1", source: "DW" },
  { id: 101, name: "工作-2(DW)", category: "工作", note: "2", source: "DW" },
  { id: 102, name: "工作-3(DW)", category: "工作", note: "3", source: "DW" },
  {
    id: 103,
    name: "噂の深層",
    category: "ゴシップ",
    note: "1",
    source: "基本",
  },
  {
    id: 104,
    name: "極秘回覧板",
    category: "ゴシップ",
    note: "2",
    source: "基本",
  },
  {
    id: 105,
    name: "覗き屋の双眼鏡",
    category: "ゴシップ",
    note: "3",
    source: "基本",
  },
  {
    id: 106,
    name: "ゴシップ-1(DW)",
    category: "ゴシップ",
    note: "1",
    source: "DW",
  },
  {
    id: 107,
    name: "ゴシップ-2(DW)",
    category: "ゴシップ",
    note: "2",
    source: "DW",
  },
  {
    id: 108,
    name: "ゴシップ-3(DW)",
    category: "ゴシップ",
    note: "3",
    source: "DW",
  },
  {
    id: 109,
    name: "友錠",
    category: "サビシガリヤ",
    note: "1",
    source: "基本",
  },
  {
    id: 110,
    name: "友達の輪",
    category: "サビシガリヤ",
    note: "2",
    source: "基本",
  },
  {
    id: 111,
    name: "イマジナリーフレンド",
    category: "サビシガリヤ",
    note: "3",
    source: "基本",
  },
  {
    id: 112,
    name: "サビシガリヤ-1(DW)",
    category: "サビシガリヤ",
    note: "1",
    source: "DW",
  },
  {
    id: 113,
    name: "サビシガリヤ-2(DW)",
    category: "サビシガリヤ",
    note: "2",
    source: "DW",
  },
  {
    id: 114,
    name: "サビシガリヤ-3(DW)",
    category: "サビシガリヤ",
    note: "3",
    source: "DW",
  },
  { id: 115, name: "教典", category: "宗教", note: "1", source: "基本" },
  {
    id: 116,
    name: "ありがたい壺",
    category: "宗教",
    note: "2",
    source: "基本",
  },
  {
    id: 117,
    name: "ホーリーシンボル",
    category: "宗教",
    note: "3",
    source: "基本",
  },
  { id: 118, name: "宗教-1(DW)", category: "宗教", note: "1", source: "DW" },
  { id: 119, name: "宗教-2(DW)", category: "宗教", note: "2", source: "DW" },
  { id: 120, name: "宗教-3(DW)", category: "宗教", note: "3", source: "DW" },
  {
    id: 121,
    name: "ホームランバット",
    category: "スポーツ",
    note: "1",
    source: "基本",
  },
  {
    id: 122,
    name: "ボールの友達",
    category: "スポーツ",
    note: "2",
    source: "基本",
  },
  {
    id: 123,
    name: "マルチボード",
    category: "スポーツ",
    note: "3",
    source: "基本",
  },
  {
    id: 124,
    name: "スポーツ-1(DW)",
    category: "スポーツ",
    note: "1",
    source: "DW",
  },
  {
    id: 125,
    name: "スポーツ-2(DW)",
    category: "スポーツ",
    note: "2",
    source: "DW",
  },
  {
    id: 126,
    name: "スポーツ-3(DW)",
    category: "スポーツ",
    note: "3",
    source: "DW",
  },
  {
    id: 127,
    name: "みんなと同じスタイル",
    category: "トレンド",
    note: "1",
    source: "基本",
  },
  {
    id: 128,
    name: "OSAKAWALKER",
    category: "トレンド",
    note: "2",
    source: "基本",
  },
  {
    id: 129,
    name: "主体性のない友達",
    category: "トレンド",
    note: "3",
    source: "基本",
  },
  {
    id: 130,
    name: "トレンド-1(DW)",
    category: "トレンド",
    note: "1",
    source: "DW",
  },
  {
    id: 131,
    name: "トレンド-2(DW)",
    category: "トレンド",
    note: "2",
    source: "DW",
  },
  {
    id: 132,
    name: "トレンド-3(DW)",
    category: "トレンド",
    note: "3",
    source: "DW",
  },
  {
    id: 133,
    name: "ムーの首飾り",
    category: "トンデモ",
    note: "1",
    source: "基本",
  },
  {
    id: 134,
    name: "秘密研究室",
    category: "トンデモ",
    note: "2",
    source: "基本",
  },
  {
    id: 135,
    name: "ネクロノミコン",
    category: "トンデモ",
    note: "3",
    source: "基本",
  },
  {
    id: 136,
    name: "トンデモ-1(DW)",
    category: "トンデモ",
    note: "1",
    source: "DW",
  },
  {
    id: 137,
    name: "トンデモ-2(DW)",
    category: "トンデモ",
    note: "2",
    source: "DW",
  },
  {
    id: 138,
    name: "トンデモ-3(DW)",
    category: "トンデモ",
    note: "3",
    source: "DW",
  },
  {
    id: 139,
    name: "聖書型ピストルケース",
    category: "読書",
    note: "1",
    source: "基本",
  },
  {
    id: 140,
    name: "熟睡ハードカバー",
    category: "読書",
    note: "2",
    source: "基本",
  },
  {
    id: 141,
    name: "書きかけの小説",
    category: "読書",
    note: "3",
    source: "基本",
  },
  { id: 142, name: "読書-1(DW)", category: "読書", note: "1", source: "DW" },
  { id: 143, name: "読書-2(DW)", category: "読書", note: "2", source: "DW" },
  { id: 144, name: "読書-3(DW)", category: "読書", note: "3", source: "DW" },
  { id: 145, name: "愛馬", category: "ハイソ", note: "1", source: "基本" },
  {
    id: 146,
    name: "呪われた別荘",
    category: "ハイソ",
    note: "2",
    source: "基本",
  },
  {
    id: 147,
    name: "僕だけのメイドさん",
    category: "ハイソ",
    note: "3",
    source: "基本",
  },
  {
    id: 148,
    name: "ハイソ-1(DW)",
    category: "ハイソ",
    note: "1",
    source: "DW",
  },
  {
    id: 149,
    name: "ハイソ-2(DW)",
    category: "ハイソ",
    note: "2",
    source: "DW",
  },
  {
    id: 150,
    name: "ハイソ-3(DW)",
    category: "ハイソ",
    note: "3",
    source: "DW",
  },
  {
    id: 151,
    name: "透明ワイヤー",
    category: "パフォーマンス",
    note: "1",
    source: "基本",
  },
  {
    id: 152,
    name: "パフォーマンス・マイク",
    category: "パフォーマンス",
    note: "2",
    source: "基本",
  },
  {
    id: 153,
    name: "道化師の衣装",
    category: "パフォーマンス",
    note: "3",
    source: "基本",
  },
  {
    id: 154,
    name: "パフォーマンス-1(DW)",
    category: "パフォーマンス",
    note: "1",
    source: "DW",
  },
  {
    id: 155,
    name: "パフォーマンス-2(DW)",
    category: "パフォーマンス",
    note: "2",
    source: "DW",
  },
  {
    id: 156,
    name: "パフォーマンス-3(DW)",
    category: "パフォーマンス",
    note: "3",
    source: "DW",
  },
  {
    id: 157,
    name: "ルマルさんの箱",
    category: "ヒマツブシ",
    note: "1",
    source: "基本",
  },
  {
    id: 158,
    name: "魅惑のぷちぷちマット",
    category: "ヒマツブシ",
    note: "2",
    source: "基本",
  },
  {
    id: 159,
    name: "宇宙クロスワード",
    category: "ヒマツブシ",
    note: "3",
    source: "基本",
  },
  {
    id: 160,
    name: "ヒマツブシ-1(DW)",
    category: "ヒマツブシ",
    note: "1",
    source: "DW",
  },
  {
    id: 161,
    name: "ヒマツブシ-2(DW)",
    category: "ヒマツブシ",
    note: "2",
    source: "DW",
  },
  {
    id: 162,
    name: "ヒマツブシ-3(DW)",
    category: "ヒマツブシ",
    note: "3",
    source: "DW",
  },
  { id: 163, name: "悪魔の絵筆", category: "美術", note: "1", source: "基本" },
  {
    id: 164,
    name: "殺しのキャンバスナイフ",
    category: "美術",
    note: "2",
    source: "基本",
  },
  {
    id: 165,
    name: "タグスプレー",
    category: "美術",
    note: "3",
    source: "基本",
  },
  { id: 166, name: "美術-1(DW)", category: "美術", note: "1", source: "DW" },
  { id: 167, name: "美術-2(DW)", category: "美術", note: "2", source: "DW" },
  { id: 168, name: "美術-3(DW)", category: "美術", note: "3", source: "DW" },
  {
    id: 169,
    name: "奇抜な衣装",
    category: "ファッション",
    note: "1",
    source: "基本",
  },
  {
    id: 170,
    name: "レディアント・コ－ム",
    category: "ファッション",
    note: "2",
    source: "基本",
  },
  {
    id: 171,
    name: "モナムール大阪",
    category: "ファッション",
    note: "3",
    source: "基本",
  },
  {
    id: 172,
    name: "ファッション-1(DW)",
    category: "ファッション",
    note: "1",
    source: "DW",
  },
  {
    id: 173,
    name: "ファッション-2(DW)",
    category: "ファッション",
    note: "2",
    source: "DW",
  },
  {
    id: 174,
    name: "ファッション-3(DW)",
    category: "ファッション",
    note: "3",
    source: "DW",
  },
  {
    id: 175,
    name: "さるまねパソコン",
    category: "マニア",
    note: "1",
    source: "基本",
  },
  {
    id: 176,
    name: "積ん読の山",
    category: "マニア",
    note: "2",
    source: "基本",
  },
  {
    id: 177,
    name: "有名人のサイン",
    category: "マニア",
    note: "3",
    source: "基本",
  },
  {
    id: 178,
    name: "マニア-1(DW)",
    category: "マニア",
    note: "1",
    source: "DW",
  },
  {
    id: 179,
    name: "マニア-2(DW)",
    category: "マニア",
    note: "2",
    source: "DW",
  },
  {
    id: 180,
    name: "マニア-3(DW)",
    category: "マニア",
    note: "3",
    source: "DW",
  },
  {
    id: 181,
    name: "あわてるなタオル",
    category: "旅行",
    note: "1",
    source: "基本",
  },
  {
    id: 182,
    name: "凡世界日常会話辞典",
    category: "旅行",
    note: "2",
    source: "基本",
  },
  {
    id: 183,
    name: "鉄壁のトランク",
    category: "旅行",
    note: "3",
    source: "基本",
  },
  { id: 184, name: "旅行-1(DW)", category: "旅行", note: "1", source: "DW" },
  { id: 185, name: "旅行-2(DW)", category: "旅行", note: "2", source: "DW" },
  { id: 186, name: "旅行-3(DW)", category: "旅行", note: "3", source: "DW" },
  {
    id: 187,
    name: "雲南の山水画",
    category: "ワビサビ",
    note: "1",
    source: "基本",
  },
  {
    id: 188,
    name: "清流舞扇",
    category: "ワビサビ",
    note: "2",
    source: "基本",
  },
  {
    id: 189,
    name: "魔性の能面",
    category: "ワビサビ",
    note: "3",
    source: "基本",
  },
  {
    id: 190,
    name: "ワビサビ-1(DW)",
    category: "ワビサビ",
    note: "1",
    source: "DW",
  },
  {
    id: 191,
    name: "ワビサビ-2(DW)",
    category: "ワビサビ",
    note: "2",
    source: "DW",
  },
  {
    id: 192,
    name: "ワビサビ-3(DW)",
    category: "ワビサビ",
    note: "3",
    source: "DW",
  },
  {
    id: 193,
    name: "ザ・コンプリート",
    category: "ヲタク",
    note: "1",
    source: "基本",
  },
  {
    id: 194,
    name: "愛の抱き枕",
    category: "ヲタク",
    note: "2",
    source: "基本",
  },
  {
    id: 195,
    name: "転校生の階段",
    category: "ヲタク",
    note: "3",
    source: "基本",
  },
  {
    id: 196,
    name: "ヲタク-1(DW)",
    category: "ヲタク",
    note: "1",
    source: "DW",
  },
  {
    id: 197,
    name: "ヲタク-2(DW)",
    category: "ヲタク",
    note: "2",
    source: "DW",
  },
  {
    id: 198,
    name: "ヲタク-3(DW)",
    category: "ヲタク",
    note: "3",
    source: "DW",
  },
  {
    id: 199,
    name: "アウトドア-1(ダボラ)",
    category: "アウトドア",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 200,
    name: "アウトドア-2(ダボラ)",
    category: "アウトドア",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 201,
    name: "アウトドア-3(ダボラ)",
    category: "アウトドア",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 202,
    name: "アウトドア-4(ダボラ)",
    category: "アウトドア",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 203,
    name: "アウトドア-5(ダボラ)",
    category: "アウトドア",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 204,
    name: "アウトドア-6(ダボラ)",
    category: "アウトドア",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 205,
    name: "アダルト-1(ダボラ)",
    category: "アダルト",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 206,
    name: "アダルト-2(ダボラ)",
    category: "アダルト",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 207,
    name: "アダルト-3(ダボラ)",
    category: "アダルト",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 208,
    name: "アダルト-4(ダボラ)",
    category: "アダルト",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 209,
    name: "アダルト-5(ダボラ)",
    category: "アダルト",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 210,
    name: "アダルト-6(ダボラ)",
    category: "アダルト",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 211,
    name: "エクストリーム-1(ダボラ)",
    category: "エクストリーム",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 212,
    name: "エクストリーム-2(ダボラ)",
    category: "エクストリーム",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 213,
    name: "エクストリーム-3(ダボラ)",
    category: "エクストリーム",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 214,
    name: "エクストリーム-4(ダボラ)",
    category: "エクストリーム",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 215,
    name: "エクストリーム-5(ダボラ)",
    category: "エクストリーム",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 216,
    name: "エクストリーム-6(ダボラ)",
    category: "エクストリーム",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 217,
    name: "アラサガシ-1(ダボラ)",
    category: "アラサガシ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 218,
    name: "アラサガシ-2(ダボラ)",
    category: "アラサガシ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 219,
    name: "アラサガシ-3(ダボラ)",
    category: "アラサガシ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 220,
    name: "アラサガシ-4(ダボラ)",
    category: "アラサガシ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 221,
    name: "アラサガシ-5(ダボラ)",
    category: "アラサガシ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 222,
    name: "アラサガシ-6(ダボラ)",
    category: "アラサガシ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 223,
    name: "育成-1(ダボラ)",
    category: "育成",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 224,
    name: "育成-2(ダボラ)",
    category: "育成",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 225,
    name: "育成-3(ダボラ)",
    category: "育成",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 226,
    name: "育成-4(ダボラ)",
    category: "育成",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 227,
    name: "育成-5(ダボラ)",
    category: "育成",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 228,
    name: "育成-6(ダボラ)",
    category: "育成",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 229,
    name: "飲食-1(ダボラ)",
    category: "飲食",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 230,
    name: "飲食-2(ダボラ)",
    category: "飲食",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 231,
    name: "飲食-3(ダボラ)",
    category: "飲食",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 232,
    name: "飲食-4(ダボラ)",
    category: "飲食",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 233,
    name: "飲食-5(ダボラ)",
    category: "飲食",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 234,
    name: "飲食-6(ダボラ)",
    category: "飲食",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 235,
    name: "おせっかい-1(ダボラ)",
    category: "おせっかい",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 236,
    name: "おせっかい-2(ダボラ)",
    category: "おせっかい",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 237,
    name: "おせっかい-3(ダボラ)",
    category: "おせっかい",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 238,
    name: "おせっかい-4(ダボラ)",
    category: "おせっかい",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 239,
    name: "おせっかい-5(ダボラ)",
    category: "おせっかい",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 240,
    name: "おせっかい-6(ダボラ)",
    category: "おせっかい",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 241,
    name: "音楽-1(ダボラ)",
    category: "音楽",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 242,
    name: "音楽-2(ダボラ)",
    category: "音楽",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 243,
    name: "音楽-3(ダボラ)",
    category: "音楽",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 244,
    name: "音楽-4(ダボラ)",
    category: "音楽",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 245,
    name: "音楽-5(ダボラ)",
    category: "音楽",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 246,
    name: "音楽-6(ダボラ)",
    category: "音楽",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 247,
    name: "家事-1(ダボラ)",
    category: "家事",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 248,
    name: "家事-2(ダボラ)",
    category: "家事",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 249,
    name: "家事-3(ダボラ)",
    category: "家事",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 250,
    name: "家事-4(ダボラ)",
    category: "家事",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 251,
    name: "家事-5(ダボラ)",
    category: "家事",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 252,
    name: "家事-6(ダボラ)",
    category: "家事",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 253,
    name: "カワイイ-1(ダボラ)",
    category: "カワイイ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 254,
    name: "カワイイ-2(ダボラ)",
    category: "カワイイ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 255,
    name: "カワイイ-3(ダボラ)",
    category: "カワイイ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 256,
    name: "カワイイ-4(ダボラ)",
    category: "カワイイ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 257,
    name: "カワイイ-5(ダボラ)",
    category: "カワイイ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 258,
    name: "カワイイ-6(ダボラ)",
    category: "カワイイ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 259,
    name: "ガリ勉-1(ダボラ)",
    category: "ガリ勉",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 260,
    name: "ガリ勉-2(ダボラ)",
    category: "ガリ勉",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 261,
    name: "ガリ勉-3(ダボラ)",
    category: "ガリ勉",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 262,
    name: "ガリ勉-4(ダボラ)",
    category: "ガリ勉",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 263,
    name: "ガリ勉-5(ダボラ)",
    category: "ガリ勉",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 264,
    name: "ガリ勉-6(ダボラ)",
    category: "ガリ勉",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 265,
    name: "ギャンブル-1(ダボラ)",
    category: "ギャンブル",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 266,
    name: "ギャンブル-2(ダボラ)",
    category: "ギャンブル",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 267,
    name: "ギャンブル-3(ダボラ)",
    category: "ギャンブル",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 268,
    name: "ギャンブル-4(ダボラ)",
    category: "ギャンブル",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 269,
    name: "ギャンブル-5(ダボラ)",
    category: "ギャンブル",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 270,
    name: "ギャンブル-6(ダボラ)",
    category: "ギャンブル",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 271,
    name: "健康-1(ダボラ)",
    category: "健康",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 272,
    name: "健康-2(ダボラ)",
    category: "健康",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 273,
    name: "健康-3(ダボラ)",
    category: "健康",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 274,
    name: "健康-4(ダボラ)",
    category: "健康",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 275,
    name: "健康-5(ダボラ)",
    category: "健康",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 276,
    name: "健康-6(ダボラ)",
    category: "健康",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 277,
    name: "工作-1(ダボラ)",
    category: "工作",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 278,
    name: "工作-2(ダボラ)",
    category: "工作",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 279,
    name: "工作-3(ダボラ)",
    category: "工作",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 280,
    name: "工作-4(ダボラ)",
    category: "工作",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 281,
    name: "工作-5(ダボラ)",
    category: "工作",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 282,
    name: "工作-6(ダボラ)",
    category: "工作",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 283,
    name: "ゴシップ-1(ダボラ)",
    category: "ゴシップ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 284,
    name: "ゴシップ-2(ダボラ)",
    category: "ゴシップ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 285,
    name: "ゴシップ-3(ダボラ)",
    category: "ゴシップ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 286,
    name: "ゴシップ-4(ダボラ)",
    category: "ゴシップ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 287,
    name: "ゴシップ-5(ダボラ)",
    category: "ゴシップ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 288,
    name: "ゴシップ-6(ダボラ)",
    category: "ゴシップ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 289,
    name: "サビシガリヤ-1(ダボラ)",
    category: "サビシガリヤ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 290,
    name: "サビシガリヤ-2(ダボラ)",
    category: "サビシガリヤ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 291,
    name: "サビシガリヤ-3(ダボラ)",
    category: "サビシガリヤ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 292,
    name: "サビシガリヤ-4(ダボラ)",
    category: "サビシガリヤ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 293,
    name: "サビシガリヤ-5(ダボラ)",
    category: "サビシガリヤ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 294,
    name: "サビシガリヤ-6(ダボラ)",
    category: "サビシガリヤ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 295,
    name: "宗教-1(ダボラ)",
    category: "宗教",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 296,
    name: "宗教-2(ダボラ)",
    category: "宗教",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 297,
    name: "宗教-3(ダボラ)",
    category: "宗教",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 298,
    name: "宗教-4(ダボラ)",
    category: "宗教",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 299,
    name: "宗教-5(ダボラ)",
    category: "宗教",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 300,
    name: "宗教-6(ダボラ)",
    category: "宗教",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 301,
    name: "スポーツ-1(ダボラ)",
    category: "スポーツ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 302,
    name: "スポーツ-2(ダボラ)",
    category: "スポーツ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 303,
    name: "スポーツ-3(ダボラ)",
    category: "スポーツ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 304,
    name: "スポーツ-4(ダボラ)",
    category: "スポーツ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 305,
    name: "スポーツ-5(ダボラ)",
    category: "スポーツ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 306,
    name: "スポーツ-6(ダボラ)",
    category: "スポーツ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 307,
    name: "トレンド-1(ダボラ)",
    category: "トレンド",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 308,
    name: "トレンド-2(ダボラ)",
    category: "トレンド",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 309,
    name: "トレンド-3(ダボラ)",
    category: "トレンド",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 310,
    name: "トレンド-4(ダボラ)",
    category: "トレンド",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 311,
    name: "トレンド-5(ダボラ)",
    category: "トレンド",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 312,
    name: "トレンド-6(ダボラ)",
    category: "トレンド",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 313,
    name: "トンデモ-1(ダボラ)",
    category: "トンデモ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 314,
    name: "トンデモ-2(ダボラ)",
    category: "トンデモ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 315,
    name: "トンデモ-3(ダボラ)",
    category: "トンデモ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 316,
    name: "トンデモ-4(ダボラ)",
    category: "トンデモ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 317,
    name: "トンデモ-5(ダボラ)",
    category: "トンデモ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 318,
    name: "トンデモ-6(ダボラ)",
    category: "トンデモ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 319,
    name: "読書-1(ダボラ)",
    category: "読書",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 320,
    name: "読書-2(ダボラ)",
    category: "読書",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 321,
    name: "読書-3(ダボラ)",
    category: "読書",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 322,
    name: "読書-4(ダボラ)",
    category: "読書",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 323,
    name: "読書-5(ダボラ)",
    category: "読書",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 324,
    name: "読書-6(ダボラ)",
    category: "読書",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 325,
    name: "ハイソ-1(ダボラ)",
    category: "ハイソ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 326,
    name: "ハイソ-2(ダボラ)",
    category: "ハイソ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 327,
    name: "ハイソ-3(ダボラ)",
    category: "ハイソ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 328,
    name: "ハイソ-4(ダボラ)",
    category: "ハイソ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 329,
    name: "ハイソ-5(ダボラ)",
    category: "ハイソ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 330,
    name: "ハイソ-6(ダボラ)",
    category: "ハイソ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 331,
    name: "パフォーマンス-1(ダボラ)",
    category: "パフォーマンス",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 332,
    name: "パフォーマンス-2(ダボラ)",
    category: "パフォーマンス",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 333,
    name: "パフォーマンス-3(ダボラ)",
    category: "パフォーマンス",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 334,
    name: "パフォーマンス-4(ダボラ)",
    category: "パフォーマンス",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 335,
    name: "パフォーマンス-5(ダボラ)",
    category: "パフォーマンス",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 336,
    name: "パフォーマンス-6(ダボラ)",
    category: "パフォーマンス",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 337,
    name: "ヒマツブシ-1(ダボラ)",
    category: "ヒマツブシ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 338,
    name: "ヒマツブシ-2(ダボラ)",
    category: "ヒマツブシ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 339,
    name: "ヒマツブシ-3(ダボラ)",
    category: "ヒマツブシ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 340,
    name: "ヒマツブシ-4(ダボラ)",
    category: "ヒマツブシ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 341,
    name: "ヒマツブシ-5(ダボラ)",
    category: "ヒマツブシ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 342,
    name: "ヒマツブシ-6(ダボラ)",
    category: "ヒマツブシ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 343,
    name: "美術-1(ダボラ)",
    category: "美術",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 344,
    name: "美術-2(ダボラ)",
    category: "美術",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 345,
    name: "美術-3(ダボラ)",
    category: "美術",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 346,
    name: "美術-4(ダボラ)",
    category: "美術",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 347,
    name: "美術-5(ダボラ)",
    category: "美術",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 348,
    name: "美術-6(ダボラ)",
    category: "美術",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 349,
    name: "ファッション-1(ダボラ)",
    category: "ファッション",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 350,
    name: "ファッション-2(ダボラ)",
    category: "ファッション",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 351,
    name: "ファッション-3(ダボラ)",
    category: "ファッション",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 352,
    name: "ファッション-4(ダボラ)",
    category: "ファッション",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 353,
    name: "ファッション-5(ダボラ)",
    category: "ファッション",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 354,
    name: "ファッション-6(ダボラ)",
    category: "ファッション",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 355,
    name: "マニア-1(ダボラ)",
    category: "マニア",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 356,
    name: "マニア-2(ダボラ)",
    category: "マニア",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 357,
    name: "マニア-3(ダボラ)",
    category: "マニア",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 358,
    name: "マニア-4(ダボラ)",
    category: "マニア",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 359,
    name: "マニア-5(ダボラ)",
    category: "マニア",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 360,
    name: "マニア-6(ダボラ)",
    category: "マニア",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 361,
    name: "旅行-1(ダボラ)",
    category: "旅行",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 362,
    name: "旅行-2(ダボラ)",
    category: "旅行",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 363,
    name: "旅行-3(ダボラ)",
    category: "旅行",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 364,
    name: "旅行-4(ダボラ)",
    category: "旅行",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 365,
    name: "旅行-5(ダボラ)",
    category: "旅行",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 366,
    name: "旅行-6(ダボラ)",
    category: "旅行",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 367,
    name: "ワビサビ-1(ダボラ)",
    category: "ワビサビ",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 368,
    name: "ワビサビ-2(ダボラ)",
    category: "ワビサビ",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 369,
    name: "ワビサビ-3(ダボラ)",
    category: "ワビサビ",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 370,
    name: "ワビサビ-4(ダボラ)",
    category: "ワビサビ",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 371,
    name: "ワビサビ-5(ダボラ)",
    category: "ワビサビ",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 372,
    name: "ワビサビ-6(ダボラ)",
    category: "ワビサビ",
    note: "6",
    source: "ダボラ",
  },
  {
    id: 373,
    name: "ヲタク-1(ダボラ)",
    category: "ヲタク",
    note: "1",
    source: "ダボラ",
  },
  {
    id: 374,
    name: "ヲタク-2(ダボラ)",
    category: "ヲタク",
    note: "2",
    source: "ダボラ",
  },
  {
    id: 375,
    name: "ヲタク-3(ダボラ)",
    category: "ヲタク",
    note: "3",
    source: "ダボラ",
  },
  {
    id: 376,
    name: "ヲタク-4(ダボラ)",
    category: "ヲタク",
    note: "4",
    source: "ダボラ",
  },
  {
    id: 377,
    name: "ヲタク-5(ダボラ)",
    category: "ヲタク",
    note: "5",
    source: "ダボラ",
  },
  {
    id: 378,
    name: "ヲタク-6(ダボラ)",
    category: "ヲタク",
    note: "6",
    source: "ダボラ",
  },
];

// ---------------------------------------------------
// 2. 名前データ (画像データ反映版)
// ---------------------------------------------------
const NAME_DATA = {
  jp: {
    family: {
      11: "赤木",
      12: "岩井",
      13: "小津",
      14: "小野",
      15: "加藤",
      16: "具志堅",
      22: "黒澤",
      23: "坂井",
      24: "菅原",
      25: "谷崎",
      26: "千葉",
      33: "東郷",
      34: "中臣",
      35: "野村",
      36: "原",
      44: "比嘉",
      45: "本田",
      46: "松田",
      55: "三島",
      56: "武者小路",
      66: "山本",
    },
    male: {
      11: "アキラ",
      12: "イゾウ",
      13: "エイスケ",
      14: "カオル",
      15: "ケンジ",
      16: "コテツ",
      22: "サンジュウロウ",
      23: "シュウサク",
      24: "シロウ",
      25: "タクヤ",
      26: "タケシ",
      33: "トシロウ",
      34: "ハヤト",
      35: "ヒデキ",
      36: "ヒロシ",
      44: "マサト",
      45: "ミツオ",
      46: "ユウジ",
      55: "ヨシヒサ",
      56: "リュウイチ",
      66: "ワタル",
    },
    female: {
      11: "アキラ",
      12: "アケミ",
      13: "アスカ",
      14: "エミ",
      15: "カオル",
      16: "キヨミ",
      22: "キョウコ",
      23: "サツキ",
      24: "シマ",
      25: "ナツミ",
      26: "ヒカル",
      33: "ヒバリ",
      34: "マリ",
      35: "ミサ",
      36: "ミドリ",
      44: "ミヤコ",
      45: "ミユキ",
      46: "モトコ",
      55: "ヨウコ",
      56: "リン",
      66: "レイコ",
    },
  },
  china: {
    family: {
      11: "ウー（呉）",
      12: "ウェイ（魏）",
      13: "カオ（高）",
      14: "カン（康）",
      15: "ジャン（江）",
      16: "スン（孫）",
      22: "チェン（陳）",
      23: "チャオ（趙）",
      24: "チャン（張）",
      25: "チョウ（周）",
      26: "ツァオ（曹）",
      33: "ツイ（崔）",
      34: "ハン（韓）",
      35: "フェイ（飛）",
      36: "マー（馬）",
      44: "ヤン（楊）",
      45: "リー（李）",
      46: "リウ（劉）",
      55: "リン（林）",
      56: "ルー（魯）",
      66: "ワン（王）",
    },
    maleA: {
      11: "イー（一）",
      12: "ウー（武）",
      13: "ウェン（文）",
      14: "クオ（国）",
      15: "シェン（深）",
      16: "ジェン（健）",
      22: "シャオ（少）",
      23: "チー（志）",
      24: "チュン（忠）",
      25: "チェン（成）",
      26: "チン（敬）",
      33: "ツー（子）",
      34: "ツェ（則）",
      35: "ツン（宗）",
      36: "ハン（漢）",
      44: "フー（虎）",
      45: "ポー（白）",
      46: "ミン（明）",
      55: "ユアン（遠）",
      56: "ユウ（裕）",
      66: "ユン（永）",
    },
    maleB: {
      11: "イェン（炎）",
      12: "イン（英）",
      13: "クェイ（貴）",
      14: "コー（克）",
      15: "ジェン（仁）",
      16: "シュン（順）",
      22: "ター（大）",
      23: "タオ（道）",
      24: "チー（智）",
      25: "チャオ（教）",
      26: "チャン（章）",
      33: "チュアン（権）",
      34: "チン（慶）",
      35: "テー（徳）",
      36: "ティエン（天）",
      44: "ナン（南）",
      45: "フー（胡）",
      46: "ミン（民）",
      55: "ユイ（玉）",
      56: "ユアン（淵）",
      66: "ルン（竜）",
    },
    female: {
      11: "アイ（愛）",
      12: "イン（英）",
      13: "クィ（貴）",
      14: "シャオ（小）",
      15: "シャン（祥）",
      16: "シン（信）",
      22: "チウ（秋）",
      23: "チュン（春）",
      24: "ファ（花）",
      25: "ファン（芳）",
      26: "フー（胡）",
      33: "ミン（明）",
      34: "メイ（美）",
      35: "ユイ（玉）",
      36: "ユエン（圓）",
      44: "ユン（永）",
      45: "ラン（蘭）",
      46: "リー（麗）",
      55: "リェン（蓮）",
      56: "リン（鈴）",
      66: "ロウ（桜）",
    },
  },
  korea: {
    // 東アジア
    family: {
      11: "カム",
      12: "サラジャニ",
      13: "サラワティ",
      14: "サルン",
      15: "ソムデン",
      16: "タナラット",
      22: "タワン",
      23: "チャンチャン",
      24: "ナラヤナン",
      25: "バット",
      26: "パンヨム",
      33: "モンワット",
      34: "ラウィット",
      35: "ワヤン",
      36: "グエン",
      44: "ゴー",
      45: "チュン",
      46: "ファン",
      55: "ラズリ",
      56: "ヴァンミン",
      66: "チェンキエム",
    },
    male: {
      11: "イム",
      12: "ヴィニチャイ",
      13: "サリット",
      14: "シティポン",
      15: "ジャルーン",
      16: "シリク",
      22: "スアルサ",
      23: "ソム",
      24: "ソングラム",
      25: "トリシラ",
      26: "トンチャイ",
      33: "ニャク",
      34: "プゲッグ",
      35: "モムルアン",
      36: "モンワット",
      44: "ユーディ",
      45: "ラズリ",
      46: "ヴァンミン",
      55: "カイ",
      56: "スアンテュイ",
      66: "ティホワ",
    },
    female: {
      11: "アティア",
      12: "アーリャ",
      13: "イルマ",
      14: "カスティ",
      15: "サーイ",
      16: "サリ",
      22: "サール",
      23: "セーナ",
      24: "チョンティチャ―",
      25: "パラディー",
      26: "ファーサイ",
      33: "ペンシー",
      34: "ポンテック",
      35: "メーティニー",
      36: "リム",
      44: "ローサ",
      45: "ワティ",
      46: "ギア",
      55: "タイン",
      56: "チャット",
      66: "ティホワ",
    },
  },
  west_asia: {
    // 西アジア
    family: {
      11: "アサド",
      12: "アジズ",
      13: "アフマド",
      14: "アミーン",
      15: "アリ",
      16: "ウッディーン",
      22: "カーン",
      23: "サラム",
      24: "サルワト",
      25: "ナギーブ",
      26: "ナスィーム",
      33: "ハーディ",
      34: "フセイン",
      35: "マーヒル",
      36: "マフムード",
      44: "マンスール",
      45: "シャストリ",
      46: "セカール",
      55: "チャンドラ",
      56: "ティラーク",
      66: "ラーマン",
    },
    male: {
      11: "アクバル",
      12: "アッバス",
      13: "アブドゥル",
      14: "イブラヒム",
      15: "オスマン",
      16: "カースィム",
      22: "サイード",
      23: "ジャワール",
      24: "スライマーン",
      25: "セイエド",
      26: "タウフィーク",
      33: "チョードリ",
      34: "ハサン",
      35: "ムスタファ",
      36: "ムハンマド",
      44: "ヤセル",
      45: "ヴァルティ",
      46: "ザキール",
      55: "シュリー",
      56: "ディベンドラ",
      66: "ラビンドラナト",
    },
    female: {
      11: "アメル",
      12: "サラ",
      13: "サルマー",
      14: "サミー",
      15: "ジャリス",
      16: "セリマ",
      22: "セローナ",
      23: "ソフィア",
      24: "ディアンナ",
      25: "ナジャ",
      26: "ファーティマ",
      33: "マヤ",
      34: "ヤスミン",
      35: "ライラ",
      36: "ラディア",
      44: "ラティファ",
      45: "インディラ",
      46: "サラリー",
      55: "シャンティ",
      56: "デビー",
      66: "テレサ",
    },
  },
  hispanic: {
    // ヒスパニック
    family: {
      11: "アギーレ",
      12: "アルバレス",
      13: "ヴァレンティノ",
      14: "ウルキオラ",
      15: "エステベス",
      16: "オニール",
      22: "オルテガ",
      23: "ガルシア",
      24: "ゴメス",
      25: "コルテス",
      26: "コルドバ",
      33: "サパタ",
      34: "ディアス",
      35: "バンデラス",
      36: "ヒメネス",
      44: "フェルナンデス",
      45: "マルティネス",
      46: "メンドーサ",
      55: "ラモス",
      56: "ロドリゲス",
      66: "ロペス",
    },
    male: {
      11: "アルフォンソ",
      12: "アントニオ",
      13: "エステバン",
      14: "エミリアノ",
      15: "カルロス",
      16: "サルヴァトーレ",
      22: "サンチョ",
      23: "ジャンゴ",
      24: "ディエゴ",
      25: "ドミンゴ",
      26: "パコ",
      33: "パブロ",
      34: "フェリペ",
      35: "フェルナンド",
      36: "ペペ",
      44: "ホセ",
      45: "マリア",
      46: "ミゲル",
      55: "ミケーレ",
      56: "リカルド",
      66: "ルイス",
    },
    female: {
      11: "イサベル",
      12: "エヴァ",
      13: "エレーナ",
      14: "ガブリエラ",
      15: "カルメン",
      16: "カルロッタ",
      22: "クリスティーナ",
      23: "サンチャ",
      24: "セレーナ",
      25: "ソフィア",
      26: "テレサ",
      33: "ノラ",
      34: "ブランカ",
      35: "フワナ",
      36: "ホセフィーナ",
      44: "マリア",
      45: "マルガリータ",
      46: "ミケーラ",
      55: "メルセデス",
      56: "ルイーザ",
      66: "ローザ",
    },
  },
  euro: {
    // 欧米
    family: {
      11: "アーミテジ",
      12: "エイクロイド",
      13: "オールドマン",
      14: "オブライエン",
      15: "カーペンター",
      16: "グリフィス",
      22: "プリンス",
      23: "ブレナン",
      24: "マクベイン",
      25: "マドセン",
      26: "ライバック",
      33: "ランディス",
      34: "エメリッヒ",
      35: "バーホーベン",
      36: "クルーゾー",
      44: "ジュネ",
      45: "ゴダール",
      46: "ルコント",
      55: "タランティーノ",
      56: "コルブッチ",
      66: "ジョーンズ",
    },
    male: {
      11: "アンディ（アンドリュー）",
      12: "エルヴィス",
      13: "クリス（クリストファー）",
      14: "ケヴィン",
      15: "ジョニー（ジョナサン）",
      16: "スパイク",
      22: "バート（ハーバート）",
      23: "マーティン",
      24: "マイク（マイケル）",
      25: "モーガン",
      26: "ロレンス",
      33: "クラウス",
      34: "ヴィンセント",
      35: "ギュスターヴ",
      36: "ルイ",
      44: "チェーザレ",
      45: "ベルナルド",
      46: "アンリ",
      55: "ベルナルド",
      56: "ハリー（ハリス）",
      66: "ティム（ティモシー）",
    },
    female: {
      11: "オードリー",
      12: "キャシー（キャサリン）",
      13: "クリス（クリスティン）",
      14: "ジェシカ",
      15: "ジーナ",
      16: "ジュリア",
      22: "ステファニー",
      23: "ナタリー",
      24: "パティ（パトリシア）",
      25: "ベッキー（レベッカ）",
      26: "ローラ",
      33: "エヴァ",
      34: "シモーヌ",
      35: "ソフィー",
      36: "ブリジット",
      44: "クラウディア",
      45: "レオナ",
      46: "アリス",
      55: "シャーロット",
      56: "レイチェル",
      66: "リーリー",
    },
  },
  africa: {
    // アフリカ
    family: {
      11: "アキエ",
      12: "アチェベ",
      13: "アドン",
      14: "アンバ",
      15: "カブラル",
      16: "カンバ",
      22: "キマジ",
      23: "キンテ",
      24: "ジェング",
      25: "ジュマ",
      26: "ツワナ",
      33: "トゥレ",
      34: "ニエレレ",
      35: "バプヌ",
      36: "バンダ",
      44: "ポコピ",
      45: "ポワニ",
      46: "ボンゴ",
      55: "マケバ",
      56: "マディ",
      66: "ワイナイナ",
    },
    male: {
      11: "アニク",
      12: "アミルカル",
      13: "アヤオビ",
      14: "インパラ",
      15: "ウフエ",
      16: "エリジャ",
      22: "ガッチャ",
      23: "クァウディオ",
      24: "クアメ",
      25: "クンタ",
      26: "シャカ",
      33: "ジャファリ",
      34: "セメコ",
      35: "セル",
      36: "ディンガネ",
      44: "デダン",
      45: "テンポ",
      46: "ベンバ",
      55: "ママット",
      56: "ムランガネ",
      66: "ロロ",
    },
    female: {
      11: "アフィ",
      12: "アッフゥエ",
      13: "アミナ",
      14: "キリガ",
      15: "コフィ",
      16: "サフィナ",
      22: "サフォー",
      23: "ジファ",
      24: "ディココレ",
      25: "ナデゲ",
      26: "ナンディ",
      33: "ネハンダ",
      34: "ハディ",
      35: "パナナ",
      36: "ハワ",
      44: "ファトゥー",
      45: "ペリシ",
      46: "ヤワ",
      55: "リュト",
      56: "ルーシ",
      66: "レガ",
    },
  },
  russia: {
    // ロシア
    family: {
      11: "アシモフ（アシモヴァ）",
      12: "イリューシン（イリューシナ）",
      13: "ウイスキー（ウイスカヤ）",
      14: "カスパロフ（カスパロヴァ）",
      15: "カラシニコフ（カラシニコヴァ）",
      16: "カレリン（カレリナ）",
      22: "カレーニン（カレーニナ）",
      23: "コピィロフ（コピィロヴァ）",
      24: "ゴロドク（ゴロドカ）",
      25: "コロリョフ（コロリョヴァ）",
      26: "ザンギエフ（ザンギエヴァ）",
      33: "ストルガツキー（ストルガツカヤ）",
      34: "タルコフスキー（タルコフスカヤ）",
      35: "ダンコー（ダンコー）",
      36: "テルミン（テルミナ）",
      44: "テレシコフ（テレシコヴァ）",
      45: "ドラコ（ドラコ）",
      46: "パジトノフ（パジトノヴァ）",
      55: "ボルコフ（ボルコヴァ）",
      56: "ラスプーチン（ラスプーチナ）",
      66: "ロッソビッチ（ロッソヴナ）",
    },
    male: {
      11: "アルカーディ",
      12: "アレクサンドル",
      13: "アレクセイ",
      14: "アンドレイ",
      15: "イリヤ",
      16: "イワン",
      22: "ヴァシリー",
      23: "ヴィクトル",
      24: "ウラジーミル",
      25: "キリル",
      26: "コンスタンチン",
      33: "セルゲイ",
      34: "ディミトリ",
      35: "ニキータ",
      36: "ニコライ",
      44: "パーヴェル",
      45: "ピョートル",
      46: "ボリス",
      55: "ミハイル",
      56: "ユーリィ",
      66: "レフ",
    },
    female: {
      11: "アナスタシア",
      12: "アレクサンドラ",
      13: "アンナ",
      14: "イリーナ",
      15: "エカチェリーナ",
      16: "エレーナ",
      22: "オリガ",
      23: "スヴェトラーナ",
      24: "ソフィア",
      25: "タチアナ",
      26: "タマーラ",
      33: "ナジェージダ",
      34: "ナターリア",
      35: "ニーナ",
      36: "マリーア",
      44: "マリーナ",
      45: "ユーリャ",
      46: "ライサ",
      55: "リュドミラ",
      56: "リュボーフィ",
      66: "リーリャ",
    },
  },
  special: {
    // 特殊人名 (苗字、名前)
    family: {
      11: "REF:jp",
      12: "REF:china",
      13: "REF:korea",
      14: "REF:west_asia",
      15: "REF:hispanic",
      16: "REF:euro",
      22: "REF:russia",
      23: "REF:africa",
      24: "モンタージュ（または任意の映画用語）",
      25: "トレイン（または任意の乗物）",
      26: "自然主義（または任意の芸術運動）",
      33: "十字軍（または任意の歴史的事件）",
      34: "四畳半（または任意の建築用語）",
      35: "ダイエー（または任意のスーパーマーケット）",
      36: "X（または任意のアルファベット一文字）",
      44: "学級文庫（または任意の文庫）",
      45: "京橋（または任意の大阪の地名）",
      46: "DICE",
      55: "会場の最寄り駅",
      56: "手近の飲み物",
      66: "故郷の名物",
    },
    given: {
      11: "ソニー（または任意の家電メーカー）",
      12: "プノンペン（または任意の首都）",
      13: "ベンツ（または任意の自動車メーカー）",
      14: "アスピリン（または任意の医薬品）",
      15: "デスメタル（または任意の音楽ジャンル）",
      16: "タイガース（または任意のスポーツチーム）",
      22: "小鬼（または任意のモンスター）",
      23: "ソリテア（または任意の電子ゲーム）",
      24: "ブロードソード（または任意の武器）",
      25: "ラジオ（または任意の電化製品）",
      26: "ピーカーブー（または任意のゲーム）",
      33: "アルパカ（または任意の動物）",
      34: "チャンピオン（または任意のコミック雑誌）",
      35: "ローソン（または任意のコンビニ）",
      36: "マクドナルド（または任意のファーストフード）",
      44: "パラディン（または任意のRPGのクラス等）",
      45: "イワトビペンギン（または任意の鳥）",
      46: "ロボ（または任意のロボット）",
      55: "ジーパン（または任意の服）",
      56: "手近の食べ物",
      66: "現在の時刻",
    },
  },
};
// ---------------------------------------------------
// 3. 年齢・外見データ
// ---------------------------------------------------
const AGE_CHART = [
  { label: "幼年", base: 6, dice: 2 },
  { label: "少年", base: 10, dice: 2 },
  { label: "青年", base: 15, dice: 3 },
  { label: "中年", base: 25, dice: 4 },
  { label: "壮年", base: 40, dice: 5 },
  { label: "老人", base: 60, dice: 6 },
];

const HOMETOWN_CHART = {
  main: {
    1: "日本",
    2: "中国",
    3: "東アジア",
    4: "ロシア",
    5: "MINOR",
    6: "MINOR",
  },
  minor: {
    1: "西アジア",
    2: "ヒスパニック",
    3: "欧米",
    4: "アフリカ",
    5: "SPECIAL",
    6: "SPECIAL",
  },
};

// ---------------------------------------------------
// 4. 通り名 & 好嫌
// ---------------------------------------------------
const NICKNAME_TABLE_1 = {
  11: "キャラクターのアジトの（例：軍艦島の、十三の）",
  12: "マグナム",
  13: "ブラック／暗黒",
  14: "ミスター／ミス",
  15: "拳銃",
  16: "ドクター",
  22: "最後の",
  23: "時計じかけの",
  24: "紅の",
  25: "狂い咲き",
  26: "地獄",
  33: "抜き撃ちの",
  34: "ゼロゼロ／ダブルオー",
  35: "怪盗",
  36: "朝露に舞う",
  44: "片腕",
  45: "おっぱい",
  46: "くるぐる",
  55: "機動戦士",
  56: "聖（セイント）",
  66: "キャラクターの故郷の（例：アメリカの、大阪の）",
};
const NICKNAME_TABLE_2 = {
  11: "キャラクターの現在最も低い能力値の称号（例：甘ちゃん、貧弱）",
  12: "少年／少女（ボーイ／ガール）",
  13: "三世",
  14: "ピンク",
  15: "オレンジ",
  16: "発電機",
  22: "星人",
  23: "紳士",
  24: "マハラジャ",
  25: "スーパースター",
  26: "伝説",
  33: "狼／ウルフ",
  34: "鮫／シャーク",
  35: "豹／パンサー",
  36: "蝶々",
  44: "若大将",
  45: "渡り鳥",
  46: "流れ星",
  55: "無頼",
  56: "殺し",
  66: "キャラクターの現在最も高い能力値の称号（例：快楽天、強靭）",
};

// 好嫌表
// D66（行） x 1D6（列: 1-2, 3-4, 5-6）
const LIKES_TABLE = {
  11: ["列強の兵士", "地獄組", "沙京流氓"],
  12: [
    "蜘蛛",
    "「4」あるいは「死」という数字、言葉",
    "将来の夢について語りあうこと",
  ],
  13: ["犬", "路地裏ネズミ", "猫"],
  14: ["タバコの煙", "ジッポーを弄ぶ", "飛び散る薬莢と硝煙の匂い"],
  15: ["官庁街、ビルのてっぺんから見下ろす風景", "通天閣のある風景", "地獄湯"],
  16: ["夕暮れ", "夜", "青空"],
  22: ["懐に感じる銃の重み", "眠りに落ちる瞬間", "新札のパリパリとした手触り"],
  23: ["自動車", "飛行機", "船"],
  24: ["ミナミの猥雑な空気", "エルヴィス", "バー「JAIL HOUSE」の喧噪"],
  25: ["ウィスキー", "シャワーを浴びてから飲むビール", "コーラ"],
  26: ["ヤクザ映画", "テレビドラマ", "ドキュメンタリー映画"],
  33: ["大帮", "大阪市警", "コンビナート"],
  34: [
    "十三の懐かしい街並み",
    "中華街から漂う食べ物の匂い",
    "軍艦島の無骨な建物群",
  ],
  35: ["報道番組", "ネット", "携帯電話"],
  36: ["演歌", "ロックンロール", "ダンスミュージック"],
  44: ["年寄り", "童話", "略語、あるいは下品な言葉遣い"],
  45: ["盟約に所属しない亜侠", "独立系盟約", "ストリートキッズ"],
  46: ["迷信、ジンクス", "太陽の塔", "ナニワ地下帝国の住人"],
  55: ["バカ", "お祭り騒ぎ、御堂筋パレード", "ムダ話"],
  56: ["日本食", "中華料理", "ジャンクフード"],
  66: ["屋台", "バー", "コンビニ"],
};
// 外見 (D66)
const APPEARANCE_TABLE = {
  11: "凡俗",
  12: "亜侠",
  13: "冷笑泡",
  14: "黒太子",
  15: "耽美",
  16: "御宅",
  22: "富士山",
  23: "堅茹卵",
  24: "洒落者",
  25: "不良",
  26: "学生服",
  33: "太平愛",
  34: "丁氏",
  35: "尻跳楽",
  36: "廃児",
  44: "未来系",
  45: "南国彩",
  46: "健康美",
  55: "造反有理",
  56: "絢爛豪華",
  66: "遊戯装束",
};

// 特徴 (D66の外見に対応する1D6表)
// キーは外見のD66出目
const FEATURE_TABLE_ROWS = {
  // 10代
  11: [
    "ビジネススーツ",
    "Tシャツにジーンズ",
    "ネルシャツやデニムシャツ",
    "今流行している格好",
    "一昔前に流行した格好",
    "おばさん、おじさんスタイル",
  ],
  12: [
    "アジア系タトゥ・京劇風メイク",
    "チャイナドレスやアオザイ、人民服",
    "ガラベーヤとターバン",
    "サリー",
    "帯やロンジー（巻きスカート）",
    "チマやパジとチョゴリ",
  ],
  13: [
    "カラーグラス",
    "缶バッヂ",
    "プラスチックアクセ",
    "スニーカー",
    "カラフルなスキニーTシャツ（ピタT）",
    "マッシュルームカット",
  ],
  14: [
    "革ジャン",
    "タトゥー、ピアス、ブランディング（焼き印）など",
    "目張り、隈取りなどのメイク",
    "安全ピン・鎖・鋲・チョーカー",
    "破れたTシャツとジーンズ",
    "モヒカンなど奇抜なヘアスタイル",
  ],
  15: [
    "ビスクドール",
    "ボンデージ",
    "黒メイク",
    "フリルやレースを使った衣装",
    "マントやロングコート",
    "十字架や目玉などの神秘的なアクセサリー",
  ],
  16: [
    "眼鏡",
    "キャラもののプリントTシャツ",
    "バンダナ",
    "紙袋",
    "指抜きグローブ",
    "アニメやゲームのコスプレ",
  ],

  // 20代
  22: [
    "ちょんまげ、日本髪",
    "紋付き袴、着物",
    "忍者装束",
    "日本刀",
    "旧帝国軍服",
    "きせる、扇子、かんざしなどの小物",
  ],
  23: [
    "トレンチコート",
    "煙草",
    "無精ひげ",
    "ソフト帽",
    "くたびれたYシャツ",
    "サスペンダー",
  ],
  24: [
    "光沢のあるモッズスーツ",
    "ポロシャツ",
    "アイラインを強調したメイク",
    "ヘアピース（つけ髪）",
    "シルバーアクセ",
    "エナメル系のローファー、ロングブーツ",
  ],
  25: [
    "長ランとボンタン、長スカート",
    "労働者風の格好",
    "特攻服",
    "リーゼント",
    "派手な刺繍入りスカジャンや革ジャン",
    "サングラスやマスク",
  ],
  26: [
    "ブレザー",
    "学ラン",
    "セーラー服",
    "マイクロミニスカート",
    "アイヴィーシャツ",
    "ルーズソックスか紺ラルとローファー",
  ],

  // 30代
  33: [
    "長髪",
    "ベルボトムジーンズ",
    "サイケなカラー、花柄",
    "ピースマーク、スマイルマーク",
    "カウボーイルック",
    "ボディペインティング",
  ],
  34: [
    "ダブルのスーツ",
    "シングルのスーツ",
    "ステッキ",
    "ブラックスーツ",
    "礼服",
    "葉巻",
  ],
  35: [
    "アフロヘア",
    "フード・パーカー",
    "ドレッドロック",
    "ゲットーブラスター※",
    "スパッツ",
    "金歯やネックレスなどのゴールドアクセ",
  ],
  36: [
    "ボロ布",
    "ワークパンツ",
    "廃品",
    "ジッパーやベルトなどのギミック",
    "エンジニア・ブーツ",
    "ゴーグルやガスマスクなど軍のサープラス",
  ],

  // 40代
  44: [
    "青や赤のボブカットのウィッグ",
    "メタリックな衣装",
    "奇妙な形のサングラス",
    "プラスティックや金属などの特殊素材",
    "電飾",
    "宇宙服",
  ],
  45: [
    "アロハシャツ",
    "レイ",
    "短パン",
    "ジャラジャラとした鍵束",
    "ポンチョ",
    "もみあげ",
  ],
  46: [
    "好きなチームのユニフォーム",
    "武術の道着",
    "水着や体操服",
    "ジャージ、バギーパンツ",
    "日焼けした肌",
    "XLのTシャツ",
  ],

  // 50代
  55: [
    "安物のジーンズ",
    "ヘルメット",
    "サングラス",
    "ゲバルト棒",
    "拡声器",
    "タオルによるマスク",
  ],
  56: [
    "毛皮",
    "豹柄などのアニマルプリント",
    "ボディコンシャス",
    "スウェードや蛇革などの高級素材",
    "シースルーの服",
    "ラメやスパンコール",
  ],

  // 60代
  66: ["着ぐるみ", "ナース服", "修道衣", "全身にタトゥ", "西洋甲冑", "裸"],
};

// ---------------------------------------------------
// 8. チーム名決定表 (完全版)
// ---------------------------------------------------
const TEAM_NAME_TABLE = {
  mainA: {
    11: "東洋",
    12: "極東",
    13: "大阪",
    14: "ナニワ",
    15: "道頓堀",
    16: "新世界",
    22: "淀川",
    23: "帝国",
    24: "青空",
    25: "21世紀",
    26: "赤色",
    33: "踊る",
    34: "走る",
    35: "空飛ぶ",
    36: "7人の",
    44: "万能",
    45: "突撃",
    46: "荒野の",
    55: "グレート",
    56: "マイティ",
    66: "アドバンスド",
  },
  mainB: {
    11: "最終",
    12: "夢見る",
    13: "血と薔薇と",
    14: "絶対",
    15: "まぼろしの",
    16: "敏度なる",
    22: "さまよう",
    23: "小さな",
    24: "はぐれ",
    25: "サイコ",
    26: "ミッドナイト",
    33: "怒れる",
    34: "純粋",
    35: "死せる",
    36: "よいどれ",
    44: "ウルトラ",
    45: "はだかの",
    46: "夜明けの",
    55: "紳士的",
    56: "デス",
  },
  subA: {
    11: "銀河",
    12: "国際",
    13: "平和",
    14: "戦闘",
    15: "電撃",
    16: "最強",
    22: "芸能",
    23: "爆発",
    24: "ダイナマイト",
    25: "トロピカル",
    26: "犯罪",
    33: "学園",
    34: "くそったれ",
    35: "七福神",
    36: "少年少女",
    44: "ハードコア",
    45: "ロックンロール",
    46: "ブルース",
    55: "キネマ",
    56: "外道",
  },
  subB: {
    11: "妄想",
    12: "永遠",
    13: "神様",
    14: "征服",
    15: "正論",
    16: "暴力",
    22: "シカバネ",
    23: "セクシー",
    24: "太陽",
    25: "煉獄",
    26: "詩人",
    33: "漂流",
    34: "クレイジー",
    35: "殺神",
    36: "心臓",
    44: "ゴスロリ",
    45: "野獣",
    46: "いい人",
    55: "星空",
    56: "B級",
  },
  orgA: {
    11: "リングス",
    12: "少年団",
    13: "同盟",
    14: "ボーイズ",
    15: "ドッグス",
    16: "軍団",
    22: "クラン",
    23: "一家",
    24: "倶楽部",
    25: "強盗団",
    26: "愚連隊",
    33: "ギャング",
    34: "軍団",
    35: "ブラザーズ（兄弟）",
    36: "カンパニー",
    44: "サーカス",
    45: "動物園",
    46: "シアター",
    55: "オーケストラ",
    56: "サーティーン",
    66: "ピストルズ",
  },
  orgB: {
    11: "サークル",
    12: "青年団",
    13: "プロジェクト",
    14: "ガールズ",
    15: "キャッツ",
    16: "イン・ザ・ダーク",
    22: "党",
    23: "組",
    24: "チルドレン",
    25: "パーティ",
    26: "探偵団",
    33: "研究会",
    34: "小隊",
    35: "シスターズ（姉妹）",
    36: ".COM",
    44: "賊、賊（トライブ）",
    45: "モンキーズ",
    46: "合唱団",
    55: "バンド",
    56: "師団",
    66: "ドラゴンズ",
  },
};

function getRandomFromObj(obj) {
  const keys = Object.keys(obj);
  return obj[keys[Math.floor(Math.random() * keys.length)]];
}
