// js/sw25_data.js
// キャラクター保管所のデータを元に、ジェネレーターで使いやすいよう整形したデータ集

window.sw25_data = {
  // 種族データ (Shuzoku)
  Races: {
    人族: [
      {
        name: "人間",
        stats: [2, 2, 2, 2, 2, 2],
        ability: "［剣の加護／運命変転］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "エルフ",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護／優しき水］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "エルフ（スノウエルフ）",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護／優しき水］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "エルフ（ミストエルフ）",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護／惑いの霧］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ドワーフ",
        stats: [3, 1, 2, 2, 1, 3],
        ability: "［暗視］［剣の加護／炎身］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ダークドワーフ",
        stats: [3, 1, 2, 1, 1, 3],
        ability: "［暗視］［黒炎の担い手］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "タビット",
        stats: [1, 1, 1, 2, 3, 2],
        ability: "［第六感］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "タビット（パイカ種タビット）",
        stats: [1, 1, 1, 2, 3, 2],
        ability: "［第六感］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "タビット（リパス種タビット）",
        stats: [1, 1, 1, 2, 3, 2],
        ability: "［第六感］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "ルーンフォーク",
        stats: [2, 1, 2, 2, 2, 1],
        ability: "［暗視］［HP変換］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "ルーンフォーク（護衛型ルーンフォーク）",
        stats: [2, 1, 2, 2, 2, 1],
        ability: "［暗視］［HP変換］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "ルーンフォーク（戦闘型ルーンフォーク）",
        stats: [2, 1, 2, 2, 2, 1],
        ability: "［暗視］［HP変換］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "ナイトメア（人間）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（エルフ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（ドワーフ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（リルドラケン）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（シャドウ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（ソレイユ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "リカント",
        stats: [1, 7, 2, 2, 5, 1],
        ability: "［獣変貌］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "リカント（大型草食獣リカント）",
        stats: [1, 7, 2, 2, 5, 1],
        ability: "［獣変貌］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "リカント（小型草食獣リカント）",
        stats: [1, 7, 2, 2, 5, 1],
        ability: "［獣変貌］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "リルドラケン",
        stats: [1, 2, 2, 3, 1, 2],
        ability: "［鱗の皮膚］［尻尾が武器］［剣の加護／風の翼］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "リルドラケン（小翼種リルドラケン）",
        stats: [1, 2, 2, 3, 1, 2],
        ability: "［鱗の皮膚］［尻尾が武器］［剣の加護／風の翼］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "リルドラケン（有毛種リルドラケン）",
        stats: [1, 2, 2, 3, 1, 2],
        ability: "［鱗の皮膚］［尻尾が武器］［剣の加護／風の翼］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "グラスランナー",
        stats: [2, 2, 1, 3, 1, 3],
        ability: "［マナ不干渉］［植物・昆虫との意思疎通］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "グラスランナー（アリーシャ）",
        stats: [2, 2, 1, 3, 1, 3],
        ability: "［マナ不干渉］［植物・昆虫との意思疎通］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "グラスランナー（クリメノス）",
        stats: [2, 2, 1, 3, 1, 3],
        ability: "［マナ不干渉］［植物・昆虫との意思疎通］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "メリア",
        stats: [1, 1, 1, 3, 1, 1],
        ability: "［繁茂する生命］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "メリア（カーニバラスメリア）",
        stats: [1, 1, 1, 3, 1, 1],
        ability: "［繁茂する生命］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "メリア（ファンギーメリア）",
        stats: [1, 1, 1, 3, 1, 1],
        ability: "［繁茂する生命］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "ティエンス",
        stats: [2, 2, 1, 7, 2, 8],
        ability: "［通じ合う意識］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ティエンス（ティエンス機解種）",
        stats: [2, 2, 1, 7, 2, 8],
        ability: "［通じ合う意識］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ティエンス（ティエンス魔解種）",
        stats: [2, 2, 1, 7, 2, 8],
        ability: "［通じ合う意識］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "レプラカーン",
        stats: [2, 1, 2, 2, 2, 2],
        ability: "［暗視］［見えざる手］［姿なき職人］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "レプラカーン（放浪種レプラカーン）",
        stats: [2, 1, 2, 2, 2, 2],
        ability: "［暗視］［見えざる手］［姿なき職人］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "レプラカーン（探索種レプラカーン）",
        stats: [2, 1, 2, 2, 2, 2],
        ability: "［暗視］［見えざる手］［姿なき職人］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "アルヴ",
        stats: [1, 7, 8, 2, 5, 1],
        ability: "［暗視］［吸精］",
      },
      {
        name: "シャドウ",
        stats: [1, 1, 2, 2, 2, 2],
        ability: "［暗視］［月光の守り］",
      },
      {
        name: "ソレイユ",
        stats: [1, 2, 5, 2, 1, 2],
        ability: "［輝く肉体］［太陽の再生］［太陽の子］",
      },
      {
        name: "スプリガン",
        stats: [1, 2, 1, 1, 2, 1],
        ability: "［暗視］［巨人化］",
      },
      {
        name: "アビスボーン",
        stats: [2, 1, 5, 2, 2, 1],
        ability: "［アビスカース付与］など",
      },
      {
        name: "ハイマン",
        stats: [2, 1, 2, 1, 1, 1],
        ability: "［デジャヴ］［魔法の申し子］",
      },
      {
        name: "フロウライト",
        stats: [2, 2, 3, 2, 1, 3],
        ability: "［魂の輝き］［鉱石の生命］［晶石の身体］",
      },
      {
        name: "フィー",
        stats: [2, 3, 1, 1, 1, 2],
        ability: "［妖精の加護］［浮遊］",
      },
      {
        name: "ミアキス",
        stats: [1, 2, 1, 2, 3, 2],
        ability: "［暗視］［猫変化］［獣性の発露］",
      },
      {
        name: "ヴァルキリー",
        stats: [2, 1, 2, 2, 1, 5],
        ability: "［戦乙女の光羽］［戦乙女の祝福］",
      },
      {
        name: "センティアン（ルミエル）",
        stats: [1, 2, 6, 6, 6, 6],
        ability: "［刻まれし聖印］など",
      },
      {
        name: "センティアン（カルディア）",
        stats: [1, 2, 6, 6, 6, 6],
        ability: "［刻まれし聖印］など",
      },
      {
        name: "ノーブルエルフ",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護/水の申し子］［カリスマ］［弱点(物理+2)］",
      },
      {
        name: "マナフレア",
        stats: [2, 5, 3, 2, 2, 5],
        ability: "［溢れるマナ］［マナの手］",
      },
      {
        name: "魔動天使",
        stats: [2, 5, 5, 2, 2, 2],
        ability: "［暗視］［鋼鉄の翼］［新たな契約の絆］［造られし強さ］",
      },
    ],
    蛮族: [
      {
        name: "ウィークリング（ガルーダ）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（タンノズ）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（バジリスク）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（ミノタウロス）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（マーマン）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ドレイク",
        stats: [1, 1, 2, 2, 3, 2],
        ability: "［暗視］［限定竜化］［光ブレス］［弱点(魔法+2)］",
      },
      {
        name: "ドレイクブロークン",
        stats: [1, 1, 2, 2, 3, 2],
        ability: "［暗視］［限定竜化］［光ブレス］［弱点(魔法+2)］",
      },
      {
        name: "バジリスク",
        stats: [5, 2, 2, 2, 1, 1],
        ability: "［邪視と瞳石］［猛毒の血液］［魔物化］［弱点(水氷+3)］",
      },
      {
        name: "ディアボロ",
        stats: [2, 2, 3, 2, 1, 5],
        ability: "［暗視］［飛行］［魔人の皮膚］［魔人化］［弱点(純EN+3)］",
      },
      {
        name: "ダークトロール",
        stats: [2, 1, 2, 3, 1, 2],
        ability: "［暗視］［弱体化］［体躯］［弱点(魔法+2)］",
      },
      {
        name: "アルボル",
        stats: [2, 2, 1, 7, 2, 2],
        ability: "［憤怒の炎］［弱点(炎+3)］",
      },
      {
        name: "バーバヤガー",
        stats: [2, 1, 1, 1, 2, 3],
        ability: "［魔女化］［魔女の火］［弱点(物理+2)］",
      },
      {
        name: "ケンタウロス",
        stats: [3, 1, 2, 2, 1, 2],
        ability: "［半馬半人］［馬人の武術］［弱点(土+3)］",
      },
      {
        name: "シザースコーピオン",
        stats: [5, 1, 2, 2, 2, 2],
        ability: "［暗視］［蠍人の身体］［蠍人の体術］［弱点(物理+2)］",
      },
      {
        name: "ドーン",
        stats: [3, 2, 1, 2, 2, 1],
        ability: "［暗視］［暗殺の心得］［親しき闇］［弱点(命中+1)］",
      },
      {
        name: "コボルド",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［種の限界］［軽視］［小さな匠］［弱点(魔法+2)］",
      },
      {
        name: "ラミア",
        stats: [1, 2, 1, 2, 2, 2],
        ability: "［暗視］［ラミアの身体］［吸血］［変化］［弱点(土+3)］",
      },
      {
        name: "ラルヴァ",
        stats: [1, 2, 3, 1, 2, 1],
        ability: "［暗視］［弱体化］［吸血の祝福］［忌むべき血］",
      },
      {
        name: "リザードマン",
        stats: [1, 2, 2, 2, 2, 1],
        ability: "［尻尾が武器］［水中活動］［無呼吸活動］［弱点(土+3)］",
      },
      {
        name: "ライカンスロープ",
        stats: [4, 4, 4, 3, 2, 2],
        ability: "［暗視］［獣人の力］［獣化］［弱点(銀+3)］",
      },
      {
        name: "バルカン",
        stats: [2, 1, 2, 3, 2, 1],
        ability: "［暗視］［炎無効］［バルカンの宝石］［弱点(水・氷+3)］",
      },
      {
        name: "センティアン（イグニス）",
        stats: [1, 2, 6, 6, 6, 6],
        ability: "［刻まれし聖印］など",
      },
    ],
    その他: [
      { name: "その他（自由記入）", stats: [0, 0, 0, 0, 0, 0], ability: "" },
    ],
  },

  // 生まれデータ (Umare25)
  Births: [
    { name: "魔動機師", stats: [8, 4, 9], exp: 2000, skills: ["マギテック"] },
    {
      name: "魔法使い",
      stats: [7, 4, 10],
      exp: 2000,
      skills: ["ソーサラー", "コンジャラー"],
    },
    {
      name: "軽戦士",
      stats: [10, 7, 4],
      exp: 2000,
      skills: ["フェンサー", "スカウト"],
    },
    { name: "一般人", stats: [7, 7, 7], exp: 3000, skills: [] },
    {
      name: "傭兵",
      stats: [7, 10, 4],
      exp: 2000,
      skills: ["ファイター", "グラップラー"],
    },
    { name: "神官", stats: [4, 8, 9], exp: 2000, skills: ["プリースト"] },
    {
      name: "妖精使い",
      stats: [6, 6, 9],
      exp: 2000,
      skills: ["フェアリーテイマー"],
    },
    { name: "冒険者", stats: [0, 0, 0], exp: 3000, skills: [] },
    { name: "斥候", stats: [10, 6, 5], exp: 2500, skills: ["スカウト"] },
    { name: "狩人", stats: [9, 7, 5], exp: 2500, skills: ["シューター"] },
    { name: "練体師", stats: [8, 8, 5], exp: 2500, skills: ["エンハンサー"] },
    { name: "魔導師", stats: [6, 5, 10], exp: 2000, skills: ["ソーサラー"] },
    { name: "拳闘士", stats: [8, 9, 4], exp: 2000, skills: ["グラップラー"] },
    { name: "剣士", stats: [9, 8, 4], exp: 2500, skills: ["フェンサー"] },
    { name: "学者", stats: [5, 7, 9], exp: 2500, skills: ["セージ"] },
    { name: "薬師", stats: [9, 4, 8], exp: 2500, skills: ["レンジャー"] },
    { name: "吟遊詩人", stats: [7, 5, 9], exp: 2500, skills: ["バード"] },
    {
      name: "趣味人",
      stats: [8, 5, 8],
      exp: 2000,
      skills: ["レンジャー", "バード"],
    },
    { name: "錬金術師", stats: [6, 7, 8], exp: 2500, skills: ["アルケミスト"] },
    { name: "軍師", stats: [7, 8, 6], exp: 2500, skills: ["ウォーリーダー"] },
    {
      name: "魔法戦士",
      stats: [5, 8, 8],
      exp: 1000,
      skills: ["ファイター", "ソーサラー"],
    },
    { name: "占い師", stats: [9, 3, 9], exp: 2500, skills: ["ミスティック"] },
    {
      name: "参謀",
      stats: [6, 5, 10],
      exp: 2000,
      skills: ["セージ", "ウォーリーダー"],
    },
    {
      name: "魔神使い",
      stats: [3, 8, 10],
      exp: 2000,
      skills: ["デーモンルーラー"],
    },
    { name: "魔工士", stats: [7, 8, 6], exp: 2500, skills: ["アーティザン"] },
    { name: "武官", stats: [7, 9, 5], exp: 2000, skills: ["ファイター"] },
    { name: "貴族", stats: [6, 7, 8], exp: 2500, skills: ["アリストクラシー"] },
    { name: "秘術師", stats: [7, 4, 10], exp: 2000, skills: ["グリモワール"] },
    {
      name: "魔術師",
      stats: [5, 7, 9],
      exp: 2000,
      skills: ["ソーサラー", "コンジャラー"],
    },
    { name: "乗り手", stats: [12, 5, 9], exp: 2500, skills: ["ライダー"] },
    {
      name: "戦奏士",
      stats: [10, 3, 13],
      exp: 2000,
      skills: ["バード", "ウォーリーダー"],
    },
    {
      name: "戦軍師",
      stats: [12, 4, 10],
      exp: 2000,
      skills: ["フェンサー", "ウォーリーダー"],
    },
    {
      name: "銃使い",
      stats: [7, 6, 7],
      exp: 1500,
      skills: ["シューター", "マギテック"],
    },
    {
      name: "錬金戦士",
      stats: [8, 7, 5],
      exp: 1500,
      skills: ["ファイター", "アルケミスト"],
    },
    { name: "楽師", stats: [7, 4, 11], exp: 2500, skills: ["バード"] },
    {
      name: "道化",
      stats: [12, 0, 13],
      exp: 2500,
      skills: ["アリストクラシー"],
    },
    { name: "呪術師", stats: [10, 12, 8], exp: 2000, skills: ["コンジャラー"] },
    { name: "戦士", stats: [12, 14, 4], exp: 2000, skills: ["ファイター"] },
    {
      name: "神官戦士",
      stats: [12, 12, 6],
      exp: 1000,
      skills: ["ファイター", "プリースト"],
    },
    { name: "騎手", stats: [8, 12, 8], exp: 2500, skills: ["ライダー"] },
    {
      name: "密偵",
      stats: [15, 0, 10],
      exp: 2000,
      skills: ["フェンサー", "スカウト"],
    },
    {
      name: "神官闘士",
      stats: [8, 13, 5],
      exp: 1000,
      skills: ["プリースト", "グラップラー"],
    },
    {
      name: "神学者",
      stats: [6, 11, 9],
      exp: 1500,
      skills: ["プリースト", "セージ"],
    },
    {
      name: "神楽師",
      stats: [5, 14, 7],
      exp: 1500,
      skills: ["プリースト", "バード"],
    },
    {
      name: "神操術士",
      stats: [4, 12, 10],
      exp: 1000,
      skills: ["プリースト", "コンジャラー"],
    },
    {
      name: "魔動神官",
      stats: [9, 9, 8],
      exp: 1000,
      skills: ["プリースト", "マギテック"],
    },
    {
      name: "魔神操者",
      stats: [7, 10, 9],
      exp: 1000,
      skills: ["プリースト", "デーモンルーラー"],
    },
    {
      name: "秘術神官",
      stats: [8, 6, 7],
      exp: 1000,
      skills: ["プリースト", "グリモワール"],
    },
    {
      name: "魔工神官",
      stats: [8, 4, 8],
      exp: 1500,
      skills: ["プリースト", "アーティザン"],
    },
    {
      name: "妖精貴師",
      stats: [10, 5, 13],
      exp: 1500,
      skills: ["フェアリーテイマー", "アリストクラシー"],
    },
    {
      name: "貴神官",
      stats: [10, 6, 12],
      exp: 1500,
      skills: ["プリースト", "アリストクラシー"],
    },
    {
      name: "貴学者",
      stats: [10, 4, 14],
      exp: 2000,
      skills: ["セージ", "アリストクラシー"],
    },
    {
      name: "野伏貴族",
      stats: [12, 6, 10],
      exp: 2000,
      skills: ["レンジャー", "アリストクラシー"],
    },
    {
      name: "密偵貴師",
      stats: [13, 5, 10],
      exp: 2000,
      skills: ["スカウト", "アリストクラシー"],
    },
    {
      name: "魔神貴師",
      stats: [10, 3, 15],
      exp: 1500,
      skills: ["デーモンルーラー", "アリストクラシー"],
    },
    {
      name: "魔導貴師",
      stats: [9, 4, 15],
      exp: 500,
      skills: ["ソーサラー", "コンジャラー", "アリストクラシー"],
    },
    {
      name: "軽戦貴師",
      stats: [12, 5, 11],
      exp: 1500,
      skills: ["フェンサー", "アーティザン", "アリストクラシー"],
    },
    { name: "歌手", stats: [6, 5, 7], exp: 1500, skills: ["バード"] },
    { name: "魔操者", stats: [7, 7, 4], exp: 2500, skills: ["アーティザン"] },
    {
      name: "指揮官",
      stats: [6, 7, 5],
      exp: 500,
      skills: ["アリストクラシー"],
    },
    { name: "森羅導師", stats: [9, 7, 9], exp: 2000, skills: ["ドルイド"] },
    {
      name: "天地使い",
      stats: [10, 7, 8],
      exp: 2500,
      skills: ["ジオマンサー"],
    },
    {
      name: "踊り子",
      stats: [13, 6, 6],
      exp: 2000,
      skills: ["バトルダンサー"],
    },
    { name: "暗殺者", stats: [12, 6, 9], exp: 2500, skills: ["フェンサー"] },
    {
      name: "部位操者",
      stats: [12, 14, 6],
      exp: 2500,
      skills: ["フィジカルマスター"],
    },
    { name: "賢者", stats: [11, 13, 8], exp: 2500, skills: ["セージ"] },
    {
      name: "舞い手",
      stats: [11, 11, 6],
      exp: 2000,
      skills: ["バトルダンサー"],
    },
    { name: "隠者", stats: [10, 9, 12], exp: 2500, skills: ["セージ"] },
    {
      name: "癒し手",
      stats: [7, 8, 13],
      exp: 1500,
      skills: ["フェアリーテイマー", "レンジャー"],
    },
    {
      name: "剣の舞手",
      stats: [8, 9, 11],
      exp: 1500,
      skills: ["フェアリーテイマー", "フェンサー"],
    },
    {
      name: "召喚士",
      stats: [6, 7, 15],
      exp: 1000,
      skills: ["コンジャラー", "フェアリーテイマー"],
    },
    {
      name: "妖精学者",
      stats: [7, 7, 14],
      exp: 1500,
      skills: ["フェアリーテイマー", "セージ"],
    },
    {
      name: "妖精戦士",
      stats: [9, 9, 10],
      exp: 1000,
      skills: ["ファイター", "フェアリーテイマー"],
    },
    {
      name: "妖精軍師",
      stats: [8, 8, 12],
      exp: 1500,
      skills: ["フェアリーテイマー", "ウォーリーダー"],
    },
    {
      name: "妖魔術師",
      stats: [5, 7, 16],
      exp: 1000,
      skills: ["ソーサラー", "フェアリーテイマー"],
    },
    {
      name: "秘術妖精",
      stats: [8, 7, 13],
      exp: 1000,
      skills: ["フェアリーテイマー", "グリモワール"],
    },
    {
      name: "魔工妖精",
      stats: [8, 8, 12],
      exp: 1500,
      skills: ["フェアリーテイマー", "アーティザン"],
    },
    { name: "騎兵", stats: [15, 6, 6], exp: 2500, skills: ["ライダー"] },
    { name: "文官", stats: [8, 7, 11], exp: 2500, skills: ["セージ"] },
    { name: "彷徨い人", stats: [12, 2, 11], exp: 2500, skills: ["スカウト"] },
    {
      name: "操霊術士",
      stats: [7, 4, 10],
      exp: 2000,
      skills: ["コンジャラー"],
    },
    { name: "歌人", stats: [5, 7, 9], exp: 2500, skills: ["バード"] },
  ],

  // 技能リスト (Ginou)
  Skills: [
    { name: "ファイター", type: "A" },
    { name: "グラップラー", type: "A" },
    { name: "フェンサー", type: "B" },
    { name: "シューター", type: "B" },
    { name: "ソーサラー", type: "A" },
    { name: "コンジャラー", type: "A" },
    { name: "プリースト", type: "A" },
    { name: "フェアリーテイマー", type: "A" },
    { name: "マギテック", type: "A" },
    { name: "スカウト", type: "B" },
    { name: "レンジャー", type: "B" },
    { name: "セージ", type: "B" },
    { name: "エンハンサー", type: "B" },
    { name: "バード", type: "B" },
    { name: "アルケミスト", type: "B" },
    { name: "ライダー", type: "B" },
    { name: "デーモンルーラー", type: "A" },
    { name: "ウォーリーダー", type: "B" },
    { name: "ミスティック", type: "B" },
    { name: "フィジカルマスター", type: "B" },
    { name: "グリモワール", type: "A" },
    { name: "アーティザン", type: "B" },
    { name: "アリストクラシー", type: "B" },
    { name: "ドルイド", type: "A" },
    { name: "ジオマンサー", type: "B" },
    { name: "バトルダンサー", type: "A" },
    { name: "アビスゲイザー", type: "A" },
    { name: "ダークハンター", type: "B" },
  ],

  // 戦闘特技データ (NVTokugi)
  CombatFeats: [
    { name: "足さばき", level: 9, prereq: "" },
    { name: "ガーディアン", level: 5, prereq: "" },
    { name: "カード軽減", level: 5, prereq: "" },
    { name: "かいくぐり", level: 1, prereq: "盾" },
    { name: "回避行動", level: 3, prereq: "" },
    { name: "頑強", level: 5, prereq: "" },
    { name: "超頑強", level: 7, prereq: "" },
    { name: "キャパシティ", level: 11, prereq: "" },
    { name: "自己占瞳", level: 5, prereq: "" },
    { name: "射手の体術", level: 7, prereq: "" },
    { name: "スローイング", level: 1, prereq: "" },
    { name: "ターゲッティング", level: 1, prereq: "" },
    { name: "占瞳操作", level: 5, prereq: "" },
    { name: "双撃", level: 1, prereq: "" },
    { name: "代償軽減", level: 3, prereq: "" },
    { name: "鷹の目", level: 1, prereq: "" },
    { name: "投げ強化", level: 3, prereq: "" },
    { name: "二刀流", level: 5, prereq: "" },
    { name: "二刀無双", level: 11, prereq: "" },
    { name: "ハーモニー", level: 5, prereq: "" },
    { name: "武器習熟Ａ／ソード", level: 0, prereq: "" },
    { name: "武器習熟Ａ／アックス", level: 0, prereq: "" },
    { name: "武器習熟Ａ／スピア", level: 0, prereq: "" },
    { name: "武器習熟Ａ／メイス", level: 0, prereq: "" },
    { name: "武器習熟Ａ／スタッフ", level: 0, prereq: "" },
    { name: "武器習熟Ａ／フレイル", level: 0, prereq: "" },
    { name: "武器習熟Ａ／ウォーハンマー", level: 0, prereq: "" },
    { name: "武器習熟Ａ／格闘", level: 0, prereq: "" },
    { name: "武器習熟Ａ／投擲", level: 0, prereq: "" },
    { name: "武器習熟Ａ／ボウ", level: 0, prereq: "" },
    { name: "武器習熟Ａ／クロスボウ", level: 0, prereq: "" },
    { name: "武器習熟Ａ／ガン", level: 0, prereq: "" },
    { name: "武器習熟Ａ／絡み", level: 0, prereq: "" },
    { name: "武器習熟Ｓ／ソード", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／アックス", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／スピア", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／メイス", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／スタッフ", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／フレイル", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／ウォーハンマー", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／格闘", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／投擲", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／ボウ", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／クロスボウ", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／ガン", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／絡み", level: 5, prereq: "" },
    { name: "武器の達人", level: 11, prereq: "" },
    { name: "賦術強化", level: 3, prereq: "" },
    { name: "賦術の極意", level: 7, prereq: "" },
    { name: "踏みつけ", level: 5, prereq: "" },
    { name: "ブロッキング", level: 3, prereq: "" },
    { name: "防具習熟Ａ／非金属鎧", level: 0, prereq: "" },
    { name: "防具習熟Ａ／金属鎧", level: 0, prereq: "" },
    { name: "防具習熟Ａ／盾", level: 0, prereq: "" },
    { name: "防具習熟Ｓ／非金属鎧", level: 5, prereq: "" },
    { name: "防具習熟Ｓ／金属鎧", level: 5, prereq: "" },
    { name: "防具習熟Ｓ／盾", level: 5, prereq: "" },
    { name: "防具の達人", level: 11, prereq: "" },
    { name: "魔晶石の達人", level: 9, prereq: "" },
    { name: "魔法制御", level: 0, prereq: "" },
    { name: "魔力強化", level: 6, prereq: "" },
    { name: "魔力撃強化", level: 9, prereq: "" },
    { name: "マルチガード", level: 7, prereq: "" },
    { name: "命中強化", level: 7, prereq: "" },
    { name: "両手利き", level: 1, prereq: "" },
    { name: "連続賦術", level: 5, prereq: "" },
    { name: "練体の極意", level: 5, prereq: "" },
    { name: "ワードブレイク", level: 1, prereq: "" },
    { name: "ＭＰ軽減／ソーサラー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／コンジャラー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／プリースト", level: 5, prereq: "" },
    { name: "ＭＰ軽減／フェアリーテイマー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／マギテック", level: 5, prereq: "" },
    { name: "ＭＰ軽減／デーモンルーラー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／ウィザード", level: 5, prereq: "" },
    { name: "インファイト", level: 5, prereq: "" },
    { name: "囮攻撃", level: 1, prereq: "" },
    { name: "影矢", level: 9, prereq: "ガン除く射撃武器" },
    { name: "かばう", level: 1, prereq: "" },
    { name: "牙折り", level: 9, prereq: "" },
    { name: "斬り返し", level: 1, prereq: "2H近接武器" },
    { name: "クリティカルキャスト", level: 7, prereq: "" },
    { name: "牽制攻撃", level: 1, prereq: "" },
    { name: "全力攻撃", level: 1, prereq: "" },
    { name: "双占瞳", level: 7, prereq: "" },
    { name: "狙撃", level: 1, prereq: "2H射撃武器" },
    { name: "ダブルキャスト", level: 9, prereq: "" },
    { name: "挑発攻撃", level: 1, prereq: "" },
    { name: "ディフェンススタンス", level: 1, prereq: "" },
    { name: "テイルスイング", level: 3, prereq: "" },
    { name: "飛び蹴り", level: 9, prereq: "" },
    { name: "なぎ払い", level: 3, prereq: "2H近接武器" },
    { name: "マリオネット", level: 5, prereq: "" },
    { name: "必殺攻撃", level: 1, prereq: "" },
    { name: "魔法拡大／威力確実化", level: 1, prereq: "" },
    { name: "魔法拡大／確実化", level: 1, prereq: "" },
    { name: "魔法拡大／数", level: 1, prereq: "" },
    { name: "魔法拡大／距離", level: 1, prereq: "" },
    { name: "魔法拡大／時間", level: 1, prereq: "" },
    { name: "魔法拡大／範囲", level: 1, prereq: "" },
    { name: "魔法収束", level: 1, prereq: "" },
    { name: "魔力撃", level: 1, prereq: "" },
    { name: "マルチアクション", level: 5, prereq: "" },
    { name: "切り払い", level: 16, prereq: "ファイター" },
    { name: "無尽の盾", level: 16, prereq: "ファイター" },
    { name: "痛撃", level: 16, prereq: "ファイター" },
    { name: "ファントムカウンター", level: 16, prereq: "グラップラー" },
    { name: "跳躍攻撃", level: 16, prereq: "グラップラー" },
    { name: "封印撃", level: 16, prereq: "グラップラー" },
    { name: "急所狙い", level: 16, prereq: "フェンサー" },
    { name: "心眼", level: 16, prereq: "フェンサー" },
    { name: "ヒット＆アウェイ", level: 16, prereq: "フェンサー" },
    { name: "零距離射撃", level: 16, prereq: "シューター" },
    { name: "曲射", level: 16, prereq: "シューター" },
    { name: "デュアルアクション", level: 16, prereq: "シューター" },
    { name: "ＭＰ軽減／グリモワール", level: 5, prereq: "" },
    { name: "魔導書習熟Ａ", level: 1, prereq: "グリモワール" },
    { name: "魔導書習熟Ｓ", level: 3, prereq: "グリモワール" },
    { name: "魔導書の達人", level: 11, prereq: "グリモワール" },
    { name: "魔器習熟Ａ", level: 1, prereq: "" },
    { name: "魔器習熟Ｓ", level: 5, prereq: "アーティザン" },
    { name: "魔器の達人", level: 11, prereq: "アーティザン" },
    { name: "変幻自在", level: 5, prereq: "" },
    { name: "魔法拡大の達人", level: 1, prereq: "" },
    { name: "バイオレントキャスト", level: 1, prereq: "" },
    { name: "魔法拡大／すべて", level: 3, prereq: "" },
    { name: "鎧貫き", level: 1, prereq: "" },
    { name: "終律増強", level: 3, prereq: "バード" },
    { name: "呪歌追加", level: 1, prereq: "バード" },
    { name: "特殊楽器習熟", level: 1, prereq: "バード" },
    { name: "楽素転換", level: 3, prereq: "バード" },
    { name: "シュアパフォーマー", level: 3, prereq: "バード" },
    { name: "スキルフルプレイ", level: 7, prereq: "バード" },
    { name: "賦術全遠隔化", level: 5, prereq: "アルケミスト" },
    { name: "ＭＰ軽減／ドルイド", level: 5, prereq: "" },
    { name: "追い打ち", level: 1, prereq: "" },
    { name: "抵抗強化", level: 3, prereq: "" },
    { name: "カニングキャスト", level: 1, prereq: "" },
    { name: "クイックキャスト", level: 1, prereq: "" },
    { name: "シールドバッシュ", level: 1, prereq: "" },
    { name: "シャドウステップ", level: 1, prereq: "" },
    { name: "捨て身攻撃", level: 1, prereq: "" },
    { name: "露払い", level: 1, prereq: "" },
    { name: "乱撃", level: 1, prereq: "" },
    { name: "掠め取り", level: 5, prereq: "" },
    { name: "クルードテイク", level: 5, prereq: "" },
    { name: "相克の標的", level: 1, prereq: "ジオマンサー" },
    { name: "相克の別離", level: 3, prereq: "ジオマンサー" },
    { name: "鼓咆陣率追加", level: 1, prereq: "ウォーリーダー" },
    { name: "先陣の才覚", level: 5, prereq: "ウォーリーダー" },
    { name: "高度な柔軟性", level: 9, prereq: "ウォーリーダー" },
    { name: "ＭＰ軽減／アビスゲイザー", level: 5, prereq: "アビスゲイザー" },
  ],

  // 武器カテゴリ (EqCategory)
  WeaponClasses: {
    ソード: { type: "1H", skill: "フェンサー" },
    アックス: { type: "1H", skill: "フェンサー" },
    スピア: { type: "1H", skill: "フェンサー" },
    メイス: { type: "1H", skill: "フェンサー" },
    スタッフ: { type: "2H", skill: "フェンサー" },
    フレイル: { type: "1H", skill: "フェンサー" },
    ウォーハンマー: { type: "1H", skill: "フェンサー" },
    格闘: { type: "1H", skill: "グラップラー" },
    投擲: { type: "1H", skill: "シューター" },
    ボウ: { type: "2H", skill: "シューター" },
    クロスボウ: { type: "2H", skill: "シューター" },
    ガン: { type: "1H", skill: "シューター" },
    絡み: { type: "1H", skill: "フェンサー" },
  },
  ArmourClasses: {
    非金属鎧: { skill: "フェンサー" },
    金属鎧: { skill: "ファイター" },
    盾: { skill: "ファイター" },
  },
  Weapons: [
    {
      name: "ナイフ",
      cls: "ソード",
      rank: "B",
      req: 1,
      acc: 0,
      hands: 1,
      might: 1,
      crit: 10,
      price: 30,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "スティレット",
      cls: "ソード",
      rank: "B",
      req: 2,
      acc: 0,
      hands: 1,
      might: 2,
      crit: 10,
      price: 40,
      note: "",
      isMagic: false,
    },
    {
      name: "ダガー",
      cls: "ソード",
      rank: "B",
      req: 3,
      acc: 0,
      hands: 1,
      might: 3,
      crit: 10,
      price: 50,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "ククリ",
      cls: "ソード",
      rank: "B",
      req: 4,
      acc: 0,
      hands: 1,
      might: 4,
      crit: 10,
      price: 60,
      note: "",
      isMagic: false,
    },
    {
      name: "ショートソード",
      cls: "ソード",
      rank: "B",
      req: 5,
      acc: 0,
      hands: 1,
      might: 5,
      crit: 10,
      price: 80,
      note: "",
      isMagic: false,
    },
    {
      name: "エペ",
      cls: "ソード",
      rank: "B",
      req: 6,
      acc: 0,
      hands: 1,
      might: 6,
      crit: 10,
      price: 90,
      note: "",
      isMagic: false,
    },
    {
      name: "カッツバルゲル",
      cls: "ソード",
      rank: "B",
      req: 7,
      acc: 0,
      hands: 1,
      might: 7,
      crit: 10,
      price: 100,
      note: "",
      isMagic: false,
    },
    {
      name: "レイピア",
      cls: "ソード",
      rank: "B",
      req: 8,
      acc: 0,
      hands: 1,
      might: 8,
      crit: 10,
      price: 110,
      note: "",
      isMagic: false,
    },
    {
      name: "サーベル",
      cls: "ソード",
      rank: "B",
      req: 10,
      acc: 0,
      hands: 1,
      might: 10,
      crit: 10,
      price: 190,
      note: "",
      isMagic: false,
    },
    {
      name: "エストック",
      cls: "ソード",
      rank: "B",
      req: 11,
      acc: 0,
      hands: 2,
      might: 21,
      crit: 10,
      price: 370,
      note: "",
      isMagic: false,
    },
    {
      name: "ロングソード",
      cls: "ソード",
      rank: "B",
      req: 13,
      acc: 0,
      hands: 1,
      might: 13,
      crit: 10,
      price: 440,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ロングソード(両手)",
      cls: "ソード",
      rank: "B",
      req: 13,
      acc: 0,
      hands: 2,
      might: 23,
      crit: 10,
      price: 440,
      note: "",
      isMagic: false,
    },
    {
      name: "ブロードソード",
      cls: "ソード",
      rank: "B",
      req: 15,
      acc: 0,
      hands: 1,
      might: 15,
      crit: 10,
      price: 340,
      note: "",
      isMagic: false,
    },
    {
      name: "バスタードソード",
      cls: "ソード",
      rank: "B",
      req: 17,
      acc: 0,
      hands: 1,
      might: 17,
      crit: 10,
      price: 560,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "バスタードソード(両手)",
      cls: "ソード",
      rank: "B",
      req: 17,
      acc: 0,
      hands: 2,
      might: 27,
      crit: 10,
      price: 560,
      note: "",
      isMagic: false,
    },
    {
      name: "ファルシオン",
      cls: "ソード",
      rank: "B",
      req: 18,
      acc: 0,
      hands: 2,
      might: 28,
      crit: 10,
      price: 790,
      note: "",
      isMagic: false,
    },
    {
      name: "ツーハンドソード",
      cls: "ソード",
      rank: "B",
      req: 20,
      acc: 0,
      hands: 2,
      might: 30,
      crit: 10,
      price: 860,
      note: "",
      isMagic: false,
    },
    {
      name: "シャムシール",
      cls: "ソード",
      rank: "B",
      req: 22,
      acc: 0,
      hands: 2,
      might: 32,
      crit: 10,
      price: 950,
      note: "",
      isMagic: false,
    },
    {
      name: "グレートソード",
      cls: "ソード",
      rank: "B",
      req: 24,
      acc: 0,
      hands: 2,
      might: 34,
      crit: 10,
      price: 1020,
      note: "",
      isMagic: false,
    },
    {
      name: "ファストスパイク",
      cls: "ソード",
      rank: "A",
      req: 1,
      acc: 0,
      hands: 1,
      might: 6,
      crit: 10,
      price: 820,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "フリッサ",
      cls: "ソード",
      rank: "A",
      req: 8,
      acc: 0,
      hands: 1,
      might: 13,
      crit: 10,
      price: 880,
      note: "",
      isMagic: false,
    },
    {
      name: "スキアヴォーナ",
      cls: "ソード",
      rank: "A",
      req: 11,
      acc: 0,
      hands: 1,
      might: 16,
      crit: 10,
      price: 990,
      note: "",
      isMagic: false,
    },
    {
      name: "ディフェンダー",
      cls: "ソード",
      rank: "A",
      req: 12,
      acc: 0,
      hands: 1,
      might: 17,
      crit: 10,
      price: 1770,
      note: "防護点+1",
      isMagic: false,
    },
    {
      name: "タルワール",
      cls: "ソード",
      rank: "A",
      req: 15,
      acc: 0,
      hands: 1,
      might: 20,
      crit: 10,
      price: 1210,
      note: "",
      isMagic: false,
    },
    {
      name: "スティールブレイド",
      cls: "ソード",
      rank: "A",
      req: 19,
      acc: 0,
      hands: 1,
      might: 24,
      crit: 10,
      price: 1450,
      note: "",
      isMagic: false,
    },
    {
      name: "フランベルジュ",
      cls: "ソード",
      rank: "A",
      req: 23,
      acc: 0,
      hands: 1,
      might: 28,
      crit: 10,
      price: 1580,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "フランベルジュ(両手)",
      cls: "ソード",
      rank: "A",
      req: 23,
      acc: 0,
      hands: 2,
      might: 38,
      crit: 10,
      price: 1580,
      note: "",
      isMagic: false,
    },
    {
      name: "ドラゴンスレイヤー",
      cls: "ソード",
      rank: "A",
      req: 28,
      acc: 0,
      hands: 2,
      might: 43,
      crit: 10,
      price: 2760,
      note: "",
      isMagic: false,
    },
    {
      name: "シックル",
      cls: "アックス",
      rank: "B",
      req: 4,
      acc: 0,
      hands: 1,
      might: 9,
      crit: 11,
      price: 40,
      note: "",
      isMagic: false,
    },
    {
      name: "ハンドアックス",
      cls: "アックス",
      rank: "B",
      req: 7,
      acc: 0,
      hands: 1,
      might: 12,
      crit: 11,
      price: 90,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "ブージ",
      cls: "アックス",
      rank: "B",
      req: 11,
      acc: 0,
      hands: 1,
      might: 16,
      crit: 11,
      price: 240,
      note: "",
      isMagic: false,
    },
    {
      name: "バトルアックス",
      cls: "アックス",
      rank: "B",
      req: 16,
      acc: 0,
      hands: 1,
      might: 21,
      crit: 11,
      price: 360,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "バトルアックス(両手)",
      cls: "アックス",
      rank: "B",
      req: 16,
      acc: 0,
      hands: 2,
      might: 31,
      crit: 11,
      price: 360,
      note: "",
      isMagic: false,
    },
    {
      name: "グレートアックス",
      cls: "アックス",
      rank: "B",
      req: 18,
      acc: 0,
      hands: 2,
      might: 33,
      crit: 11,
      price: 410,
      note: "",
      isMagic: false,
    },
    {
      name: "ヘビーアックス",
      cls: "アックス",
      rank: "B",
      req: 20,
      acc: 0,
      hands: 1,
      might: 25,
      crit: 11,
      price: 440,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ヘビーアックス(両手)",
      cls: "アックス",
      rank: "B",
      req: 20,
      acc: 0,
      hands: 2,
      might: 35,
      crit: 11,
      price: 440,
      note: "",
      isMagic: false,
    },
    {
      name: "ブローバ",
      cls: "アックス",
      rank: "B",
      req: 22,
      acc: 0,
      hands: 2,
      might: 37,
      crit: 11,
      price: 490,
      note: "",
      isMagic: false,
    },
    {
      name: "ミノタウロスアックス",
      cls: "アックス",
      rank: "B",
      req: 30,
      acc: 0,
      hands: 2,
      might: 45,
      crit: 11,
      price: 950,
      note: "",
      isMagic: false,
    },
    {
      name: "トマホーク",
      cls: "アックス",
      rank: "A",
      req: 7,
      acc: 0,
      hands: 1,
      might: 17,
      crit: 11,
      price: 630,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "タバルジン",
      cls: "アックス",
      rank: "A",
      req: 13,
      acc: 0,
      hands: 1,
      might: 23,
      crit: 11,
      price: 840,
      note: "",
      isMagic: false,
    },
    {
      name: "ロングアックス(振)",
      cls: "アックス",
      rank: "A",
      req: 16,
      acc: 0,
      hands: 2,
      might: 36,
      crit: 11,
      price: 990,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "ロングアックス(突)",
      cls: "アックス",
      rank: "A",
      req: 16,
      acc: 0,
      hands: 2,
      might: 31,
      crit: 10,
      price: 990,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "ハルバード(振)",
      cls: "アックス",
      rank: "A",
      req: 20,
      acc: 0,
      hands: 2,
      might: 40,
      crit: 11,
      price: 1080,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "ハルバード(突)",
      cls: "アックス",
      rank: "A",
      req: 20,
      acc: 0,
      hands: 2,
      might: 35,
      crit: 10,
      price: 1080,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "グレイヴ(振)",
      cls: "アックス",
      rank: "A",
      req: 28,
      acc: 0,
      hands: 2,
      might: 48,
      crit: 11,
      price: 1350,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "グレイヴ(突)",
      cls: "アックス",
      rank: "A",
      req: 28,
      acc: 0,
      hands: 2,
      might: 43,
      crit: 10,
      price: 1350,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "ジャベリン",
      cls: "スピア",
      rank: "B",
      req: 5,
      acc: -1,
      hands: 1,
      might: 10,
      crit: 9,
      price: 65,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "ショートスピア",
      cls: "スピア",
      rank: "B",
      req: 10,
      acc: -1,
      hands: 1,
      might: 15,
      crit: 9,
      price: 110,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "スピア",
      cls: "スピア",
      rank: "B",
      req: 15,
      acc: -1,
      hands: 1,
      might: 20,
      crit: 9,
      price: 170,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "スピア(両手)",
      cls: "スピア",
      rank: "B",
      req: 15,
      acc: 0,
      hands: 2,
      might: 25,
      crit: 10,
      price: 170,
      note: "",
      isMagic: false,
    },
    {
      name: "ロングスピア",
      cls: "スピア",
      rank: "B",
      req: 20,
      acc: -1,
      hands: 1,
      might: 25,
      crit: 9,
      price: 220,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ロングスピア(両手)",
      cls: "スピア",
      rank: "B",
      req: 20,
      acc: 0,
      hands: 2,
      might: 30,
      crit: 10,
      price: 220,
      note: "",
      isMagic: false,
    },
    {
      name: "ピラー",
      cls: "スピア",
      rank: "A",
      req: 8,
      acc: -1,
      hands: 1,
      might: 13,
      crit: 8,
      price: 880,
      note: "",
      isMagic: false,
    },
    {
      name: "トライデント",
      cls: "スピア",
      rank: "A",
      req: 12,
      acc: 0,
      hands: 1,
      might: 17,
      crit: 9,
      price: 460,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "アールシェピース",
      cls: "スピア",
      rank: "A",
      req: 15,
      acc: -1,
      hands: 1,
      might: 25,
      crit: 9,
      price: 480,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "アールシェピース(両手)",
      cls: "スピア",
      rank: "A",
      req: 15,
      acc: 0,
      hands: 2,
      might: 30,
      crit: 10,
      price: 480,
      note: "",
      isMagic: false,
    },
    {
      name: "パイク",
      cls: "スピア",
      rank: "A",
      req: 25,
      acc: -1,
      hands: 1,
      might: 35,
      crit: 9,
      price: 1750,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "パイク(両手)",
      cls: "スピア",
      rank: "A",
      req: 25,
      acc: 0,
      hands: 2,
      might: 45,
      crit: 9,
      price: 1750,
      note: "",
      isMagic: false,
    },
    {
      name: "マレット",
      cls: "メイス",
      rank: "B",
      req: 1,
      acc: 1,
      hands: 1,
      might: 6,
      crit: 12,
      price: 20,
      note: "投擲可",
      isMagic: false,
    },
    {
      name: "ライトメイス",
      cls: "メイス",
      rank: "B",
      req: 5,
      acc: 1,
      hands: 1,
      might: 10,
      crit: 12,
      price: 120,
      note: "",
      isMagic: false,
    },
    {
      name: "ヘビーマレット",
      cls: "メイス",
      rank: "B",
      req: 10,
      acc: 1,
      hands: 1,
      might: 15,
      crit: 12,
      price: 220,
      note: "",
      isMagic: false,
    },
    {
      name: "ヘビーメイス",
      cls: "メイス",
      rank: "B",
      req: 15,
      acc: 1,
      hands: 1,
      might: 20,
      crit: 12,
      price: 330,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ヘビーメイス(両手)",
      cls: "メイス",
      rank: "B",
      req: 15,
      acc: 1,
      hands: 2,
      might: 30,
      crit: 12,
      price: 330,
      note: "",
      isMagic: false,
    },
    {
      name: "モール",
      cls: "メイス",
      rank: "B",
      req: 20,
      acc: 1,
      hands: 2,
      might: 35,
      crit: 12,
      price: 440,
      note: "",
      isMagic: false,
    },
    {
      name: "オーガモール",
      cls: "メイス",
      rank: "B",
      req: 30,
      acc: 1,
      hands: 2,
      might: 45,
      crit: 12,
      price: 640,
      note: "",
      isMagic: false,
    },
    {
      name: "ビリオン",
      cls: "メイス",
      rank: "A",
      req: 7,
      acc: 1,
      hands: 1,
      might: 17,
      crit: 12,
      price: 460,
      note: "",
      isMagic: false,
    },
    {
      name: "スティールブロウ",
      cls: "メイス",
      rank: "A",
      req: 13,
      acc: 1,
      hands: 1,
      might: 23,
      crit: 12,
      price: 710,
      note: "",
      isMagic: false,
    },
    {
      name: "シェルブレイカー",
      cls: "メイス",
      rank: "A",
      req: 18,
      acc: 1,
      hands: 1,
      might: 28,
      crit: 12,
      price: 1080,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "シェルブレイカー(両手)",
      cls: "メイス",
      rank: "A",
      req: 18,
      acc: 1,
      hands: 2,
      might: 38,
      crit: 12,
      price: 1080,
      note: "",
      isMagic: false,
    },
    {
      name: "ポールメイス",
      cls: "メイス",
      rank: "A",
      req: 23,
      acc: 1,
      hands: 2,
      might: 43,
      crit: 12,
      price: 1220,
      note: "",
      isMagic: false,
    },
    {
      name: "メイジスタッフ",
      cls: "スタッフ",
      rank: "B",
      req: 1,
      acc: 1,
      hands: 2,
      might: 11,
      crit: 12,
      price: 110,
      note: "防護点+1",
      isMagic: false,
    },
    {
      name: "クォータースタッフ",
      cls: "スタッフ",
      rank: "B",
      req: 4,
      acc: 1,
      hands: 2,
      might: 14,
      crit: 12,
      price: 140,
      note: "防護点+1",
      isMagic: false,
    },
    {
      name: "マナスタッフ",
      cls: "スタッフ",
      rank: "A",
      req: 3,
      acc: 1,
      hands: 2,
      might: 13,
      crit: 12,
      price: 6800,
      note: "魔力+1、魔法の武器",
      isMagic: true,
    },
    {
      name: "リーチスタッフ",
      cls: "スタッフ",
      rank: "A",
      req: 5,
      acc: 1,
      hands: 2,
      might: 15,
      crit: 12,
      price: 7000,
      note: "魔法のダメージ+2",
      isMagic: true,
    },
    {
      name: "ライトフレイル",
      cls: "フレイル",
      rank: "B",
      req: 7,
      acc: -1,
      hands: 1,
      might: 12,
      crit: 9,
      price: 90,
      note: "",
      isMagic: false,
    },
    {
      name: "フレイル",
      cls: "フレイル",
      rank: "B",
      req: 10,
      acc: -1,
      hands: 1,
      might: 15,
      crit: 9,
      price: 240,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "フレイル(両手)",
      cls: "フレイル",
      rank: "B",
      req: 10,
      acc: -1,
      hands: 2,
      might: 25,
      crit: 9,
      price: 240,
      note: "",
      isMagic: false,
    },
    {
      name: "モーニングスター",
      cls: "フレイル",
      rank: "B",
      req: 12,
      acc: -1,
      hands: 1,
      might: 17,
      crit: 9,
      price: 280,
      note: "",
      isMagic: false,
    },
    {
      name: "ヘビーフレイル",
      cls: "フレイル",
      rank: "B",
      req: 15,
      acc: -1,
      hands: 1,
      might: 20,
      crit: 9,
      price: 340,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ヘビーフレイル(両手)",
      cls: "フレイル",
      rank: "B",
      req: 15,
      acc: -1,
      hands: 2,
      might: 30,
      crit: 9,
      price: 340,
      note: "",
      isMagic: false,
    },
    {
      name: "ライジングサン",
      cls: "フレイル",
      rank: "A",
      req: 14,
      acc: -1,
      hands: 1,
      might: 24,
      crit: 9,
      price: 1200,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ライジングサン(両手)",
      cls: "フレイル",
      rank: "A",
      req: 14,
      acc: -1,
      hands: 2,
      might: 34,
      crit: 9,
      price: 1200,
      note: "",
      isMagic: false,
    },
    {
      name: "ゴーデンダッグ",
      cls: "フレイル",
      rank: "A",
      req: 18,
      acc: -1,
      hands: 1,
      might: 28,
      crit: 9,
      price: 1540,
      note: "両手持ち可",
      isMagic: false,
    },
    {
      name: "ゴーデンダッグ(両手)",
      cls: "フレイル",
      rank: "A",
      req: 18,
      acc: -1,
      hands: 2,
      might: 38,
      crit: 9,
      price: 1540,
      note: "",
      isMagic: false,
    },
    {
      name: "スコーピオンテイル",
      cls: "フレイル",
      rank: "A",
      req: 27,
      acc: -1,
      hands: 2,
      might: 47,
      crit: 9,
      price: 2600,
      note: "",
      isMagic: false,
    },
    {
      name: "ピック",
      cls: "ウォーハンマー",
      rank: "B",
      req: 2,
      acc: -1,
      hands: 1,
      might: 7,
      crit: 9,
      price: 60,
      note: "",
      isMagic: false,
    },
    {
      name: "ウォーハンマー",
      cls: "ウォーハンマー",
      rank: "B",
      req: 11,
      acc: -1,
      hands: 1,
      might: 16,
      crit: 9,
      price: 250,
      note: "",
      isMagic: false,
    },
    {
      name: "マトック",
      cls: "ウォーハンマー",
      rank: "B",
      req: 20,
      acc: -2,
      hands: 2,
      might: 40,
      crit: 8,
      price: 440,
      note: "",
      isMagic: false,
    },
    {
      name: "ウォーピック",
      cls: "ウォーハンマー",
      rank: "A",
      req: 5,
      acc: -1,
      hands: 1,
      might: 15,
      crit: 9,
      price: 600,
      note: "",
      isMagic: false,
    },
    {
      name: "ベク・ド・コルバン(振)",
      cls: "ウォーハンマー",
      rank: "A",
      req: 20,
      acc: -1,
      hands: 2,
      might: 40,
      crit: 9,
      price: 1800,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "ベク・ド・コルバン(突)",
      cls: "ウォーハンマー",
      rank: "A",
      req: 20,
      acc: -2,
      hands: 2,
      might: 45,
      crit: 8,
      price: 1800,
      note: "ハルバード系",
      isMagic: false,
    },
    {
      name: "ギザルメー",
      cls: "ウォーハンマー",
      rank: "A",
      req: 25,
      acc: -2,
      hands: 2,
      might: 50,
      crit: 8,
      price: 1680,
      note: "",
      isMagic: false,
    },
    {
      name: "パンチ",
      cls: "格闘",
      rank: "B",
      req: 0,
      acc: 0,
      hands: 1,
      might: 0,
      crit: 12,
      price: 0,
      note: "武器無し",
      isMagic: false,
    },
    {
      name: "キック",
      cls: "格闘",
      rank: "B",
      req: 0,
      acc: -1,
      hands: 1,
      might: 5,
      crit: 9,
      price: 0,
      note: "武器無し",
      isMagic: false,
    },
    {
      name: "投げ",
      cls: "格闘",
      rank: "B",
      req: 0,
      acc: 0,
      hands: 2,
      might: 10,
      crit: 12,
      price: 0,
      note: "グラップラー専用",
      isMagic: false,
    },
    {
      name: "セスタス",
      cls: "格闘",
      rank: "B",
      req: 1,
      acc: 1,
      hands: 1,
      might: 1,
      crit: 11,
      price: 40,
      note: "パンチ強化",
      isMagic: false,
    },
    {
      name: "スパイクブーツ",
      cls: "格闘",
      rank: "B",
      req: 1,
      acc: -1,
      hands: 1,
      might: 11,
      crit: 9,
      price: 160,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "アイアンナックル",
      cls: "格闘",
      rank: "B",
      req: 5,
      acc: 1,
      hands: 1,
      might: 5,
      crit: 11,
      price: 100,
      note: "パンチ強化",
      isMagic: false,
    },
    {
      name: "ソリッドヒール",
      cls: "格闘",
      rank: "B",
      req: 5,
      acc: -1,
      hands: 1,
      might: 15,
      crit: 9,
      price: 240,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "アイアンボックス",
      cls: "格闘",
      rank: "B",
      req: 10,
      acc: 1,
      hands: 1,
      might: 10,
      crit: 11,
      price: 230,
      note: "パンチ強化",
      isMagic: false,
    },
    {
      name: "シンガード",
      cls: "格闘",
      rank: "B",
      req: 10,
      acc: -1,
      hands: 1,
      might: 20,
      crit: 9,
      price: 390,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "シンプレート",
      cls: "格闘",
      rank: "B",
      req: 15,
      acc: -1,
      hands: 1,
      might: 25,
      crit: 9,
      price: 580,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "ハードノッカー",
      cls: "格闘",
      rank: "A",
      req: 5,
      acc: 1,
      hands: 1,
      might: 10,
      crit: 11,
      price: 440,
      note: "パンチ強化",
      isMagic: false,
    },
    {
      name: "パワーリスト",
      cls: "格闘",
      rank: "A",
      req: 5,
      acc: 1,
      hands: 1,
      might: 10,
      crit: 10,
      price: 460,
      note: "パンチ強化",
      isMagic: false,
    },
    {
      name: "スタンパー",
      cls: "格闘",
      rank: "A",
      req: 5,
      acc: -1,
      hands: 1,
      might: 20,
      crit: 9,
      price: 520,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "チェインスティック",
      cls: "格闘",
      rank: "A",
      req: 10,
      acc: 1,
      hands: 1,
      might: 15,
      crit: 11,
      price: 630,
      note: "パンチ強化",
      isMagic: false,
    },
    {
      name: "パワーアンクル",
      cls: "格闘",
      rank: "A",
      req: 10,
      acc: -1,
      hands: 1,
      might: 20,
      crit: 10,
      price: 900,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "ハードキッカー",
      cls: "格闘",
      rank: "A",
      req: 15,
      acc: -1,
      hands: 1,
      might: 30,
      crit: 9,
      price: 1290,
      note: "キック強化",
      isMagic: false,
    },
    {
      name: "ストーン",
      cls: "投擲",
      rank: "B",
      req: 1,
      acc: 0,
      hands: 1,
      might: 1,
      crit: 12,
      price: 0,
      note: "射程10m",
      isMagic: false,
    },
    {
      name: "シルバーストーン",
      cls: "投擲",
      rank: "B",
      req: 1,
      acc: 0,
      hands: 1,
      might: 1,
      crit: 12,
      price: 1,
      note: "射程10m, 銀製",
      isMagic: false,
    },
    {
      name: "チャクラム",
      cls: "投擲",
      rank: "A",
      req: 1,
      acc: 0,
      hands: 1,
      might: 6,
      crit: 10,
      price: 100,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "スリング",
      cls: "投擲",
      rank: "A",
      req: 2,
      acc: 0,
      hands: 1,
      might: 12,
      crit: 11,
      price: 220,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ダーク",
      cls: "投擲",
      rank: "A",
      req: 4,
      acc: 0,
      hands: 1,
      might: 9,
      crit: 10,
      price: 100,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "ソリフェラム",
      cls: "投擲",
      rank: "A",
      req: 17,
      acc: 0,
      hands: 1,
      might: 27,
      crit: 9,
      price: 1070,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "ショートボウ",
      cls: "ボウ",
      rank: "B",
      req: 2,
      acc: 0,
      hands: 2,
      might: 12,
      crit: 10,
      price: 60,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "ノーマルボウ",
      cls: "ボウ",
      rank: "B",
      req: 7,
      acc: 0,
      hands: 2,
      might: 17,
      crit: 10,
      price: 120,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "ロングボウ",
      cls: "ボウ",
      rank: "B",
      req: 12,
      acc: 0,
      hands: 2,
      might: 22,
      crit: 10,
      price: 170,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "ヘビーボウ",
      cls: "ボウ",
      rank: "B",
      req: 17,
      acc: 0,
      hands: 2,
      might: 27,
      crit: 10,
      price: 220,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "ライトボウ",
      cls: "ボウ",
      rank: "A",
      req: 5,
      acc: 0,
      hands: 2,
      might: 20,
      crit: 10,
      price: 610,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ラップドボウ",
      cls: "ボウ",
      rank: "A",
      req: 13,
      acc: 0,
      hands: 2,
      might: 28,
      crit: 10,
      price: 780,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ファストボウ",
      cls: "ボウ",
      rank: "A",
      req: 20,
      acc: 0,
      hands: 2,
      might: 35,
      crit: 10,
      price: 1200,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ライトクロスボウ",
      cls: "クロスボウ",
      rank: "B",
      req: 1,
      acc: 0,
      hands: 2,
      might: 16,
      crit: 10,
      price: 160,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ノーマルクロスボウ",
      cls: "クロスボウ",
      rank: "B",
      req: 5,
      acc: 0,
      hands: 2,
      might: 20,
      crit: 10,
      price: 260,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ヘビークロスボウ",
      cls: "クロスボウ",
      rank: "B",
      req: 10,
      acc: 0,
      hands: 2,
      might: 25,
      crit: 10,
      price: 530,
      note: "射程30m",
      isMagic: false,
    },
    {
      name: "ボウガン",
      cls: "クロスボウ",
      rank: "A",
      req: 5,
      acc: 0,
      hands: 1,
      might: 15,
      crit: 10,
      price: 800,
      note: "射程20m",
      isMagic: false,
    },
    {
      name: "アーバレスト",
      cls: "クロスボウ",
      rank: "A",
      req: 10,
      acc: 0,
      hands: 2,
      might: 30,
      crit: 10,
      price: 1000,
      note: "射程40m",
      isMagic: false,
    },
    {
      name: "ティム",
      cls: "クロスボウ",
      rank: "A",
      req: 15,
      acc: 0,
      hands: 2,
      might: 35,
      crit: 10,
      price: 1280,
      note: "射程50m",
      isMagic: false,
    },
    {
      name: "クレインクィン",
      cls: "クロスボウ",
      rank: "A",
      req: 20,
      acc: 0,
      hands: 2,
      might: 50,
      crit: 9,
      price: 1500,
      note: "射程40m",
      isMagic: false,
    },
    {
      name: "サーペンタインガン",
      cls: "ガン",
      rank: "B",
      req: 1,
      acc: 0,
      hands: 1,
      might: 0,
      crit: 11,
      price: 360,
      note: "射程10m,装填数3",
      isMagic: false,
    },
    {
      name: "トラドール",
      cls: "ガン",
      rank: "B",
      req: 5,
      acc: 0,
      hands: 2,
      might: 0,
      crit: 10,
      price: 800,
      note: "射程30m,装填数3",
      isMagic: false,
    },
    {
      name: "ジェザイル",
      cls: "ガン",
      rank: "B",
      req: 10,
      acc: 0,
      hands: 2,
      might: 0,
      crit: 10,
      price: 1200,
      note: "射程50m,装填数3",
      isMagic: false,
    },
    {
      name: "デリンジャー",
      cls: "ガン",
      rank: "A",
      req: 1,
      acc: 1,
      hands: 1,
      might: 0,
      crit: 10,
      price: 600,
      note: "射程10m,装填数2,ダメージ+1",
      isMagic: false,
    },
    {
      name: "テンペスト",
      cls: "ガン",
      rank: "A",
      req: 10,
      acc: 0,
      hands: 2,
      might: 0,
      crit: 11,
      price: 2000,
      note: "射程30m,装填数6,ダメージ+1",
      isMagic: false,
    },
    {
      name: "ロングバレル",
      cls: "ガン",
      rank: "A",
      req: 15,
      acc: 1,
      hands: 2,
      might: 0,
      crit: 10,
      price: 3500,
      note: "射程50m,装填数1,ダメージ+2",
      isMagic: false,
    },
  ],
};
window.sw25_data.Armours = [
  // 非金属鎧
  {
    name: "クロースアーマー",
    cls: "非金属鎧",
    rank: "B",
    req: 1,
    eva: 0,
    def: 2,
    price: 15,
    note: "グラップラー装備可能",
    isMagic: false,
  },
  {
    name: "ポイントガード",
    cls: "非金属鎧",
    rank: "B",
    req: 1,
    eva: "+1",
    def: 0,
    price: 100,
    note: "グラップラー専用",
    isMagic: false,
  },
  {
    name: "ソフトレザー",
    cls: "非金属鎧",
    rank: "B",
    req: 7,
    eva: 0,
    def: 3,
    price: 150,
    note: "",
    isMagic: false,
  },
  {
    name: "ハードレザー",
    cls: "非金属鎧",
    rank: "B",
    req: 13,
    eva: 0,
    def: 4,
    price: 340,
    note: "",
    isMagic: false,
  },
  {
    name: "マナコート",
    cls: "非金属鎧",
    rank: "B",
    req: 1,
    eva: 0,
    def: 0,
    price: 28000,
    note: "装備者の知力ボーナスが防護点となる。上限6(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "マナコートプラス",
    cls: "非金属鎧",
    rank: "B",
    req: 1,
    eva: 0,
    def: 0,
    price: 52000,
    note: "装備者の知力ボーナスが防護点となる。上限8(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "ミモレの布鎧",
    cls: "非金属鎧",
    rank: "B",
    req: 2,
    eva: 0,
    def: 2,
    price: 6000,
    note: "グラップラー装備可能、両手に何も持っていないとき回避力判定+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "茨のローブ",
    cls: "非金属鎧",
    rank: "B",
    req: 2,
    eva: 0,
    def: 2,
    price: 40000,
    note: "近づくものに「2d」点の魔法ダメージ(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "コンバットメイド",
    cls: "非金属鎧",
    rank: "B",
    req: 10,
    eva: "+1",
    def: 0,
    price: 24000,
    note: "グラップラー装備可能、魔法ダメージ-3",
    isMagic: false,
  },
  {
    name: "バトラースーツ",
    cls: "非金属鎧",
    rank: "B",
    req: 10,
    eva: "+1",
    def: 0,
    price: 24000,
    note: "グラップラー装備可能、魔法ダメージ-3",
    isMagic: false,
  },
  {
    name: "アラミドコート",
    cls: "非金属鎧",
    rank: "A",
    req: 5,
    eva: "+1",
    def: 2,
    price: 750,
    note: "グラップラー装備可能",
    isMagic: false,
  },
  {
    name: "ブレストアーム",
    cls: "非金属鎧",
    rank: "A",
    req: 10,
    eva: 0,
    def: 5,
    price: 1000,
    note: "",
    isMagic: false,
  },
  {
    name: "ボーンベスト",
    cls: "非金属鎧",
    rank: "A",
    req: 16,
    eva: 0,
    def: 6,
    price: 2100,
    note: "",
    isMagic: false,
  },
  {
    name: "ミモレの上質布鎧",
    cls: "非金属鎧",
    rank: "A",
    req: 6,
    eva: "+1",
    def: 2,
    price: 12000,
    note: "グラップラー装備可能、両手に何も持っていないとき回避力判定+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "風切りのサーコート",
    cls: "非金属鎧",
    rank: "A",
    req: 12,
    eva: "+1",
    def: 3,
    price: 10500,
    note: "風属性の攻撃や効果を1日に1回だけ自動回避する(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "ファインレザー",
    cls: "非金属鎧",
    rank: "S",
    req: 6,
    eva: "+1",
    def: 4,
    price: 2440,
    note: "",
    isMagic: false,
  },
  {
    name: "リュンクスベスト",
    cls: "非金属鎧",
    rank: "S",
    req: 8,
    eva: "+2",
    def: 3,
    price: 2750,
    note: "グラップラー専用",
    isMagic: false,
  },
  {
    name: "タイガーバンド",
    cls: "非金属鎧",
    rank: "S",
    req: 10,
    eva: "+1",
    def: 5,
    price: 3600,
    note: "",
    isMagic: false,
  },
  {
    name: "ドラゴンスケイル",
    cls: "非金属鎧",
    rank: "S",
    req: 14,
    eva: "+1",
    def: 6,
    price: 4500,
    note: "",
    isMagic: false,
  },
  {
    name: "ミモレの極上布鎧",
    cls: "非金属鎧",
    rank: "S",
    req: 6,
    eva: "+2",
    def: 2,
    price: 24000,
    note: "グラップラー装備可能、両手に何も持っていないとき回避力判定+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "アストラルガード",
    cls: "非金属鎧",
    rank: "SS",
    req: 6,
    eva: "+1",
    def: 7,
    price: 34000,
    note: "魔法ダメージ-3",
    isMagic: false,
  },
  {
    name: "サイレントクローク",
    cls: "非金属鎧",
    rank: "SS",
    req: 11,
    eva: "+1",
    def: 8,
    price: 38000,
    note: "隠密判定+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "アラバスタシェル",
    cls: "非金属鎧",
    rank: "SS",
    req: 14,
    eva: "+1",
    def: 9,
    price: 41000,
    note: "",
    isMagic: false,
  },
  {
    name: "フェニックスクローク",
    cls: "非金属鎧",
    rank: "SS",
    req: 17,
    eva: "+2",
    def: 8,
    price: 45000,
    note: "グラップラー専用",
    isMagic: false,
  },
  {
    name: "ディバインスキン",
    cls: "非金属鎧",
    rank: "SS",
    req: 18,
    eva: "+1",
    def: 10,
    price: 52000,
    note: "精神抵抗力判定+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },

  // 金属鎧
  {
    name: "スプリントアーマー",
    cls: "金属鎧",
    rank: "B",
    req: 15,
    eva: 0,
    def: 5,
    price: 520,
    note: "",
    isMagic: false,
  },
  {
    name: "チェインメイル",
    cls: "金属鎧",
    rank: "B",
    req: 18,
    eva: "-1",
    def: 6,
    price: 760,
    note: "",
    isMagic: false,
  },
  {
    name: "プレートアーマー",
    cls: "金属鎧",
    rank: "B",
    req: 21,
    eva: "-2",
    def: 7,
    price: 1200,
    note: "",
    isMagic: false,
  },
  {
    name: "スーパーアーマー",
    cls: "金属鎧",
    rank: "B",
    req: 24,
    eva: "-3",
    def: 8,
    price: 2500,
    note: "全力移動不可、着用度6",
    isMagic: false,
  },
  {
    name: "バルザーの魔王鎧",
    cls: "金属鎧",
    rank: "B",
    req: 16,
    eva: 0,
    def: 6,
    price: 8000,
    note: "(魔封剣)の命中でマナを蓄え、解放時に1体のHPを回復(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "ドントレシアの堅忍鎧",
    cls: "金属鎧",
    rank: "B",
    req: 20,
    eva: 0,
    def: 6,
    price: 12700,
    note: "物理ダメージを受けるたび防護点+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "スティールガード",
    cls: "金属鎧",
    rank: "A",
    req: 12,
    eva: 0,
    def: 5,
    price: 1600,
    note: "",
    isMagic: false,
  },
  {
    name: "ラメラーアーマー",
    cls: "金属鎧",
    rank: "A",
    req: 15,
    eva: 0,
    def: 6,
    price: 2400,
    note: "",
    isMagic: false,
  },
  {
    name: "ブリガンティ",
    cls: "金属鎧",
    rank: "A",
    req: 18,
    eva: "-1",
    def: 7,
    price: 3800,
    note: "",
    isMagic: false,
  },
  {
    name: "コート・オブ・プレート",
    cls: "金属鎧",
    rank: "A",
    req: 24,
    eva: "-2",
    def: 8,
    price: 6100,
    note: "",
    isMagic: false,
  },
  {
    name: "フォートレス",
    cls: "金属鎧",
    rank: "A",
    req: 27,
    eva: "-3",
    def: 9,
    price: 8200,
    note: "",
    isMagic: false,
  },
  {
    name: "ドントレシアの堅忍大鎧",
    cls: "金属鎧",
    rank: "A",
    req: 21,
    eva: 0,
    def: 8,
    price: 26400,
    note: "物理ダメージを受けるたび防護点+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "ミスリルチェイン",
    cls: "金属鎧",
    rank: "S",
    req: 10,
    eva: 0,
    def: 7,
    price: 6000,
    note: "銀製",
    isMagic: false,
  },
  {
    name: "フルメタルアーマー",
    cls: "金属鎧",
    rank: "S",
    req: 17,
    eva: "-1",
    def: 9,
    price: 11000,
    note: "",
    isMagic: false,
  },
  {
    name: "ミスリルプレート",
    cls: "金属鎧",
    rank: "S",
    req: 24,
    eva: "-2",
    def: 11,
    price: 23000,
    note: "銀製",
    isMagic: false,
  },
  {
    name: "パワァードプレーツ",
    cls: "金属鎧",
    rank: "S",
    req: 14,
    eva: 0,
    def: 8,
    price: 28000,
    note: "MP3点を消費することで回避力判定を事後に+1(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "ドントレシアの堅忍甲冑",
    cls: "金属鎧",
    rank: "S",
    req: 22,
    eva: 0,
    def: 10,
    price: 54800,
    note: "物理ダメージを受けるたび防護点+2(詳細⇒Ⅰ123頁)",
    isMagic: false,
  },
  {
    name: "マナタイトフレーム",
    cls: "金属鎧",
    rank: "SS",
    req: 18,
    eva: 0,
    def: 11,
    price: 62000,
    note: "",
    isMagic: false,
  },
  {
    name: "アンチアーク・バス",
    cls: "金属鎧",
    rank: "SS",
    req: 23,
    eva: 0,
    def: 12,
    price: 79000,
    note: "(ガン)によるダメージを-5(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "インペリアル",
    cls: "金属鎧",
    rank: "SS",
    req: 30,
    eva: "-1",
    def: 14,
    price: 100000,
    note: "魔法ダメージ-3",
    isMagic: false,
  },

  // 盾
  {
    name: "バックラー",
    cls: "盾",
    rank: "B",
    req: 1,
    eva: "+1",
    def: 0,
    price: 60,
    note: "",
    isMagic: false,
  },
  {
    name: "グラスのバックラー",
    cls: "盾",
    rank: "B",
    req: 1,
    eva: "+1",
    def: 0,
    price: 1060,
    note: "命中力+1、回避失敗で機能喪失、破壊(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "ラウンドシールド",
    cls: "盾",
    rank: "B",
    req: 8,
    eva: 0,
    def: 1,
    price: 100,
    note: "",
    isMagic: false,
  },
  {
    name: "カイトシールド",
    cls: "盾",
    rank: "B",
    req: 13,
    eva: "+1",
    def: 1,
    price: 500,
    note: "",
    isMagic: false,
  },
  {
    name: "タワーシールド",
    cls: "盾",
    rank: "B",
    req: 17,
    eva: 0,
    def: 2,
    price: 600,
    note: "",
    isMagic: false,
  },
  {
    name: "アステリアの守り",
    cls: "盾",
    rank: "B",
    req: 6,
    eva: 0,
    def: 2,
    price: 40000,
    note: "属性(土・水・氷・風)ダメージを-3(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "炎の盾",
    cls: "盾",
    rank: "B",
    req: 13,
    eva: "+1",
    def: 1,
    price: 7900,
    note: "合言葉によって炎を纏い、防具を強化する(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "カルヴァリア",
    cls: "盾",
    rank: "B",
    req: 14,
    eva: 0,
    def: 3,
    price: 67000,
    note: "盾形態と盾形態を切り替えられる(詳細⇒Ⅰ120頁)",
    isMagic: false,
  },
  {
    name: "バルザーの魔光盾",
    cls: "盾",
    rank: "B",
    req: 16,
    eva: 0,
    def: 2,
    price: 6000,
    note: "(魔剣針)の命中でマナを蓄え、解放時に1体のダメージ(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "ブリットルマイティ",
    cls: "盾",
    rank: "B",
    req: 20,
    eva: "-2",
    def: 4,
    price: 3000,
    note: "回避力判定の自動失敗でキャラクターの防護点0(詳細⇒Ⅰ124頁)",
    isMagic: false,
  },
  {
    name: "ミラーシールド",
    cls: "盾",
    rank: "A",
    req: 5,
    eva: "+1",
    def: 0,
    price: 870,
    note: "鏡として使用できる(詳細⇒Ⅰ125頁)",
    isMagic: false,
  },
  {
    name: "ターゲットシールド",
    cls: "盾",
    rank: "A",
    req: 7,
    eva: "+1",
    def: 1,
    price: 680,
    note: "",
    isMagic: false,
  },
  {
    name: "シンバルシールド",
    cls: "盾",
    rank: "A",
    req: 8,
    eva: "+1",
    def: 1,
    price: 1020,
    note: "盾として使用時に「楽素:奏」を生成(詳細⇒Ⅰ129頁)",
    isMagic: false,
  },
  {
    name: "ヒーターシールド",
    cls: "盾",
    rank: "A",
    req: 10,
    eva: 0,
    def: 2,
    price: 1000,
    note: "",
    isMagic: false,
  },
  {
    name: "スパイクシールド",
    cls: "盾",
    rank: "A",
    req: 13,
    eva: "+1",
    def: "2/0",
    price: 1800,
    note: "武器として使用可能(詳細⇒Ⅰ125頁)",
    isMagic: false,
  },
  {
    name: "ナイトシールド",
    cls: "盾",
    rank: "A",
    req: 15,
    eva: 0,
    def: 3,
    price: 1800,
    note: "鞘嵌防護",
    isMagic: false,
  },
  {
    name: "グレートウォール",
    cls: "盾",
    rank: "A",
    req: 20,
    eva: "-1",
    def: 3,
    price: 3300,
    note: "",
    isMagic: false,
  },
  {
    name: "グレートパリィ",
    cls: "盾",
    rank: "A",
    req: 30,
    eva: "+1",
    def: 3,
    price: 7000,
    note: "武器として使用可能",
    isMagic: false,
  },
  {
    name: "ティムスガルドのライトドック",
    cls: "盾",
    rank: "A",
    req: 10,
    eva: 0,
    def: 2,
    price: 4200,
    note: "(ティムスガルドのチェイン**)と連結し、使い勝手を劇的に向上させる(詳細⇒Ⅰ125頁)",
    isMagic: false,
  },
  {
    name: "リフレクターシールド",
    cls: "盾",
    rank: "A",
    req: 16,
    eva: "+1",
    def: 2,
    price: 8000,
    note: "「形状:貫通」を跳ね返す(詳細⇒Ⅰ125頁)",
    isMagic: false,
  },
  {
    name: "ティムスガルドのヘビードック",
    cls: "盾",
    rank: "A",
    req: 20,
    eva: "-1",
    def: 3,
    price: 4200,
    note: "(ティムスガルドのチェイン**)と連結し、使い勝手を劇的に向上させる(詳細⇒Ⅰ125頁)",
    isMagic: false,
  },
  {
    name: "ミスリルシールド",
    cls: "盾",
    rank: "S",
    req: 8,
    eva: "+1",
    def: 2,
    price: 4700,
    note: "銀製",
    isMagic: false,
  },
  {
    name: "ホプライトシールド",
    cls: "盾",
    rank: "S",
    req: 15,
    eva: 0,
    def: 4,
    price: 2900,
    note: "",
    isMagic: false,
  },
  {
    name: "グランドパートナー",
    cls: "盾",
    rank: "S",
    req: 18,
    eva: 0,
    def: 3,
    price: 4800,
    note: "鞘嵌防護",
    isMagic: false,
  },
  {
    name: "ブレードキラー",
    cls: "盾",
    rank: "S",
    req: 22,
    eva: 0,
    def: "4/2",
    price: 7200,
    note: "武器として使用可能",
    isMagic: false,
  },
  {
    name: "タートルシェル",
    cls: "盾",
    rank: "S",
    req: 5,
    eva: "+2",
    def: 1,
    price: 19200,
    note: "",
    isMagic: false,
  },
  {
    name: "トータルリフレクター",
    cls: "盾",
    rank: "S",
    req: 16,
    eva: "+1",
    def: 3,
    price: 28800,
    note: "「形状:射撃,貫通」を跳ね返す(詳細⇒Ⅰ125頁)",
    isMagic: false,
  },
  {
    name: "ハーフムーン",
    cls: "盾",
    rank: "SS",
    req: 6,
    eva: "+2",
    def: 2,
    price: 33000,
    note: "",
    isMagic: false,
  },
  {
    name: "グロリアス",
    cls: "盾",
    rank: "SS",
    req: 15,
    eva: "+1",
    def: 5,
    price: 47000,
    note: "",
    isMagic: false,
  },
  {
    name: "パラディンズプライド",
    cls: "盾",
    rank: "SS",
    req: 21,
    eva: 0,
    def: 6,
    price: 54000,
    note: "鞘嵌防護",
    isMagic: false,
  },
  {
    name: "エターナルロード",
    cls: "盾",
    rank: "SS",
    req: 24,
    eva: 0,
    def: 7,
    price: 65000,
    note: "",
    isMagic: false,
  },
];
// このコードで sw25_data.js の Items オブジェクト全体を置き換えてください

window.sw25_data.Items = {
  冒険者技能用アイテム: [
    {
      name: "〈魔法の発動体〉",
      price: 100,
      note: "真語魔法、操霊魔法の行使に使用",
      isMagic: false,
    },
    {
      name: "〈我慢比べのワンド〉",
      price: 700,
      note: "自身と対象に「1」点の呪いダメージ(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    {
      name: "〈計測のワンド〉",
      price: 4200,
      note: "「形状：貫通」の魔法を任意の起点と終点で行使できる(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    {
      name: "〈ミニマムアーマー〉",
      price: 2120,
      note: "使い魔の防護点を+3/+6(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    {
      name: "〈魔化された＊＊〉",
      price: 50,
      note: "さまざまなゴーレム素材(109頁も参照)",
      isMagic: false,
    },
    {
      name: "〈強く魔化された＊＊〉",
      price: 100,
      note: "再利用可能なさまざまなゴーレム素材(109頁も参照)",
      isMagic: false,
    },
    {
      name: "〈ゴーレム強化アイテム〉",
      price: 100,
      note: "ゴーレムの強化に使用するさまざまなアイテム(109頁も参照)",
      isMagic: false,
    },
    {
      name: "〈魔力を帯びた骨〉",
      price: 500,
      note: "スケルトン系アンデッドの素材",
      isMagic: false,
    },
    {
      name: "〈呼応石〉",
      price: 100,
      note: "ゴーレムやアンデッドへの命令を変更できる(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    { name: "〈聖印〉", price: 100, note: "神聖魔法の行使に使用" },
    {
      name: "〈携帯神殿〉",
      price: 9120,
      note: "特殊神聖魔法を1日1回だけMP0で使える。また、特定地方でのMP上昇(⇒『Ⅱ』109頁)を抑制(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    {
      name: "〈浄化の聖印〉",
      price: 13800,
      note: "異大陸・地方でのMP上昇(⇒『Ⅱ』109頁)を抑制する(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    { name: "〈妖精使いの宝石〉", price: 50, note: "妖精魔法の行使に使用" },
    {
      name: "〈宝石ケース〉",
      price: 100,
      note: "〈妖精使いの宝石〉を4つまで収められる。宝石は別売り",
      isMagic: false,
    },
    {
      name: "〈華美なる宝石飾り〉",
      price: 200,
      honor: 20,
      note: "〈妖精使いの宝石〉6つを使って使える。宝石は別売り。フェアリーテイマー技能3レベル",
      isMagic: false,
    },
    {
      name: "〈フェアリードロップ〉",
      price: 1000,
      note: "【サモン・フェアリー】における〈魔晶石〉を代替する(詳細⇒Ⅰ128頁)",
      isMagic: false,
    },
    { name: "〈マギスフィア(小)〉", price: 200, note: "魔動機術の行使に使用" },
    { name: "〈マギスフィア(中)〉", price: 500, note: "魔動機術の行使に使用" },
    { name: "〈マギスフィア(大)〉", price: 1000, note: "魔動機術の行使に使用" },
    {
      name: "魔晶石(1～5点)",
      price: 100,
      note: "MP消費を肩代わりできる。価格は点数x100",
      isMagic: false,
    },
    {
      name: "魔晶石(6～10点)",
      price: 200,
      note: "MP消費を肩代わりできる。価格は点数x200",
      isMagic: false,
    },
    {
      name: "魔晶石(11～15点)",
      price: 300,
      note: "MP消費を肩代わりできる。価格は点数x300",
      isMagic: false,
    },
    {
      name: "魔晶石(16～20点)",
      price: 400,
      note: "MP消費を肩代わりできる。価格は点数x400",
      isMagic: false,
    },
    {
      name: "マナチャージクリスタル(1～5点)",
      price: 500,
      note: "MPを自動で再充填する(魔晶石)(詳細⇒Ⅰ128頁)。価格は点数x500",
      isMagic: false,
    },
    { name: "〈矢筒〉", price: 20, note: "矢、矢来を合計12本まで収納 ※1" },
    {
      name: "〈補充の矢筒〉",
      price: 600,
      note: "MP消費で自動補充される矢筒(詳細⇒Ⅰ128頁) ※1",
      isMagic: false,
    },
    {
      name: "〈えびら〉",
      price: 100,
      note: "矢、矢来を合計24本まで収納。要〈武器習熟A/ボウ〉または〈武器習熟A/クロスボウ〉 ※1",
      isMagic: false,
    },
    { name: "〈ガンベルト〉", price: 20, note: "弾丸を合計12発まで収納 ※1" },
    {
      name: "〈バレットスリンガー〉",
      price: 40,
      note: "弾丸を合計12発まで収納 ※1",
      isMagic: false,
    },
    {
      name: "〈バレットポーチ〉",
      price: 100,
      note: "弾丸を合計24本まで収納。要〈武器習熟A/ガン〉 ※1",
      isMagic: false,
    },
    {
      name: "〈スカウト用ツール〉",
      price: 100,
      note: "合い鍵や針金などの工具セット。所持していないと解除判定の達成値に-4のペナルティ修正",
      isMagic: false,
    },
    {
      name: "〈精密ツールセット〉",
      price: 2500,
      note: "スカウト技巧判定に+1の(スカウト用ツール)、自動失敗時破損(詳細⇒Ⅰ128頁)",
      isMagic: false,
    },
    {
      name: "〈機械仕掛けの指〉",
      price: 7080,
      note: "MP2点使用で、解除判定に+2。(スカウト用ツール)を兼ねる(詳細⇒Ⅰ128頁)",
      isMagic: false,
    },
    {
      name: "〈アンロックキー〉",
      price: 100,
      note: "魔法で閉じられた鍵や扉に対して解除判定を試みられる。成功したら失われる。(詳細⇒Ⅰ128頁)",
      isMagic: false,
    },
    {
      name: "〈薬師道具セット〉",
      price: 200,
      note: "薬草での回復が安定(威力表を1d+4で参照)する(詳細⇒Ⅰ128頁)",
      isMagic: false,
    },
    {
      name: "〈魔香のパイプ〉",
      price: 1360,
      note: "自身の薬草による回復量を+1(詳細⇒Ⅰ128頁)",
      isMagic: false,
    },
    { name: "〈楽器〉", price: 100, note: "呪歌を奏でるために使用" },
    { name: "〈明音のフルート〉", price: 200, note: "巧奏値を-1(詳細⇒Ⅰ128頁)" },
    { name: "〈ペット〉", price: 100, note: "呪歌を歌わせられるペット" },
    {
      name: "〈尊い騎手の像〉",
      price: 1000,
      honor: 50,
      note: "レンタル騎獣の返却を1回猶予してもらえる(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈真に尊い騎手の像〉",
      price: 3000,
      honor: 200,
      note: "レンタル騎獣の返却を1回猶予してもらえる(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    { name: "〈アルケミーキット〉", price: 200, note: "賦術を使用できる" },
    {
      name: "〈カードシューター〉",
      price: 1500,
      note: "射程距離を延長して賦術を使用できる(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈マテリアルカード〉",
      price: 20,
      note: "賦術で消費する。価格は20～20000G",
      isMagic: false,
    },
  ],
  一般装備品: [
    {
      name: "〈冒険者セット〉",
      price: 100,
      note: "背負い袋、水袋、毛布、たいまつ6本、火口箱、ロープ10m、ナイフ",
      isMagic: false,
    },
    { name: "〈着替えセット〉", price: 10, note: "一週間分の着替え" },
    { name: "〈下着〉", price: 3, note: "シャツと、スカート、ズボン" },
    { name: "〈水着〉", price: 20, note: "濡れても透けにくい布でできた着衣" },
    {
      name: "〈防水着〉",
      price: 20,
      note: "水中活動時の達成値に+1のボーナス修正",
      isMagic: false,
    },
    {
      name: "〈ふかふかの防寒着〉",
      price: 80,
      note: "氷・水属性のダメージを「-1」点する。被ダメージ-6",
      isMagic: false,
    },
    { name: "〈礼装(男女)〉", price: 100, note: "上下セット価格" },
    {
      name: "〈礼装(ドレス)〉",
      price: 100,
      note: "誘惑判定の達成値に+1のボーナス修正",
      isMagic: false,
    },
    {
      name: "〈仕立てのいい服〉",
      price: 18000,
      note: "あらゆる服に変わる(詳細⇒Ⅰ125頁)",
      isMagic: false,
    },
    { name: "〈ベルトポーチ〉", price: 15, note: "布製" },
    { name: "〈水袋〉", price: 20, note: "革製" },
    { name: "〈背負い袋〉", price: 50, note: "革製" },
    { name: "〈食器セット〉", price: 12, note: "コップ、皿、おわん" },
    {
      name: "〈調理用具セット〉",
      price: 20,
      note: "フライパン、お鍋、クッキングスプーン",
      isMagic: false,
    },
    {
      name: "〈携帯しやすい調理道具セット〉",
      price: 50,
      note: "調理をするときの行為判定の達成値に+1のボーナス修正",
      isMagic: false,
    },
    { name: "〈テント〉", price: 250, note: "4人用250G～、5人用350G～" },
    {
      name: "〈たいまつ〉",
      price: 5,
      note: "6本セット。1本につき2時間もつ。落としても消えない",
      isMagic: false,
    },
    {
      name: "〈火口箱〉",
      price: 20,
      note: "火打ち石と火口の入った箱。10分で着火",
      isMagic: false,
    },
    { name: "〈燃えやすい火口箱〉", price: 20, note: "5分で着火する火口箱" },
    { name: "〈油〉", price: 20, note: "ランタン1瓶。1本で12時間分" },
    {
      name: "〈ランタン〉",
      price: 100,
      note: "耐風性の高い火打ち石の入った小さな器。1分で着火。",
      isMagic: false,
    },
    {
      name: "〈詰替え式のランタン〉",
      price: 100,
      note: "シャッター式で明かりを絞れる。落とすと消える",
      isMagic: false,
    },
    {
      name: "〈頑丈なランタン〉",
      price: 40,
      note: "3mの高さから石畳に落としても壊れないほど頑丈なランタン",
      isMagic: false,
    },
    { name: "〈ロープ〉", price: 10, note: "10m分。追加価格は1mあたり1G" },
    { name: "〈小型ハンマー〉", price: 10, note: "武器としては使えない" },
    {
      name: "〈バランスのよい小型ハンマー〉",
      price: 10,
      note: "いざとなったら武器（メイス／投擲）として使えるハンマー",
      isMagic: false,
    },
    { name: "〈フック〉", price: 10, note: "" },
    { name: "〈小型刃〉", price: 20, note: "10本セット。1つにつき1G" },
    {
      name: "〈よく切れるナイフ〉",
      price: 20,
      note: "いざとなったら武器（ソード／投擲）Bランクの武器（ナイフ）に同じとして使える小型ナイフ",
      isMagic: false,
    },
    {
      name: "〈手鏡〉",
      price: 50,
      note: "Sサイズ50～, Mサイズ100～, Lサイズ150～",
      isMagic: false,
    },
    {
      name: "〈真っ平らの手鏡〉",
      price: 50,
      note: "〈I-105頁〉の装備に+1のボーナス修正",
      isMagic: false,
    },
    { name: "〈羽根ペン〉", price: 2, note: "50回+10G*ランク回執筆可能" },
    {
      name: "〈鋭い羽根ペン〉",
      price: 50,
      note: "執筆速度が+10%される羽根ペン",
      isMagic: false,
    },
    { name: "〈インク〉", price: 5, note: "" },
    {
      name: "〈銘筆〉",
      price: 50,
      note: "絵画を描くときの行為判定の達成値に+1のボーナス修正",
      isMagic: false,
    },
    { name: "〈綺麗な絵筆〉", price: 10, note: "" },
    { name: "〈油絵の具〉", price: 10, note: "7色セット" },
    { name: "〈はけ〉", price: 5, note: "" },
    { name: "〈カンバス〉", price: 20, note: "1枚" },
    { name: "〈墨〉", price: 4, note: "ハンカチサイズ4~, 風呂敷サイズ10~" },
    { name: "〈羊皮紙〉", price: 5, note: "5枚1束セット" },
    { name: "〈白紙の本〉", price: 30, note: "20枚ふん" },
    { name: "〈スケッチブック〉", price: 50, note: "50枚ぶん" },
    {
      name: "〈ぬいぐるみ〉",
      price: 30,
      note: "Sサイズ30~, Mサイズ50~, Lサイズ70~",
      isMagic: false,
    },
    { name: "〈はさみ〉", price: 30, note: "" },
    { name: "〈虫眼鏡〉", price: 100, note: "" },
    { name: "〈砂時計〉", price: 120, note: "3分を計れる" },
    { name: "〈ティーセット〉", price: 60, note: "ポット、茶漉し、カップ4つ" },
    { name: "〈化粧品セット〉", price: 100, note: "" },
  ],
  生活と移動: [
    {
      name: "〈自宅住まいで自炊〉",
      price: 10,
      note: "質素な暮らし10～, そこそこな暮らし30～",
      isMagic: false,
    },
    {
      name: "〈宿泊まり(1日)〉",
      price: 15,
      note: "馬小屋の宿15～, スタンダード30～, スイート100～",
      isMagic: false,
    },
    {
      name: "〈素泊まり(1週間)〉",
      price: 150,
      note: "食費別。前払い制。スタンダードのみで150～",
      isMagic: false,
    },
    { name: "食事(エール)", price: 1, note: "1杯の値段。1樽300～" },
    { name: "食事(ワイン)", price: 2, note: "1杯の値段。1瓶20～" },
    { name: "食事(蒸留酒)", price: 3, note: "1杯の値段。1瓶30～" },
    {
      name: "食事(1食分)",
      price: 3,
      note: "軽食3～, ランチセット8～, ディナー15～",
      isMagic: false,
    },
    {
      name: "〈保存食(1日分)〉",
      price: 10,
      note: "干し肉、ドライフルーツなど",
      isMagic: false,
    },
    { name: "〈保存食(1週間分)〉", price: 50, note: "お得用" },
    {
      name: "〈栄養カプセル〉",
      price: 100,
      note: "ルーンフォーク専用。1粒で1週間食事不要",
      isMagic: false,
    },
    {
      name: "〈刻み煙草〉",
      price: 10,
      note: "パイプや煙管に詰めて使う煙草。10回ぶん",
      isMagic: false,
    },
    { name: "〈巻き煙草〉", price: 24, note: "12本入り。" },
    { name: "〈パイプ〉/〈煙管〉", price: 10, note: "" },
    {
      name: "〈鉄煙管〉",
      price: 225,
      note: "いざとなったら武器（メイス／投擲）Bランク武器（マレット）に同じとして使える頑丈な鉄の煙管",
      isMagic: false,
    },
    { name: "〈ロバ〉", price: 800, note: "" },
    { name: "〈ラクダ〉", price: 1000, note: "" },
    { name: "〈馬〉", price: 1200, note: "" },
    { name: "〈ラウダ〉", price: 2000, note: "" },
    {
      name: "〈乗合馬車運賃〉",
      price: 10,
      note: "1時間で到着する程度の距離。長距離の乗合、時間あたりで+5G",
      isMagic: false,
    },
    {
      name: "〈魔動列車運賃〉",
      price: 20,
      note: "馬車の半分の時間で同程度の距離の行程。距離が伸びれば比例して増額。一等50～",
      isMagic: false,
    },
    { name: "〈飛空船運賃〉", price: 500, note: "旅程1日あたり。運賃のみ" },
    {
      name: "〈荷馬車チャーター〉",
      price: 500,
      note: "御者込みで1日あたり。旅程1人。その乗り物1台も2週間。2人乗り750。4人乗り1000。まとめて払うと合計金額の5%を割引",
      isMagic: false,
    },
    {
      name: "〈小型飛空船チャーター〉",
      price: 20000,
      note: "クルー1チームが操船（飛空船のみorセレスティアクルー）のクルーの費用すべて込みで1日あたり",
      isMagic: false,
    },
  ],
  薬品と修理具: [
    { name: "〈薬草〉", price: 10, note: "" },
    { name: "〈救命草〉", price: 30, note: "HPを回復「威力50」" },
    { name: "〈魔香草〉", price: 100, note: "MPを回復「威力50」" },
    { name: "〈魔療草〉", price: 250, note: "MPを回復「威力10」" },
    { name: "ヒーリングポーション", price: 100, note: "HPを回復「威力20」" },
    {
      name: "ヒーリングポーション+1",
      price: 200,
      note: "HPを回復「威力20+1」詳細⇒Ⅰ125頁",
      isMagic: false,
    },
    { name: "トリートポーション+1", price: 500, note: "HPを回復「威力30」" },
    {
      name: "アウェイクポーション",
      price: 100,
      note: "神聖魔法「アウェイクン」に同じ効果を得る。振りかけて使用可",
      isMagic: false,
    },
    {
      name: "アンチドーテポーション(Ⅰ)",
      price: 100,
      note: "Ⅰの毒属性の効果をすべて消滅させる",
      isMagic: false,
    },
    {
      name: "アンチドーテポーション(Ⅱ)",
      price: 2000,
      note: "達成値25以下の毒属性の効果をすべて消滅させる",
      isMagic: false,
    },
    {
      name: "キュアストーンポーション(Ⅰ)",
      price: 500,
      note: "達成値15以下の石化、石化進行の効果を消滅させる。振りかけて使用可",
      isMagic: false,
    },
    {
      name: "キュアストーンポーション(Ⅱ)",
      price: 10000,
      note: "達成値25以下の石化、石化進行の効果を消滅させる。振りかけて使用可",
      isMagic: false,
    },
    {
      name: "スカウトポーション",
      price: 1400,
      note: "探索判定に+1のボーナス修正",
      isMagic: false,
    },
    {
      name: "マッスルポーション",
      price: 2000,
      note: "6ラウンドの間、頑強の効果を得る",
      isMagic: false,
    },
    {
      name: "スピードポーション",
      price: 2000,
      note: "6ラウンドの間、移動力が+5される",
      isMagic: false,
    },
    {
      name: "マナマッジポーション",
      price: 3000,
      note: "6ラウンドの間、受ける魔法ダメージがすべて「-3」点される",
      isMagic: false,
    },
    {
      name: "夢見の薬",
      price: 3000,
      note: "一定時間の間、MPを回復(詳細⇒Ⅰ126頁)",
      isMagic: false,
    },
    {
      name: "気付け薬",
      price: 20,
      note: "対象への応急手当て判定を「時間：一瞬」で行い、ボーナス+2(詳細⇒Ⅰ126頁)",
      isMagic: false,
    },
    {
      name: "武器の磨き粉",
      price: 220,
      note: "「威力」によるHPへのダメージを+2(詳細⇒Ⅰ126頁)",
      isMagic: false,
    },
    {
      name: "七色のパテ",
      price: 240,
      note: "3時間、防具の装飾品化+1(詳細⇒Ⅰ126頁)",
      isMagic: false,
    },
    {
      name: "能力タビットにんじん",
      price: 1600,
      note: "気絶なし＆魔力を行使できる。魔力を行使すると1d+3で行える。タビット専用(詳細⇒Ⅰ127頁)",
      isMagic: false,
    },
    {
      name: "リペアテープ(Ⅰ)",
      price: 200,
      note: "「魔動機」のHPを回復「威力10」",
      isMagic: false,
    },
    {
      name: "リペアテープ(Ⅱ)",
      price: 750,
      note: "「魔動機」のHPを回復「威力20」",
      isMagic: false,
    },
    {
      name: "リペアテープ(Ⅲ)",
      price: 1000,
      note: "「魔動機」のHPを回復「威力30」",
      isMagic: false,
    },
    {
      name: "ポーションボール",
      price: 20,
      note: "ポーションを投擲で使用できる。戦闘特技《スローイングⅠ》",
      isMagic: false,
    },
    { name: "酒(10倍)", price: 100, note: "水で薄くなった酒を元に戻す" },
    { name: "ジャックの豆", price: 100, note: "" },
    {
      name: "ガラス玉",
      price: 100,
      note: "タヌキの大釜で使わせる。発見に対抗する隠密判定に+1",
      isMagic: false,
    },
    {
      name: "接着剤",
      price: 160,
      note: "金属鎧の接合部の動きを滑らかにし、音を消す",
      isMagic: false,
    },
    {
      name: "月光の魔符",
      price: 200,
      note: "半径30m内を極めて明るく照らす（魔力）",
      isMagic: false,
    },
    {
      name: "聖水",
      price: 500,
      note: "神聖魔法「ホーリーライト」に同じ効果を得る",
      isMagic: false,
    },
    {
      name: "護りの魔符",
      price: 500,
      note: "精神抵抗力判定にボーナス修正、サイコロを振った後に使用可能",
      isMagic: false,
    },
    { name: "絆の魔符", price: 1000, note: "他者の使用可能な「魔力」の護符" },
    { name: "光の魔符", price: 1000, note: "戦闘に使用可能な《月光の魔符》" },
    {
      name: "リリック・グルージャ",
      price: 1000,
      note: "30秒の効果を回復する妖精",
      isMagic: false,
    },
    {
      name: "デビルズ・カース",
      price: 1000,
      note: "相手の武器の威力を減少させる",
      isMagic: false,
    },
    { name: "輝き", price: 6000, note: "10分間、周囲の者から逃れる" },
    {
      name: "一角獣の角",
      price: 1000,
      note: "触れたものの毒、病気を治癒、または、アンデッドにダメージ",
      isMagic: false,
    },
  ],
  特殊楽器: [
    {
      name: "〈シンバルシールド〉",
      price: 1020,
      note: "盾として使用時に「楽素：(高揚)or(鎮静)」を生成(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈パラスマラカ〉",
      price: 1360,
      note: "武器として使用時に「楽素：(高揚)or(鎮静)」を生成(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈パーカッションフレイル〉",
      price: 1380,
      note: "武器として使用時に「楽素：(高揚)or(鎮静)」を生成(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈ストリングボウ〉",
      price: 1880,
      note: "武器として使用時に「楽素：(魅惑)」を生成(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈奏楽のリュート〉",
      price: 9200,
      note: "呪歌の条件や終律の消費から楽素を1つ軽減する(詳細⇒Ⅰ129頁)",
      isMagic: false,
    },
    {
      name: "〈フィスタロッサム〉",
      price: 16100,
      note: "楽器として使用時に呪歌の対象を増やす(詳細⇒Ⅰ130頁)",
      isMagic: false,
    },
    {
      name: "〈ミューズのホルン〉",
      price: 16900,
      note: "楽素を追加で生成する(詳細⇒Ⅰ130頁)",
      isMagic: false,
    },
  ],
  装飾品_耳: [
    {
      name: "〈イヤリング〉",
      price: 5,
      note: "ピアス。天然石60～, 宝石製100～",
      isMagic: false,
    },
    { name: "〈リングピアス〉", price: 10, note: "イヤリング。ピアス。" },
    { name: "〈イヤーカフス〉", price: 10, note: "耳の縁につける" },
    { name: "〈巨人の耳飾り〉", price: 100, note: "特定の人の声を聞き続ける" },
    {
      name: "〈レコーディングピアス〉",
      price: 1600,
      note: "耳に1時間の音の記録を5回録音・再生できる",
      isMagic: false,
    },
    {
      name: "〈アンテナ(耳)〉",
      price: 2200,
      note: "10m手前から音と聞き分ける",
      isMagic: false,
    },
    { name: "〈スマティーの耳飾り〉", price: 2800, note: "「騎獣」中のHPに+2" },
    { name: "〈マジックアッパー〉", price: 3500, note: "魔法ダメージ+2" },
    {
      name: "〈盗聴の耳飾り〉",
      price: 3500,
      note: "見えない状況でも行動できる",
      isMagic: false,
    },
    {
      name: "〈翻訳の耳飾り〉",
      price: 5000,
      note: "耳にする特定の言語を理解できるようになる",
      isMagic: false,
    },
    {
      name: "〈石人の耳飾り〉",
      price: 6640,
      note: "体がわずかに石化し、骨格のなしと引き替えに防護点が+5される",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの耳飾り〉",
      price: 7500,
      note: "「装備部位：そのほか随意」と置き換え。筋力・生命力+1",
      isMagic: false,
    },
    {
      name: "〈頑強のピアス〉",
      price: 10640,
      note: "アンデット・インペリテブに+2ダメージ",
      isMagic: false,
    },
    {
      name: "〈血のフォークの耳飾り〉",
      price: 12000,
      note: "「血のフォーク」によってダメージを受けるとき、回復できる。セット価格",
      isMagic: false,
    },
  ],
  装飾品_顔: [
    {
      name: "〈スマティエの装飾品〉",
      price: 250,
      note: "魔物知識で時代のブランド。3種類以上装備で全能力上昇",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの装飾品〉",
      price: 500,
      note: "魔物知識で時代のブランド。3種類以上装備で精神力上昇",
      isMagic: false,
    },
    { name: "〈髪飾り〉", price: 3, note: "布製、髪の長さを自在に変える" },
    {
      name: "〈髪飾り(彫金)〉",
      price: 10,
      note: "ビーズ製～, 天然石60～, 宝石製100～",
      isMagic: false,
    },
    {
      name: "〈サークレット〉",
      price: 20,
      note: "魔物知識に特定種族に特化し、特定のダメージに弱い",
      isMagic: false,
    },
    { name: "〈ヘルメット〉", price: 200, note: "頑丈" },
    {
      name: "〈羽〉",
      price: 500,
      note: "セージ判定でパッケージの再挑戦を半分の時間でできる",
      isMagic: false,
    },
    {
      name: "〈獣の耳かき〉",
      price: 800,
      note: "これを使うとリラックスできる",
      isMagic: false,
    },
    {
      name: "〈閃きの眼鏡〉",
      price: 900,
      note: "セージ判定に+1のボーナス修正",
      isMagic: false,
    },
    {
      name: "〈雷雲の髪飾り〉",
      price: 1500,
      note: "投げる。雷属性の魔法ダメージ。(威力20+5)",
      isMagic: false,
    },
    {
      name: "〈氷雪の髪飾り〉",
      price: 1500,
      note: "投げる。氷属性の魔法ダメージ。(威力20+5)",
      isMagic: false,
    },
    {
      name: "〈霜の髪飾り〉",
      price: 1500,
      note: "投げる。水・氷属性の魔法ダメージ。(威力20+5)",
      isMagic: false,
    },
    {
      name: "〈セーフティメット〉",
      price: 2000,
      note: "ダメージの「 C 値+1」詳細⇒Ⅰ138頁",
      isMagic: false,
    },
    { name: "〈素敵なウィッグ〉", price: 2500, note: "危険感知判定に+1" },
    {
      name: "〈セーフティハット〉",
      price: 2500,
      note: "ダメージの「 C 値+1」詳細⇒Ⅰ138頁",
      isMagic: false,
    },
    {
      name: "〈シースルーハット〉",
      price: 4100,
      note: "HPの最大値を超えたダメージで気絶する。隠蔽不可",
      isMagic: false,
    },
    {
      name: "〈グランシティハット〉",
      price: 6000,
      note: "HP回復効果を受けたときにMPが「1」点回復",
      isMagic: false,
    },
    {
      name: "〈聖印〉",
      price: 10000,
      note: "手元にあればあらゆる信仰の神聖魔法を習得",
      isMagic: false,
    },
    { name: "〈獣の証〉", price: 10000, note: "回避力判定に+2(詳細⇒Ⅰ138頁)" },
    {
      name: "〈叡智の三人の贈り物〉",
      price: 18000,
      note: "魔物知識判定に+2(詳細⇒Ⅰ138頁)。稀に戦闘行為を行う、または決戦品",
      isMagic: false,
    },
    {
      name: "〈女神のヴェール〉",
      price: 20000,
      note: "鉄魔法の効果を延長する。女性専用(詳細⇒Ⅰ139頁)",
      isMagic: false,
    },
    {
      name: "〈女牧場の証〉",
      price: 20000,
      note: "鉄魔法の効果を延長する。女性専用(詳細⇒Ⅰ139頁)",
      isMagic: false,
    },
    {
      name: "〈支配の髪飾り〉",
      price: 25000,
      note: "装備者が与えるダメージが全て物理属性に。精神抵抗力+139",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの頭飾り〉",
      price: 60000,
      note: "追加の行動を行える(詳細⇒Ⅰ139頁)",
      isMagic: false,
    },
    { name: "〈マスク〉", price: 10, note: "口の周辺のみを覆う" },
    {
      name: "〈仮面〉",
      price: 20,
      note: "木製10～, パーティ用60～, 金属製100～",
      isMagic: false,
    },
    { name: "〈つけヒゲ〉", price: 20, note: "つけると髭が伸びたように見える" },
    {
      name: "〈眼帯〉",
      price: 30,
      note: "病気や怪我を隠す。ファッション性も高い",
      isMagic: false,
    },
    {
      name: "〈モノクル〉",
      price: 200,
      note: "片眼鏡。サイズが特になるため装飾より高価",
      isMagic: false,
    },
    {
      name: "〈瓶底の眼鏡〉",
      price: 1000,
      note: "よく見えない特殊レンズ。遠視、近視、乱視も。",
      isMagic: false,
    },
    {
      name: "〈水中眼鏡〉",
      price: 2000,
      note: "破壊することで曇りもとらず物に対する命中・生命精神抵抗力-2",
      isMagic: false,
    },
    {
      name: "〈ナイトゴーグル〉",
      price: 2000,
      note: "味覚を遮断し、乱雑な学術判定に+2",
      isMagic: false,
    },
    { name: "〈夜のとばり〉", price: 3000, note: "睡眠を阻害し、学術判定に+1" },
    { name: "〈暗視の仮面〉", price: 3000, note: "暗視の能力を得る" },
    {
      name: "〈不屈の仮面〉",
      price: 4620,
      note: "HPが0点以下になるとレベルの回復時、HPが追加で10点回復",
      isMagic: false,
    },
    {
      name: "〈水飲み鳥のマスク〉",
      price: 6000,
      note: "毒・病気のダメージの「威力」にレベルのボーナス修正",
      isMagic: false,
    },
    {
      name: "〈逃すものの目〉",
      price: 7200,
      note: "「冒険者」失格時に望むと1体を引き追加指定できる",
      isMagic: false,
    },
    {
      name: "〈スパイダーマスク〉",
      price: 9600,
      note: "魔物知識判定で失敗時に対象のレベルがわかる。成功時は魔物知識判定に+2",
      isMagic: false,
    },
    {
      name: "〈スマティエのガード〉",
      price: 12000,
      note: "純エネルギー属性の魔法ダメージを-4",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの仮面〉",
      price: 20000,
      note: "魔物の弱点を4点低いものとする",
      isMagic: false,
    },
  ],
  装飾品_首: [
    { name: "〈首輪〉", price: 5, note: "ビーズ5～, 天然石8～, 宝石製100～" },
    {
      name: "〈チョーカー〉",
      price: 10,
      note: "ある地方では「家畜」の意味がある",
      isMagic: false,
    },
    {
      name: "〈ラリエット〉",
      price: 15,
      note: "緩めの首飾り。ある地方では「家畜」の意味がある",
      isMagic: false,
    },
    { name: "〈革紐のチョーカー〉", price: 10, note: "魔物の牙や爪を飾る" },
    {
      name: "〈老婆の首飾り〉",
      price: 1700,
      note: "任意の老婆を被っているように見える",
      isMagic: false,
    },
    { name: "〈浮遊の首飾り〉", price: 3000, note: "飛行" },
    {
      name: "〈ドクターペンダント〉",
      price: 3000,
      note: "抵抗力判定に+1。精神力からのダメージを-1",
      isMagic: false,
    },
    {
      name: "〈マナ・フレアレット〉",
      price: 4500,
      note: "「魔力」に+1のボーナス修正",
      isMagic: false,
    },
    {
      name: "〈ティカ・ミレット〉",
      price: 6000,
      note: "魔物知識を有利に進める",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの首飾り〉",
      price: 10000,
      note: "気絶判定を乗り越える",
      isMagic: false,
    },
    {
      name: "〈ホーリーシンボル〉",
      price: 25000,
      note: "MPを10点以上有するとHPが回復",
      isMagic: false,
    },
    {
      name: "〈カース・レベリオン〉",
      price: 40000,
      note: "10分間、受けるダメージを+3。魔物からのダメージを-3",
      isMagic: false,
    },
  ],
  装飾品_背中: [
    {
      name: "〈ロングマント〉",
      price: 30,
      note: "綿でできた長めのマント。フード付き40～",
      isMagic: false,
    },
    {
      name: "〈ポンチョ〉",
      price: 40,
      note: "四角い布の中央に穴を通し、かぶって着用する。",
      isMagic: false,
    },
    { name: "〈ハーマンマント〉", price: 50, note: "" },
    {
      name: "〈サバイバルコート〉",
      price: 180,
      note: "防熱、防寒、防水に優れてるコート",
      isMagic: false,
    },
    {
      name: "〈ウェポンホルダー〉",
      price: 1000,
      note: "武器を背中に2つ装備できる",
      isMagic: false,
    },
    {
      name: "〈野伏のマント〉",
      price: 1000,
      note: "「部位：背中」の装飾品を追加装備できる。要レンジャー",
      isMagic: false,
    },
    {
      name: "〈暗殺者のマント〉",
      price: 1000,
      note: "隠密判定に+1のボーナス修正",
      isMagic: false,
    },
    {
      name: "〈リサイクリング〉",
      price: 3000,
      note: "落すダメージを「-20」点する",
      isMagic: false,
    },
    { name: "〈サーマルマント〉", price: 3500, note: "温度変化から身を守る" },
    {
      name: "〈ペンギンマント〉",
      price: 5000,
      note: "氷や水属性の不利な効果を受けず、氷・水判定+4",
      isMagic: false,
    },
    {
      name: "〈サーペントマント〉",
      price: 8000,
      note: "回復や抵抗の失敗時に魔法ダメージ-4",
      isMagic: false,
    },
    {
      name: "〈インビジブルマント〉",
      price: 9000,
      note: "魔法文字で隠蔽して姿を消す。探索、魔物知識、鑑定、危険感知判定にペナルティ",
      isMagic: false,
    },
    {
      name: "〈断罪のマント〉",
      price: 10000,
      note: "ブレスに対してダメージを-5する",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの肩掛け〉",
      price: 15000,
      note: "魔物に対する誘導を得る",
      isMagic: false,
    },
    {
      name: "〈スマティエの裏切り〉",
      price: 25000,
      note: "10秒（1ラウンド）の間、命中力判定と回避力判定に+2",
      isMagic: false,
    },
  ],
  装飾品_腰: [
    {
      name: "〈ベルト〉",
      price: 10,
      note: "シンプルで細いもので、よいものやデザインに凝ったものも15～",
      isMagic: false,
    },
    { name: "〈ガードベルト〉", price: 50, note: "" },
    { name: "〈コルセット〉", price: 80, note: "スタイルがよく見える" },
    {
      name: "〈多機能ベルト〉",
      price: 1000,
      note: "「部位：腰」の装飾品を追加装備できる。要スカウト技能3レベル",
      isMagic: false,
    },
    { name: "〈チャンピオンベルト〉", price: 1500, note: "" },
    {
      name: "〈日輪のバックル〉",
      price: 1500,
      note: "アンデッドに対する生命・精神抵抗力判定に+1",
      isMagic: false,
    },
    {
      name: "〈変身ベルト〉",
      price: 1500,
      note: "任意の鎧を着ているように見せる",
      isMagic: false,
    },
    {
      name: "〈ミサイルランチャー〉",
      price: 1660,
      note: "両横からミサイルを発射し、両横から装備者を守る",
      isMagic: false,
    },
    { name: "〈ブラックベルト〉", price: 3000, note: "防護点+1" },
    {
      name: "〈竜のベルト〉",
      price: 4500,
      note: "「部位：腰」の装飾品で衝撃を吸収する",
      isMagic: false,
    },
    {
      name: "〈スマティエの武勇〉",
      price: 6000,
      note: "格闘【カテゴリ】のダメージに生命力ボーナスをプラス",
      isMagic: false,
    },
    {
      name: "〈不滅のバックル〉",
      price: 12300,
      note: "「部位：腰」の装飾品で(火矢)の攻撃を精神抵抗力で耐える",
      isMagic: false,
    },
    {
      name: "〈真ブラックベルト〉",
      price: 20000,
      note: "防護点+2、グラップラー技能3レベル",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの帯〉",
      price: 26000,
      note: "装備者が自然治癒力（「1」+108頁）にあるものとする",
      isMagic: false,
    },
    {
      name: "〈グリーンベルト〉",
      price: 35000,
      note: "製作者を魔力（「威力」）にすることができる",
      isMagic: false,
    },
  ],
  装飾品_手: [
    { name: "〈指輪〉", price: 5, note: "ビーズ5～, 天然石8～, 宝石製100～" },
    { name: "〈リストバンド〉", price: 7, note: "手にはめるもの。革製8～" },
    { name: "〈腕輪〉", price: 9, note: "10秒（1ラウンド）の間、宝石製100～" },
    { name: "〈手袋〉", price: 10, note: "布製10～, 絹製18～" },
    { name: "〈アームレット〉", price: 10, note: "上腕につける腕輪" },
    {
      name: "〈ガントレット〉",
      price: 200,
      note: "手甲。革製200～, 金属製250～",
      isMagic: false,
    },
    {
      name: "〈能力増強の指輪〉",
      price: 500,
      note: "特定能力値を+1。増やすと+13",
      isMagic: false,
    },
    {
      name: "〈平素の指輪〉",
      price: 500,
      note: "特定能力値を+1。増やすと+13。戦闘時に破壊で能力値を適用",
      isMagic: false,
    },
    {
      name: "〈伝令の腕輪〉",
      price: 900,
      note: "1日1回だけ誰かにメッセージを送る",
      isMagic: false,
    },
    {
      name: "〈能力増強の腕輪〉",
      price: 1000,
      note: "特定能力値を+2,+2。増やすと+14",
      isMagic: false,
    },
    {
      name: "〈俊足のブレスレット〉",
      price: 5000,
      note: "水を弾かせる。また、氷・水属性のダメージを「-1」",
      isMagic: false,
    },
    {
      name: "〈レインボーリング〉",
      price: 5000,
      note: "さまざまな色の光を発し、周囲を照らす",
      isMagic: false,
    },
    {
      name: "〈大きな手〉",
      price: 8000,
      note: "本来の腕に装備。他の部位も装備可能",
      isMagic: false,
    },
    {
      name: "〈マナリング〉",
      price: 10000,
      note: "精神抵抗力判定を+2,+1。魔法の発動体を兼ねる",
      isMagic: false,
    },
    { name: "〈博打の指輪〉", price: 24800, note: "見えない手を得る" },
    {
      name: "〈正しき意思のリング〉",
      price: 30000,
      note: "精神抵抗力判定に+1",
      isMagic: false,
    },
    {
      name: "〈ラル=ヴェイダの指輪〉",
      price: 40000,
      note: "「魔物」のHPが0点以下になったとき、魔法の発動体を兼ねる",
      isMagic: false,
    },
  ],
  装飾品_足: [
    {
      name: "〈トリング〉",
      price: 5,
      note: "ビーズ5～, 天然石8～, 宝石製100～",
      isMagic: false,
    },
    { name: "〈おしぼり〉", price: 15, note: "" },
    {
      name: "〈アンクレット〉",
      price: 20,
      note: "金属製。ある地方では「家畜」の意味がある。銀製100～",
      isMagic: false,
    },
    {
      name: "〈夜会への招待状〉",
      price: 20,
      note: "革製。ある地方では「家畜」の意味がある。銀製100～",
      isMagic: false,
    },
    { name: "〈サンダル〉", price: 500, note: "足首で転がして転がせる" },
    {
      name: "〈身代わりのサンダル〉",
      price: 2000,
      note: "足のダメージを肩代わりする",
      isMagic: false,
    },
    { name: "〈土踏まず〉", price: 2800, note: "足首で転がして転がせる" },
  ],
  装飾品_任意: [
    { name: "〈リボン〉", price: 1, note: "" },
    { name: "〈バンダナ〉", price: 5, note: "" },
    { name: "〈ハンカチ〉", price: 8, note: "" },
    { name: "〈リボン〉", price: 35, note: "" },
    { name: "〈ディスプレイサージ〉", price: 5000, note: "" },
    { name: "〈チョーカー〉", price: 10000, note: "" },
    { name: "〈勇者の証〉", price: 30, note: "" },
  ],
};
window.sw25_data.Regulations = [
  {
    label: "初期作成",
    growth: 0,
    exp: 3000,
    money: 1200,
    honor: 0,
    abyssShard: 0,
  },
  {
    label: "3～4",
    growth: 2,
    exp: 5500,
    money: 2500,
    honor: 30,
    abyssShard: 1,
  },
  {
    label: "4～5",
    growth: 5,
    exp: 10000,
    money: 6000,
    honor: 80,
    abyssShard: 2,
  },
  {
    label: "5～6",
    growth: 9,
    exp: 16000,
    money: 14000,
    honor: 150,
    abyssShard: 3,
  },
  {
    label: "6～7",
    growth: 13,
    exp: 23000,
    money: 24000,
    honor: 250,
    abyssShard: 5,
  },
  {
    label: "7～8",
    growth: 17,
    exp: 30000,
    money: 36000,
    honor: 350,
    abyssShard: 7,
  },
  {
    label: "8～9",
    growth: 22,
    exp: 40000,
    money: 54000,
    honor: 500,
    abyssShard: 9,
  },
  {
    label: "9～10",
    growth: 28,
    exp: 50000,
    money: 80000,
    honor: 700,
    abyssShard: 12,
  },
  {
    label: "10～11",
    growth: 34,
    exp: 65000,
    money: 120000,
    honor: 900,
    abyssShard: 15,
  },
  {
    label: "11～12",
    growth: 44,
    exp: 85000,
    money: 160000,
    honor: 1300,
    abyssShard: 21,
  },
  {
    label: "12～13",
    growth: 54,
    exp: 105000,
    money: 210000,
    honor: 1700,
    abyssShard: 30,
  },
  {
    label: "13～14",
    growth: 65,
    exp: 135000,
    money: 270000,
    honor: 2200,
    abyssShard: 39,
  },
  {
    label: "14～15",
    growth: 77,
    exp: 165000,
    money: 350000,
    honor: 2800,
    abyssShard: 48,
  },
  {
    label: "15+A",
    growth: 90,
    exp: 200000,
    money: 450000,
    honor: 3500,
    abyssShard: 57,
  },
  {
    label: "15+B",
    growth: 100,
    exp: 220000,
    money: 500000,
    honor: 4000,
    abyssShard: 66,
  },
  {
    label: "15+C",
    growth: 110,
    exp: 250000,
    money: 550000,
    honor: 4500,
    abyssShard: 75,
  },
];
