// js/sw25_data.js
// キャラクター保管所のデータを元に、ジェネレーターで使いやすいよう整形したデータ集

window.sw25_data = {
  // 種族データ (Shuzoku)
  Races: {
    人族: [
      {
        name: "人間",
        stats: [2, 2, 2, 2, 2, 2],
        ability: "［剣の加護／運命変転］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "エルフ",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護／優しき水］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "エルフ（スノウエルフ）",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護／優しき水］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "エルフ（ミストエルフ）",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護／惑いの霧］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ドワーフ",
        stats: [3, 1, 2, 2, 1, 3],
        ability: "［暗視］［剣の加護／炎身］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ダークドワーフ",
        stats: [3, 1, 2, 1, 1, 3],
        ability: "［暗視］［黒炎の担い手］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "タビット",
        stats: [1, 1, 1, 2, 3, 2],
        ability: "［第六感］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "タビット（パイカ種タビット）",
        stats: [1, 1, 1, 2, 3, 2],
        ability: "［第六感］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "タビット（リパス種タビット）",
        stats: [1, 1, 1, 2, 3, 2],
        ability: "［第六感］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "ルーンフォーク",
        stats: [2, 1, 2, 2, 2, 1],
        ability: "［暗視］［HP変換］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "ルーンフォーク（護衛型ルーンフォーク）",
        stats: [2, 1, 2, 2, 2, 1],
        ability: "［暗視］［HP変換］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "ルーンフォーク（戦闘型ルーンフォーク）",
        stats: [2, 1, 2, 2, 2, 1],
        ability: "［暗視］［HP変換］",
        birthIds: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        name: "ナイトメア（人間）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（エルフ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（ドワーフ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（リルドラケン）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（シャドウ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ナイトメア（ソレイユ）",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［異貌］［弱点（銀）］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "リカント",
        stats: [1, 7, 2, 2, 5, 1],
        ability: "［獣変貌］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "リカント（大型草食獣リカント）",
        stats: [1, 7, 2, 2, 5, 1],
        ability: "［獣変貌］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "リカント（小型草食獣リカント）",
        stats: [1, 7, 2, 2, 5, 1],
        ability: "［獣変貌］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "リルドラケン",
        stats: [1, 2, 2, 3, 1, 2],
        ability: "［鱗の皮膚］［尻尾が武器］［剣の加護／風の翼］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "リルドラケン（小翼種リルドラケン）",
        stats: [1, 2, 2, 3, 1, 2],
        ability: "［鱗の皮膚］［尻尾が武器］［剣の加護／風の翼］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "リルドラケン（有毛種リルドラケン）",
        stats: [1, 2, 2, 3, 1, 2],
        ability: "［鱗の皮膚］［尻尾が武器］［剣の加護／風の翼］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "グラスランナー",
        stats: [2, 2, 1, 3, 1, 3],
        ability: "［マナ不干渉］［植物・昆虫との意思疎通］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "グラスランナー（アリーシャ）",
        stats: [2, 2, 1, 3, 1, 3],
        ability: "［マナ不干渉］［植物・昆虫との意思疎通］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "グラスランナー（クリメノス）",
        stats: [2, 2, 1, 3, 1, 3],
        ability: "［マナ不干渉］［植物・昆虫との意思疎通］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "メリア",
        stats: [1, 1, 1, 3, 1, 1],
        ability: "［繁茂する生命］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "メリア（カーニバラスメリア）",
        stats: [1, 1, 1, 3, 1, 1],
        ability: "［繁茂する生命］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "メリア（ファンギーメリア）",
        stats: [1, 1, 1, 3, 1, 1],
        ability: "［繁茂する生命］",
        birthIds: [1, 2, 3, 4, 5],
      },
      {
        name: "ティエンス",
        stats: [2, 2, 1, 7, 2, 8],
        ability: "［通じ合う意識］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ティエンス（ティエンス機解種）",
        stats: [2, 2, 1, 7, 2, 8],
        ability: "［通じ合う意識］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "ティエンス（ティエンス魔解種）",
        stats: [2, 2, 1, 7, 2, 8],
        ability: "［通じ合う意識］",
        birthIds: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        name: "レプラカーン",
        stats: [2, 1, 2, 2, 2, 2],
        ability: "［暗視］［見えざる手］［姿なき職人］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "レプラカーン（放浪種レプラカーン）",
        stats: [2, 1, 2, 2, 2, 2],
        ability: "［暗視］［見えざる手］［姿なき職人］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "レプラカーン（探索種レプラカーン）",
        stats: [2, 1, 2, 2, 2, 2],
        ability: "［暗視］［見えざる手］［姿なき職人］",
        birthIds: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "アルヴ",
        stats: [1, 7, 8, 2, 5, 1],
        ability: "［暗視］［吸精］",
      },
      {
        name: "シャドウ",
        stats: [1, 1, 2, 2, 2, 2],
        ability: "［暗視］［月光の守り］",
      },
      {
        name: "ソレイユ",
        stats: [1, 2, 5, 2, 1, 2],
        ability: "［輝く肉体］［太陽の再生］［太陽の子］",
      },
      {
        name: "スプリガン",
        stats: [1, 2, 1, 1, 2, 1],
        ability: "［暗視］［巨人化］",
      },
      {
        name: "アビスボーン",
        stats: [2, 1, 5, 2, 2, 1],
        ability: "［アビスカース付与］など",
      },
      {
        name: "ハイマン",
        stats: [2, 1, 2, 1, 1, 1],
        ability: "［デジャヴ］［魔法の申し子］",
      },
      {
        name: "フロウライト",
        stats: [2, 2, 3, 2, 1, 3],
        ability: "［魂の輝き］［鉱石の生命］［晶石の身体］",
      },
      {
        name: "フィー",
        stats: [2, 3, 1, 1, 1, 2],
        ability: "［妖精の加護］［浮遊］",
      },
      {
        name: "ミアキス",
        stats: [1, 2, 1, 2, 3, 2],
        ability: "［暗視］［猫変化］［獣性の発露］",
      },
      {
        name: "ヴァルキリー",
        stats: [2, 1, 2, 2, 1, 5],
        ability: "［戦乙女の光羽］［戦乙女の祝福］",
      },
      {
        name: "センティアン（ルミエル）",
        stats: [1, 2, 6, 6, 6, 6],
        ability: "［刻まれし聖印］など",
      },
      {
        name: "センティアン（カルディア）",
        stats: [1, 2, 6, 6, 6, 6],
        ability: "［刻まれし聖印］など",
      },
      {
        name: "ノーブルエルフ",
        stats: [2, 2, 1, 2, 2, 2],
        ability: "［暗視］［剣の加護/水の申し子］［カリスマ］［弱点(物理+2)］",
      },
      {
        name: "マナフレア",
        stats: [2, 5, 3, 2, 2, 5],
        ability: "［溢れるマナ］［マナの手］",
      },
      {
        name: "魔動天使",
        stats: [2, 5, 5, 2, 2, 2],
        ability: "［暗視］［鋼鉄の翼］［新たな契約の絆］［造られし強さ］",
      },
    ],
    蛮族: [
      {
        name: "ウィークリング（ガルーダ）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（タンノズ）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（バジリスク）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（ミノタウロス）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ウィークリング（マーマン）",
        stats: [4, 4, 4, 4, 4, 4],
        ability: "［弱点］など",
      },
      {
        name: "ドレイク",
        stats: [1, 1, 2, 2, 3, 2],
        ability: "［暗視］［限定竜化］［光ブレス］［弱点(魔法+2)］",
      },
      {
        name: "ドレイクブロークン",
        stats: [1, 1, 2, 2, 3, 2],
        ability: "［暗視］［限定竜化］［光ブレス］［弱点(魔法+2)］",
      },
      {
        name: "バジリスク",
        stats: [5, 2, 2, 2, 1, 1],
        ability: "［邪視と瞳石］［猛毒の血液］［魔物化］［弱点(水氷+3)］",
      },
      {
        name: "ディアボロ",
        stats: [2, 2, 3, 2, 1, 5],
        ability: "［暗視］［飛行］［魔人の皮膚］［魔人化］［弱点(純EN+3)］",
      },
      {
        name: "ダークトロール",
        stats: [2, 1, 2, 3, 1, 2],
        ability: "［暗視］［弱体化］［体躯］［弱点(魔法+2)］",
      },
      {
        name: "アルボル",
        stats: [2, 2, 1, 7, 2, 2],
        ability: "［憤怒の炎］［弱点(炎+3)］",
      },
      {
        name: "バーバヤガー",
        stats: [2, 1, 1, 1, 2, 3],
        ability: "［魔女化］［魔女の火］［弱点(物理+2)］",
      },
      {
        name: "ケンタウロス",
        stats: [3, 1, 2, 2, 1, 2],
        ability: "［半馬半人］［馬人の武術］［弱点(土+3)］",
      },
      {
        name: "シザースコーピオン",
        stats: [5, 1, 2, 2, 2, 2],
        ability: "［暗視］［蠍人の身体］［蠍人の体術］［弱点(物理+2)］",
      },
      {
        name: "ドーン",
        stats: [3, 2, 1, 2, 2, 1],
        ability: "［暗視］［暗殺の心得］［親しき闇］［弱点(命中+1)］",
      },
      {
        name: "コボルド",
        stats: [2, 2, 1, 1, 2, 2],
        ability: "［種の限界］［軽視］［小さな匠］［弱点(魔法+2)］",
      },
      {
        name: "ラミア",
        stats: [1, 2, 1, 2, 2, 2],
        ability: "［暗視］［ラミアの身体］［吸血］［変化］［弱点(土+3)］",
      },
      {
        name: "ラルヴァ",
        stats: [1, 2, 3, 1, 2, 1],
        ability: "［暗視］［弱体化］［吸血の祝福］［忌むべき血］",
      },
      {
        name: "リザードマン",
        stats: [1, 2, 2, 2, 2, 1],
        ability: "［尻尾が武器］［水中活動］［無呼吸活動］［弱点(土+3)］",
      },
      {
        name: "ライカンスロープ",
        stats: [4, 4, 4, 3, 2, 2],
        ability: "［暗視］［獣人の力］［獣化］［弱点(銀+3)］",
      },
      {
        name: "バルカン",
        stats: [2, 1, 2, 3, 2, 1],
        ability: "［暗視］［炎無効］［バルカンの宝石］［弱点(水・氷+3)］",
      },
      {
        name: "センティアン（イグニス）",
        stats: [1, 2, 6, 6, 6, 6],
        ability: "［刻まれし聖印］など",
      },
    ],
    その他: [
      { name: "その他（自由記入）", stats: [0, 0, 0, 0, 0, 0], ability: "" },
    ],
  },

  // 生まれデータ (Umare25)
  Births: [
    { name: "魔動機師", stats: [8, 4, 9], exp: 2000, skills: ["マギテック"] },
    {
      name: "魔法使い",
      stats: [7, 4, 10],
      exp: 2000,
      skills: ["ソーサラー", "コンジャラー"],
    },
    {
      name: "軽戦士",
      stats: [10, 7, 4],
      exp: 2000,
      skills: ["フェンサー", "スカウト"],
    },
    { name: "一般人", stats: [7, 7, 7], exp: 3000, skills: [] },
    {
      name: "傭兵",
      stats: [7, 10, 4],
      exp: 2000,
      skills: ["ファイター", "グラップラー"],
    },
    { name: "神官", stats: [4, 8, 9], exp: 2000, skills: ["プリースト"] },
    {
      name: "妖精使い",
      stats: [6, 6, 9],
      exp: 2000,
      skills: ["フェアリーテイマー"],
    },
    { name: "冒険者", stats: [0, 0, 0], exp: 3000, skills: [] },
    { name: "斥候", stats: [10, 6, 5], exp: 2500, skills: ["スカウト"] },
    { name: "狩人", stats: [9, 7, 5], exp: 2500, skills: ["シューター"] },
    { name: "練体師", stats: [8, 8, 5], exp: 2500, skills: ["エンハンサー"] },
    { name: "魔導師", stats: [6, 5, 10], exp: 2000, skills: ["ソーサラー"] },
    { name: "拳闘士", stats: [8, 9, 4], exp: 2000, skills: ["グラップラー"] },
    { name: "剣士", stats: [9, 8, 4], exp: 2500, skills: ["フェンサー"] },
    { name: "学者", stats: [5, 7, 9], exp: 2500, skills: ["セージ"] },
    { name: "薬師", stats: [9, 4, 8], exp: 2500, skills: ["レンジャー"] },
    { name: "吟遊詩人", stats: [7, 5, 9], exp: 2500, skills: ["バード"] },
    {
      name: "趣味人",
      stats: [8, 5, 8],
      exp: 2000,
      skills: ["レンジャー", "バード"],
    },
    { name: "錬金術師", stats: [6, 7, 8], exp: 2500, skills: ["アルケミスト"] },
    { name: "軍師", stats: [7, 8, 6], exp: 2500, skills: ["ウォーリーダー"] },
    {
      name: "魔法戦士",
      stats: [5, 8, 8],
      exp: 1000,
      skills: ["ファイター", "ソーサラー"],
    },
    { name: "占い師", stats: [9, 3, 9], exp: 2500, skills: ["ミスティック"] },
    {
      name: "参謀",
      stats: [6, 5, 10],
      exp: 2000,
      skills: ["セージ", "ウォーリーダー"],
    },
    {
      name: "魔神使い",
      stats: [3, 8, 10],
      exp: 2000,
      skills: ["デーモンルーラー"],
    },
    { name: "魔工士", stats: [7, 8, 6], exp: 2500, skills: ["アーティザン"] },
    { name: "武官", stats: [7, 9, 5], exp: 2000, skills: ["ファイター"] },
    { name: "貴族", stats: [6, 7, 8], exp: 2500, skills: ["アリストクラシー"] },
    { name: "秘術師", stats: [7, 4, 10], exp: 2000, skills: ["グリモワール"] },
    {
      name: "魔術師",
      stats: [5, 7, 9],
      exp: 2000,
      skills: ["ソーサラー", "コンジャラー"],
    },
    { name: "乗り手", stats: [12, 5, 9], exp: 2500, skills: ["ライダー"] },
    {
      name: "戦奏士",
      stats: [10, 3, 13],
      exp: 2000,
      skills: ["バード", "ウォーリーダー"],
    },
    {
      name: "戦軍師",
      stats: [12, 4, 10],
      exp: 2000,
      skills: ["フェンサー", "ウォーリーダー"],
    },
    {
      name: "銃使い",
      stats: [7, 6, 7],
      exp: 1500,
      skills: ["シューター", "マギテック"],
    },
    {
      name: "錬金戦士",
      stats: [8, 7, 5],
      exp: 1500,
      skills: ["ファイター", "アルケミスト"],
    },
    { name: "楽師", stats: [7, 4, 11], exp: 2500, skills: ["バード"] },
    {
      name: "道化",
      stats: [12, 0, 13],
      exp: 2500,
      skills: ["アリストクラシー"],
    },
    { name: "呪術師", stats: [10, 12, 8], exp: 2000, skills: ["コンジャラー"] },
    { name: "戦士", stats: [12, 14, 4], exp: 2000, skills: ["ファイター"] },
    {
      name: "神官戦士",
      stats: [12, 12, 6],
      exp: 1000,
      skills: ["ファイター", "プリースト"],
    },
    { name: "騎手", stats: [8, 12, 8], exp: 2500, skills: ["ライダー"] },
    {
      name: "密偵",
      stats: [15, 0, 10],
      exp: 2000,
      skills: ["フェンサー", "スカウト"],
    },
    {
      name: "神官闘士",
      stats: [8, 13, 5],
      exp: 1000,
      skills: ["プリースト", "グラップラー"],
    },
    {
      name: "神学者",
      stats: [6, 11, 9],
      exp: 1500,
      skills: ["プリースト", "セージ"],
    },
    {
      name: "神楽師",
      stats: [5, 14, 7],
      exp: 1500,
      skills: ["プリースト", "バード"],
    },
    {
      name: "神操術士",
      stats: [4, 12, 10],
      exp: 1000,
      skills: ["プリースト", "コンジャラー"],
    },
    {
      name: "魔動神官",
      stats: [9, 9, 8],
      exp: 1000,
      skills: ["プリースト", "マギテック"],
    },
    {
      name: "魔神操者",
      stats: [7, 10, 9],
      exp: 1000,
      skills: ["プリースト", "デーモンルーラー"],
    },
    {
      name: "秘術神官",
      stats: [8, 6, 7],
      exp: 1000,
      skills: ["プリースト", "グリモワール"],
    },
    {
      name: "魔工神官",
      stats: [8, 4, 8],
      exp: 1500,
      skills: ["プリースト", "アーティザン"],
    },
    {
      name: "妖精貴師",
      stats: [10, 5, 13],
      exp: 1500,
      skills: ["フェアリーテイマー", "アリストクラシー"],
    },
    {
      name: "貴神官",
      stats: [10, 6, 12],
      exp: 1500,
      skills: ["プリースト", "アリストクラシー"],
    },
    {
      name: "貴学者",
      stats: [10, 4, 14],
      exp: 2000,
      skills: ["セージ", "アリストクラシー"],
    },
    {
      name: "野伏貴族",
      stats: [12, 6, 10],
      exp: 2000,
      skills: ["レンジャー", "アリストクラシー"],
    },
    {
      name: "密偵貴師",
      stats: [13, 5, 10],
      exp: 2000,
      skills: ["スカウト", "アリストクラシー"],
    },
    {
      name: "魔神貴師",
      stats: [10, 3, 15],
      exp: 1500,
      skills: ["デーモンルーラー", "アリストクラシー"],
    },
    {
      name: "魔導貴師",
      stats: [9, 4, 15],
      exp: 500,
      skills: ["ソーサラー", "コンジャラー", "アリストクラシー"],
    },
    {
      name: "軽戦貴師",
      stats: [12, 5, 11],
      exp: 1500,
      skills: ["フェンサー", "アーティザン", "アリストクラシー"],
    },
    { name: "歌手", stats: [6, 5, 7], exp: 1500, skills: ["バード"] },
    { name: "魔操者", stats: [7, 7, 4], exp: 2500, skills: ["アーティザン"] },
    {
      name: "指揮官",
      stats: [6, 7, 5],
      exp: 500,
      skills: ["アリストクラシー"],
    },
    { name: "森羅導師", stats: [9, 7, 9], exp: 2000, skills: ["ドルイド"] },
    {
      name: "天地使い",
      stats: [10, 7, 8],
      exp: 2500,
      skills: ["ジオマンサー"],
    },
    {
      name: "踊り子",
      stats: [13, 6, 6],
      exp: 2000,
      skills: ["バトルダンサー"],
    },
    { name: "暗殺者", stats: [12, 6, 9], exp: 2500, skills: ["フェンサー"] },
    {
      name: "部位操者",
      stats: [12, 14, 6],
      exp: 2500,
      skills: ["フィジカルマスター"],
    },
    { name: "賢者", stats: [11, 13, 8], exp: 2500, skills: ["セージ"] },
    {
      name: "舞い手",
      stats: [11, 11, 6],
      exp: 2000,
      skills: ["バトルダンサー"],
    },
    { name: "隠者", stats: [10, 9, 12], exp: 2500, skills: ["セージ"] },
    {
      name: "癒し手",
      stats: [7, 8, 13],
      exp: 1500,
      skills: ["フェアリーテイマー", "レンジャー"],
    },
    {
      name: "剣の舞手",
      stats: [8, 9, 11],
      exp: 1500,
      skills: ["フェアリーテイマー", "フェンサー"],
    },
    {
      name: "召喚士",
      stats: [6, 7, 15],
      exp: 1000,
      skills: ["コンジャラー", "フェアリーテイマー"],
    },
    {
      name: "妖精学者",
      stats: [7, 7, 14],
      exp: 1500,
      skills: ["フェアリーテイマー", "セージ"],
    },
    {
      name: "妖精戦士",
      stats: [9, 9, 10],
      exp: 1000,
      skills: ["ファイター", "フェアリーテイマー"],
    },
    {
      name: "妖精軍師",
      stats: [8, 8, 12],
      exp: 1500,
      skills: ["フェアリーテイマー", "ウォーリーダー"],
    },
    {
      name: "妖魔術師",
      stats: [5, 7, 16],
      exp: 1000,
      skills: ["ソーサラー", "フェアリーテイマー"],
    },
    {
      name: "秘術妖精",
      stats: [8, 7, 13],
      exp: 1000,
      skills: ["フェアリーテイマー", "グリモワール"],
    },
    {
      name: "魔工妖精",
      stats: [8, 8, 12],
      exp: 1500,
      skills: ["フェアリーテイマー", "アーティザン"],
    },
    { name: "騎兵", stats: [15, 6, 6], exp: 2500, skills: ["ライダー"] },
    { name: "文官", stats: [8, 7, 11], exp: 2500, skills: ["セージ"] },
    { name: "彷徨い人", stats: [12, 2, 11], exp: 2500, skills: ["スカウト"] },
    {
      name: "操霊術士",
      stats: [7, 4, 10],
      exp: 2000,
      skills: ["コンジャラー"],
    },
    { name: "歌人", stats: [5, 7, 9], exp: 2500, skills: ["バード"] },
  ],

  // 技能リスト (Ginou)
  Skills: [
    { name: "ファイター", type: "A" },
    { name: "グラップラー", type: "A" },
    { name: "フェンサー", type: "B" },
    { name: "シューター", type: "B" },
    { name: "ソーサラー", type: "A" },
    { name: "コンジャラー", type: "A" },
    { name: "プリースト", type: "A" },
    { name: "フェアリーテイマー", type: "A" },
    { name: "マギテック", type: "A" },
    { name: "スカウト", type: "B" },
    { name: "レンジャー", type: "B" },
    { name: "セージ", type: "B" },
    { name: "エンハンサー", type: "B" },
    { name: "バード", type: "B" },
    { name: "アルケミスト", type: "B" },
    { name: "ライダー", type: "B" },
    { name: "デーモンルーラー", type: "A" },
    { name: "ウォーリーダー", type: "B" },
    { name: "ミスティック", type: "B" },
    { name: "フィジカルマスター", type: "B" },
    { name: "グリモワール", type: "A" },
    { name: "アーティザン", type: "B" },
    { name: "アリストクラシー", type: "B" },
    { name: "ドルイド", type: "A" },
    { name: "ジオマンサー", type: "B" },
    { name: "バトルダンサー", type: "A" },
    { name: "アビスゲイザー", type: "A" },
    { name: "ダークハンター", type: "B" },
  ],

  // 戦闘特技データ (NVTokugi)
  CombatFeats: [
    { name: "足さばき", level: 9, prereq: "" },
    { name: "ガーディアン", level: 5, prereq: "" },
    { name: "カード軽減", level: 5, prereq: "" },
    { name: "かいくぐり", level: 1, prereq: "盾" },
    { name: "回避行動", level: 3, prereq: "" },
    { name: "頑強", level: 5, prereq: "" },
    { name: "超頑強", level: 7, prereq: "" },
    { name: "キャパシティ", level: 11, prereq: "" },
    { name: "自己占瞳", level: 5, prereq: "" },
    { name: "射手の体術", level: 7, prereq: "" },
    { name: "スローイング", level: 1, prereq: "" },
    { name: "ターゲッティング", level: 1, prereq: "" },
    { name: "占瞳操作", level: 5, prereq: "" },
    { name: "双撃", level: 1, prereq: "" },
    { name: "代償軽減", level: 3, prereq: "" },
    { name: "鷹の目", level: 1, prereq: "" },
    { name: "投げ強化", level: 3, prereq: "" },
    { name: "二刀流", level: 5, prereq: "" },
    { name: "二刀無双", level: 11, prereq: "" },
    { name: "ハーモニー", level: 5, prereq: "" },
    { name: "武器習熟Ａ／ソード", level: 0, prereq: "" },
    { name: "武器習熟Ａ／アックス", level: 0, prereq: "" },
    { name: "武器習熟Ａ／スピア", level: 0, prereq: "" },
    { name: "武器習熟Ａ／メイス", level: 0, prereq: "" },
    { name: "武器習熟Ａ／スタッフ", level: 0, prereq: "" },
    { name: "武器習熟Ａ／フレイル", level: 0, prereq: "" },
    { name: "武器習熟Ａ／ウォーハンマー", level: 0, prereq: "" },
    { name: "武器習熟Ａ／格闘", level: 0, prereq: "" },
    { name: "武器習熟Ａ／投擲", level: 0, prereq: "" },
    { name: "武器習熟Ａ／ボウ", level: 0, prereq: "" },
    { name: "武器習熟Ａ／クロスボウ", level: 0, prereq: "" },
    { name: "武器習熟Ａ／ガン", level: 0, prereq: "" },
    { name: "武器習熟Ａ／絡み", level: 0, prereq: "" },
    { name: "武器習熟Ｓ／ソード", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／アックス", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／スピア", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／メイス", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／スタッフ", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／フレイル", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／ウォーハンマー", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／格闘", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／投擲", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／ボウ", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／クロスボウ", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／ガン", level: 5, prereq: "" },
    { name: "武器習熟Ｓ／絡み", level: 5, prereq: "" },
    { name: "武器の達人", level: 11, prereq: "" },
    { name: "賦術強化", level: 3, prereq: "" },
    { name: "賦術の極意", level: 7, prereq: "" },
    { name: "踏みつけ", level: 5, prereq: "" },
    { name: "ブロッキング", level: 3, prereq: "" },
    { name: "防具習熟Ａ／非金属鎧", level: 0, prereq: "" },
    { name: "防具習熟Ａ／金属鎧", level: 0, prereq: "" },
    { name: "防具習熟Ａ／盾", level: 0, prereq: "" },
    { name: "防具習熟Ｓ／非金属鎧", level: 5, prereq: "" },
    { name: "防具習熟Ｓ／金属鎧", level: 5, prereq: "" },
    { name: "防具習熟Ｓ／盾", level: 5, prereq: "" },
    { name: "防具の達人", level: 11, prereq: "" },
    { name: "魔晶石の達人", level: 9, prereq: "" },
    { name: "魔法制御", level: 0, prereq: "" },
    { name: "魔力強化", level: 6, prereq: "" },
    { name: "魔力撃強化", level: 9, prereq: "" },
    { name: "マルチガード", level: 7, prereq: "" },
    { name: "命中強化", level: 7, prereq: "" },
    { name: "両手利き", level: 1, prereq: "" },
    { name: "連続賦術", level: 5, prereq: "" },
    { name: "練体の極意", level: 5, prereq: "" },
    { name: "ワードブレイク", level: 1, prereq: "" },
    { name: "ＭＰ軽減／ソーサラー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／コンジャラー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／プリースト", level: 5, prereq: "" },
    { name: "ＭＰ軽減／フェアリーテイマー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／マギテック", level: 5, prereq: "" },
    { name: "ＭＰ軽減／デーモンルーラー", level: 5, prereq: "" },
    { name: "ＭＰ軽減／ウィザード", level: 5, prereq: "" },
    { name: "インファイト", level: 5, prereq: "" },
    { name: "囮攻撃", level: 1, prereq: "" },
    { name: "影矢", level: 9, prereq: "ガン除く射撃武器" },
    { name: "かばう", level: 1, prereq: "" },
    { name: "牙折り", level: 9, prereq: "" },
    { name: "斬り返し", level: 1, prereq: "2H近接武器" },
    { name: "クリティカルキャスト", level: 7, prereq: "" },
    { name: "牽制攻撃", level: 1, prereq: "" },
    { name: "全力攻撃", level: 1, prereq: "" },
    { name: "双占瞳", level: 7, prereq: "" },
    { name: "狙撃", level: 1, prereq: "2H射撃武器" },
    { name: "ダブルキャスト", level: 9, prereq: "" },
    { name: "挑発攻撃", level: 1, prereq: "" },
    { name: "ディフェンススタンス", level: 1, prereq: "" },
    { name: "テイルスイング", level: 3, prereq: "" },
    { name: "飛び蹴り", level: 9, prereq: "" },
    { name: "なぎ払い", level: 3, prereq: "2H近接武器" },
    { name: "マリオネット", level: 5, prereq: "" },
    { name: "必殺攻撃", level: 1, prereq: "" },
    { name: "魔法拡大／威力確実化", level: 1, prereq: "" },
    { name: "魔法拡大／確実化", level: 1, prereq: "" },
    { name: "魔法拡大／数", level: 1, prereq: "" },
    { name: "魔法拡大／距離", level: 1, prereq: "" },
    { name: "魔法拡大／時間", level: 1, prereq: "" },
    { name: "魔法拡大／範囲", level: 1, prereq: "" },
    { name: "魔法収束", level: 1, prereq: "" },
    { name: "魔力撃", level: 1, prereq: "" },
    { name: "マルチアクション", level: 5, prereq: "" },
    { name: "切り払い", level: 16, prereq: "ファイター" },
    { name: "無尽の盾", level: 16, prereq: "ファイター" },
    { name: "痛撃", level: 16, prereq: "ファイター" },
    { name: "ファントムカウンター", level: 16, prereq: "グラップラー" },
    { name: "跳躍攻撃", level: 16, prereq: "グラップラー" },
    { name: "封印撃", level: 16, prereq: "グラップラー" },
    { name: "急所狙い", level: 16, prereq: "フェンサー" },
    { name: "心眼", level: 16, prereq: "フェンサー" },
    { name: "ヒット＆アウェイ", level: 16, prereq: "フェンサー" },
    { name: "零距離射撃", level: 16, prereq: "シューター" },
    { name: "曲射", level: 16, prereq: "シューター" },
    { name: "デュアルアクション", level: 16, prereq: "シューター" },
    { name: "ＭＰ軽減／グリモワール", level: 5, prereq: "" },
    { name: "魔導書習熟Ａ", level: 1, prereq: "グリモワール" },
    { name: "魔導書習熟Ｓ", level: 3, prereq: "グリモワール" },
    { name: "魔導書の達人", level: 11, prereq: "グリモワール" },
    { name: "魔器習熟Ａ", level: 1, prereq: "" },
    { name: "魔器習熟Ｓ", level: 5, prereq: "アーティザン" },
    { name: "魔器の達人", level: 11, prereq: "アーティザン" },
    { name: "変幻自在", level: 5, prereq: "" },
    { name: "魔法拡大の達人", level: 1, prereq: "" },
    { name: "バイオレントキャスト", level: 1, prereq: "" },
    { name: "魔法拡大／すべて", level: 3, prereq: "" },
    { name: "鎧貫き", level: 1, prereq: "" },
    { name: "終律増強", level: 3, prereq: "バード" },
    { name: "呪歌追加", level: 1, prereq: "バード" },
    { name: "特殊楽器習熟", level: 1, prereq: "バード" },
    { name: "楽素転換", level: 3, prereq: "バード" },
    { name: "シュアパフォーマー", level: 3, prereq: "バード" },
    { name: "スキルフルプレイ", level: 7, prereq: "バード" },
    { name: "賦術全遠隔化", level: 5, prereq: "アルケミスト" },
    { name: "ＭＰ軽減／ドルイド", level: 5, prereq: "" },
    { name: "追い打ち", level: 1, prereq: "" },
    { name: "抵抗強化", level: 3, prereq: "" },
    { name: "カニングキャスト", level: 1, prereq: "" },
    { name: "クイックキャスト", level: 1, prereq: "" },
    { name: "シールドバッシュ", level: 1, prereq: "" },
    { name: "シャドウステップ", level: 1, prereq: "" },
    { name: "捨て身攻撃", level: 1, prereq: "" },
    { name: "露払い", level: 1, prereq: "" },
    { name: "乱撃", level: 1, prereq: "" },
    { name: "掠め取り", level: 5, prereq: "" },
    { name: "クルードテイク", level: 5, prereq: "" },
    { name: "相克の標的", level: 1, prereq: "ジオマンサー" },
    { name: "相克の別離", level: 3, prereq: "ジオマンサー" },
    { name: "鼓咆陣率追加", level: 1, prereq: "ウォーリーダー" },
    { name: "先陣の才覚", level: 5, prereq: "ウォーリーダー" },
    { name: "高度な柔軟性", level: 9, prereq: "ウォーリーダー" },
    { name: "ＭＰ軽減／アビスゲイザー", level: 5, prereq: "アビスゲイザー" },
  ],

  // 武器カテゴリ (EqCategory)
  WeaponClasses: {
    ソード: { type: "1H", skill: "フェンサー" },
    アックス: { type: "1H", skill: "フェンサー" },
    スピア: { type: "1H", skill: "フェンサー" },
    メイス: { type: "1H", skill: "フェンサー" },
    スタッフ: { type: "2H", skill: "フェンサー" },
    フレイル: { type: "1H", skill: "フェンサー" },
    ウォーハンマー: { type: "1H", skill: "フェンサー" },
    格闘: { type: "1H", skill: "グラップラー" },
    投擲: { type: "1H", skill: "シューター" },
    ボウ: { type: "2H", skill: "シューター" },
    クロスボウ: { type: "2H", skill: "シューター" },
    ガン: { type: "1H", skill: "シューター" },
    絡み: { type: "1H", skill: "フェンサー" },
  },
  ArmourClasses: {
    非金属鎧: { skill: "フェンサー" },
    金属鎧: { skill: "ファイター" },
    盾: { skill: "ファイター" },
  },
  Weapons: [
    {
      name: "ナイフ",
      cls: "ソード",
      rank: "B",
      req: 1,
      hands: 1,
      might: 1,
      crit: 10,
      price: 30,
      note: "投擲可",
    },
    {
      name: "スティレット",
      cls: "ソード",
      rank: "B",
      req: 2,
      hands: 1,
      might: 2,
      crit: 10,
      price: 40,
      note: "",
    },
    {
      name: "ダガー",
      cls: "ソード",
      rank: "B",
      req: 3,
      hands: 1,
      might: 3,
      crit: 10,
      price: 50,
      note: "投擲可",
    },
    {
      name: "ククリ",
      cls: "ソード",
      rank: "B",
      req: 4,
      hands: 1,
      might: 4,
      crit: 10,
      price: 60,
      note: "",
    },
    {
      name: "ショートソード",
      cls: "ソード",
      rank: "B",
      req: 5,
      hands: 1,
      might: 5,
      crit: 10,
      price: 80,
      note: "",
    },
    {
      name: "エペ",
      cls: "ソード",
      rank: "B",
      req: 6,
      hands: 1,
      might: 6,
      crit: 10,
      price: 90,
      note: "",
    },
    {
      name: "カッツバルゲル",
      cls: "ソード",
      rank: "B",
      req: 7,
      hands: 1,
      might: 7,
      crit: 10,
      price: 100,
      note: "",
    },
    {
      name: "レイピア",
      cls: "ソード",
      rank: "B",
      req: 8,
      hands: 1,
      might: 8,
      crit: 10,
      price: 110,
      note: "",
    },
    {
      name: "サーベル",
      cls: "ソード",
      rank: "B",
      req: 10,
      hands: 1,
      might: 10,
      crit: 10,
      price: 190,
      note: "",
    },
    {
      name: "エストック",
      cls: "ソード",
      rank: "B",
      req: 11,
      hands: 2,
      might: 21,
      crit: 10,
      price: 370,
      note: "",
    },
    {
      name: "ロングソード",
      cls: "ソード",
      rank: "B",
      req: 13,
      hands: 1,
      might: 13,
      crit: 10,
      price: 440,
      note: "両手持ち可",
    },
    {
      name: "ロングソード(両手)",
      cls: "ソード",
      rank: "B",
      req: 13,
      hands: 2,
      might: 23,
      crit: 10,
      price: 440,
      note: "",
    },
    {
      name: "ブロードソード",
      cls: "ソード",
      rank: "B",
      req: 15,
      hands: 1,
      might: 15,
      crit: 10,
      price: 340,
      note: "",
    },
    {
      name: "バスタードソード",
      cls: "ソード",
      rank: "B",
      req: 17,
      hands: 1,
      might: 17,
      crit: 10,
      price: 560,
      note: "両手持ち可",
    },
    {
      name: "バスタードソード(両手)",
      cls: "ソード",
      rank: "B",
      req: 17,
      hands: 2,
      might: 27,
      crit: 10,
      price: 560,
      note: "",
    },
    {
      name: "ファルシオン",
      cls: "ソード",
      rank: "B",
      req: 18,
      hands: 2,
      might: 28,
      crit: 10,
      price: 790,
      note: "",
    },
    {
      name: "ツーハンドソード",
      cls: "ソード",
      rank: "B",
      req: 20,
      hands: 2,
      might: 30,
      crit: 10,
      price: 860,
      note: "",
    },
    {
      name: "シャムシール",
      cls: "ソード",
      rank: "B",
      req: 22,
      hands: 2,
      might: 32,
      crit: 10,
      price: 950,
      note: "",
    },
    {
      name: "グレートソード",
      cls: "ソード",
      rank: "B",
      req: 24,
      hands: 2,
      might: 34,
      crit: 10,
      price: 1020,
      note: "",
    },
    {
      name: "ファストスパイク",
      cls: "ソード",
      rank: "A",
      req: 1,
      hands: 1,
      might: 6,
      crit: 10,
      price: 820,
      note: "投擲可",
    },
    {
      name: "フリッサ",
      cls: "ソード",
      rank: "A",
      req: 8,
      hands: 1,
      might: 13,
      crit: 10,
      price: 880,
      note: "",
    },
    {
      name: "スキアヴォーナ",
      cls: "ソード",
      rank: "A",
      req: 11,
      hands: 1,
      might: 16,
      crit: 10,
      price: 990,
      note: "",
    },
    {
      name: "ディフェンダー",
      cls: "ソード",
      rank: "A",
      req: 12,
      hands: 1,
      might: 17,
      crit: 10,
      price: 1770,
      note: "防護点+1",
    },
    {
      name: "タルワール",
      cls: "ソード",
      rank: "A",
      req: 15,
      hands: 1,
      might: 20,
      crit: 10,
      price: 1210,
      note: "",
    },
    {
      name: "スティールブレイド",
      cls: "ソード",
      rank: "A",
      req: 19,
      hands: 1,
      might: 24,
      crit: 10,
      price: 1450,
      note: "",
    },
    {
      name: "フランベルジュ",
      cls: "ソード",
      rank: "A",
      req: 23,
      hands: 1,
      might: 28,
      crit: 10,
      price: 1580,
      note: "両手持ち可",
    },
    {
      name: "フランベルジュ(両手)",
      cls: "ソード",
      rank: "A",
      req: 23,
      hands: 2,
      might: 38,
      crit: 10,
      price: 1580,
      note: "",
    },
    {
      name: "ドラゴンスレイヤー",
      cls: "ソード",
      rank: "A",
      req: 28,
      hands: 2,
      might: 43,
      crit: 10,
      price: 2760,
      note: "",
    },
    {
      name: "シックル",
      cls: "アックス",
      rank: "B",
      req: 4,
      hands: 1,
      might: 9,
      crit: 11,
      price: 40,
      note: "",
    },
    {
      name: "ハンドアックス",
      cls: "アックス",
      rank: "B",
      req: 7,
      hands: 1,
      might: 12,
      crit: 11,
      price: 90,
      note: "投擲可",
    },
    {
      name: "ブージ",
      cls: "アックス",
      rank: "B",
      req: 11,
      hands: 1,
      might: 16,
      crit: 11,
      price: 240,
      note: "",
    },
    {
      name: "バトルアックス",
      cls: "アックス",
      rank: "B",
      req: 16,
      hands: 1,
      might: 21,
      crit: 11,
      price: 360,
      note: "両手持ち可",
    },
    {
      name: "バトルアックス(両手)",
      cls: "アックス",
      rank: "B",
      req: 16,
      hands: 2,
      might: 31,
      crit: 11,
      price: 360,
      note: "",
    },
    {
      name: "グレートアックス",
      cls: "アックス",
      rank: "B",
      req: 18,
      hands: 2,
      might: 33,
      crit: 11,
      price: 410,
      note: "",
    },
    {
      name: "ヘビーアックス",
      cls: "アックス",
      rank: "B",
      req: 20,
      hands: 1,
      might: 25,
      crit: 11,
      price: 440,
      note: "両手持ち可",
    },
    {
      name: "ヘビーアックス(両手)",
      cls: "アックス",
      rank: "B",
      req: 20,
      hands: 2,
      might: 35,
      crit: 11,
      price: 440,
      note: "",
    },
    {
      name: "ブローバ",
      cls: "アックス",
      rank: "B",
      req: 22,
      hands: 2,
      might: 37,
      crit: 11,
      price: 490,
      note: "",
    },
    {
      name: "ミノタウロスアックス",
      cls: "アックス",
      rank: "B",
      req: 30,
      hands: 2,
      might: 45,
      crit: 11,
      price: 950,
      note: "",
    },
    {
      name: "トマホーク",
      cls: "アックス",
      rank: "A",
      req: 7,
      hands: 1,
      might: 17,
      crit: 11,
      price: 630,
      note: "投擲可",
    },
    {
      name: "タバルジン",
      cls: "アックス",
      rank: "A",
      req: 13,
      hands: 1,
      might: 23,
      crit: 11,
      price: 840,
      note: "",
    },
    {
      name: "ロングアックス(振)",
      cls: "アックス",
      rank: "A",
      req: 16,
      hands: 2,
      might: 36,
      crit: 11,
      price: 990,
      note: "ハルバード系",
    },
    {
      name: "ロングアックス(突)",
      cls: "アックス",
      rank: "A",
      req: 16,
      hands: 2,
      might: 31,
      crit: 10,
      price: 990,
      note: "ハルバード系",
    },
    {
      name: "ハルバード(振)",
      cls: "アックス",
      rank: "A",
      req: 20,
      hands: 2,
      might: 40,
      crit: 11,
      price: 1080,
      note: "ハルバード系",
    },
    {
      name: "ハルバード(突)",
      cls: "アックス",
      rank: "A",
      req: 20,
      hands: 2,
      might: 35,
      crit: 10,
      price: 1080,
      note: "ハルバード系",
    },
    {
      name: "グレイヴ(振)",
      cls: "アックス",
      rank: "A",
      req: 28,
      hands: 2,
      might: 48,
      crit: 11,
      price: 1350,
      note: "ハルバード系",
    },
    {
      name: "グレイヴ(突)",
      cls: "アックス",
      rank: "A",
      req: 28,
      hands: 2,
      might: 43,
      crit: 10,
      price: 1350,
      note: "ハルバード系",
    },
    {
      name: "ジャベリン",
      cls: "スピア",
      rank: "B",
      req: 5,
      hands: 1,
      might: 10,
      crit: 9,
      price: 65,
      note: "投擲可",
    },
    {
      name: "ショートスピア",
      cls: "スピア",
      rank: "B",
      req: 10,
      hands: 1,
      might: 15,
      crit: 9,
      price: 110,
      note: "投擲可",
    },
    {
      name: "スピア",
      cls: "スピア",
      rank: "B",
      req: 15,
      hands: 1,
      might: 20,
      crit: 9,
      price: 170,
      note: "両手持ち可",
    },
    {
      name: "スピア(両手)",
      cls: "スピア",
      rank: "B",
      req: 15,
      hands: 2,
      might: 25,
      crit: 10,
      price: 170,
      note: "",
    },
    {
      name: "ロングスピア",
      cls: "スピア",
      rank: "B",
      req: 20,
      hands: 1,
      might: 25,
      crit: 9,
      price: 220,
      note: "両手持ち可",
    },
    {
      name: "ロングスピア(両手)",
      cls: "スピア",
      rank: "B",
      req: 20,
      hands: 2,
      might: 30,
      crit: 10,
      price: 220,
      note: "",
    },
    {
      name: "ピラー",
      cls: "スピア",
      rank: "A",
      req: 8,
      hands: 1,
      might: 13,
      crit: 8,
      price: 880,
      note: "",
    },
    {
      name: "トライデント",
      cls: "スピア",
      rank: "A",
      req: 12,
      hands: 1,
      might: 17,
      crit: 9,
      price: 460,
      note: "投擲可",
    },
    {
      name: "アールシェピース",
      cls: "スピア",
      rank: "A",
      req: 15,
      hands: 1,
      might: 25,
      crit: 9,
      price: 480,
      note: "両手持ち可",
    },
    {
      name: "アールシェピース(両手)",
      cls: "スピア",
      rank: "A",
      req: 15,
      hands: 2,
      might: 30,
      crit: 10,
      price: 480,
      note: "",
    },
    {
      name: "パイク",
      cls: "スピア",
      rank: "A",
      req: 25,
      hands: 1,
      might: 35,
      crit: 9,
      price: 1750,
      note: "両手持ち可",
    },
    {
      name: "パイク(両手)",
      cls: "スピア",
      rank: "A",
      req: 25,
      hands: 2,
      might: 45,
      crit: 9,
      price: 1750,
      note: "",
    },
    {
      name: "マレット",
      cls: "メイス",
      rank: "B",
      req: 1,
      hands: 1,
      might: 6,
      crit: 12,
      price: 20,
      note: "投擲可",
    },
    {
      name: "ライトメイス",
      cls: "メイス",
      rank: "B",
      req: 5,
      hands: 1,
      might: 10,
      crit: 12,
      price: 120,
      note: "",
    },
    {
      name: "ヘビーマレット",
      cls: "メイス",
      rank: "B",
      req: 10,
      hands: 1,
      might: 15,
      crit: 12,
      price: 220,
      note: "",
    },
    {
      name: "ヘビーメイス",
      cls: "メイス",
      rank: "B",
      req: 15,
      hands: 1,
      might: 20,
      crit: 12,
      price: 330,
      note: "両手持ち可",
    },
    {
      name: "ヘビーメイス(両手)",
      cls: "メイス",
      rank: "B",
      req: 15,
      hands: 2,
      might: 30,
      crit: 12,
      price: 330,
      note: "",
    },
    {
      name: "モール",
      cls: "メイス",
      rank: "B",
      req: 20,
      hands: 2,
      might: 35,
      crit: 12,
      price: 440,
      note: "",
    },
    {
      name: "オーガモール",
      cls: "メイス",
      rank: "B",
      req: 30,
      hands: 2,
      might: 45,
      crit: 12,
      price: 640,
      note: "",
    },
    {
      name: "ビリオン",
      cls: "メイス",
      rank: "A",
      req: 7,
      hands: 1,
      might: 17,
      crit: 12,
      price: 460,
      note: "",
    },
    {
      name: "スティールブロウ",
      cls: "メイス",
      rank: "A",
      req: 13,
      hands: 1,
      might: 23,
      crit: 12,
      price: 710,
      note: "",
    },
    {
      name: "シェルブレイカー",
      cls: "メイス",
      rank: "A",
      req: 18,
      hands: 1,
      might: 28,
      crit: 12,
      price: 1080,
      note: "両手持ち可",
    },
    {
      name: "シェルブレイカー(両手)",
      cls: "メイス",
      rank: "A",
      req: 18,
      hands: 2,
      might: 38,
      crit: 12,
      price: 1080,
      note: "",
    },
    {
      name: "ポールメイス",
      cls: "メイス",
      rank: "A",
      req: 23,
      hands: 2,
      might: 43,
      crit: 12,
      price: 1220,
      note: "",
    },
    {
      name: "メイジスタッフ",
      cls: "スタッフ",
      rank: "B",
      req: 1,
      hands: 2,
      might: 11,
      crit: 12,
      price: 110,
      note: "防護点+1",
    },
    {
      name: "クォータースタッフ",
      cls: "スタッフ",
      rank: "B",
      req: 4,
      hands: 2,
      might: 14,
      crit: 12,
      price: 140,
      note: "防護点+1",
    },
    {
      name: "マナスタッフ",
      cls: "スタッフ",
      rank: "A",
      req: 3,
      hands: 2,
      might: 13,
      crit: 12,
      price: 6800,
      note: "魔力+1、魔法の武器",
    },
    {
      name: "リーチスタッフ",
      cls: "スタッフ",
      rank: "A",
      req: 5,
      hands: 2,
      might: 15,
      crit: 12,
      price: 7000,
      note: "魔法のダメージ+2",
    },
    {
      name: "ライトフレイル",
      cls: "フレイル",
      rank: "B",
      req: 7,
      hands: 1,
      might: 12,
      crit: 9,
      price: 90,
      note: "",
    },
    {
      name: "フレイル",
      cls: "フレイル",
      rank: "B",
      req: 10,
      hands: 1,
      might: 15,
      crit: 9,
      price: 240,
      note: "両手持ち可",
    },
    {
      name: "フレイル(両手)",
      cls: "フレイル",
      rank: "B",
      req: 10,
      hands: 2,
      might: 25,
      crit: 9,
      price: 240,
      note: "",
    },
    {
      name: "モーニングスター",
      cls: "フレイル",
      rank: "B",
      req: 12,
      hands: 1,
      might: 17,
      crit: 9,
      price: 280,
      note: "",
    },
    {
      name: "ヘビーフレイル",
      cls: "フレイル",
      rank: "B",
      req: 15,
      hands: 1,
      might: 20,
      crit: 9,
      price: 340,
      note: "両手持ち可",
    },
    {
      name: "ヘビーフレイル(両手)",
      cls: "フレイル",
      rank: "B",
      req: 15,
      hands: 2,
      might: 30,
      crit: 9,
      price: 340,
      note: "",
    },
    {
      name: "ライジングサン",
      cls: "フレイル",
      rank: "A",
      req: 14,
      hands: 1,
      might: 24,
      crit: 9,
      price: 1200,
      note: "両手持ち可",
    },
    {
      name: "ライジングサン(両手)",
      cls: "フレイル",
      rank: "A",
      req: 14,
      hands: 2,
      might: 34,
      crit: 9,
      price: 1200,
      note: "",
    },
    {
      name: "ゴーデンダッグ",
      cls: "フレイル",
      rank: "A",
      req: 18,
      hands: 1,
      might: 28,
      crit: 9,
      price: 1540,
      note: "両手持ち可",
    },
    {
      name: "ゴーデンダッグ(両手)",
      cls: "フレイル",
      rank: "A",
      req: 18,
      hands: 2,
      might: 38,
      crit: 9,
      price: 1540,
      note: "",
    },
    {
      name: "スコーピオンテイル",
      cls: "フレイル",
      rank: "A",
      req: 27,
      hands: 2,
      might: 47,
      crit: 9,
      price: 2600,
      note: "",
    },
    {
      name: "ピック",
      cls: "ウォーハンマー",
      rank: "B",
      req: 2,
      hands: 1,
      might: 7,
      crit: 9,
      price: 60,
      note: "",
    },
    {
      name: "ウォーハンマー",
      cls: "ウォーハンマー",
      rank: "B",
      req: 11,
      hands: 1,
      might: 16,
      crit: 9,
      price: 250,
      note: "",
    },
    {
      name: "マトック",
      cls: "ウォーハンマー",
      rank: "B",
      req: 20,
      hands: 2,
      might: 40,
      crit: 8,
      price: 440,
      note: "",
    },
    {
      name: "ウォーピック",
      cls: "ウォーハンマー",
      rank: "A",
      req: 5,
      hands: 1,
      might: 15,
      crit: 9,
      price: 600,
      note: "",
    },
    {
      name: "ベク・ド・コルバン(振)",
      cls: "ウォーハンマー",
      rank: "A",
      req: 20,
      hands: 2,
      might: 40,
      crit: 9,
      price: 1800,
      note: "ハルバード系",
    },
    {
      name: "ベク・ド・コルバン(突)",
      cls: "ウォーハンマー",
      rank: "A",
      req: 20,
      hands: 2,
      might: 45,
      crit: 8,
      price: 1800,
      note: "ハルバード系",
    },
    {
      name: "ギザルメー",
      cls: "ウォーハンマー",
      rank: "A",
      req: 25,
      hands: 2,
      might: 50,
      crit: 8,
      price: 1680,
      note: "",
    },
    {
      name: "パンチ",
      cls: "格闘",
      rank: "B",
      req: 0,
      hands: 1,
      might: 0,
      crit: 12,
      price: 0,
      note: "武器無し",
    },
    {
      name: "キック",
      cls: "格闘",
      rank: "B",
      req: 0,
      hands: 1,
      might: 5,
      crit: 9,
      price: 0,
      note: "武器無し",
    },
    {
      name: "投げ",
      cls: "格闘",
      rank: "B",
      req: 0,
      hands: 2,
      might: 10,
      crit: 12,
      price: 0,
      note: "グラップラー専用",
    },
    {
      name: "セスタス",
      cls: "格闘",
      rank: "B",
      req: 1,
      hands: 1,
      might: 1,
      crit: 11,
      price: 40,
      note: "パンチ強化",
    },
    {
      name: "スパイクブーツ",
      cls: "格闘",
      rank: "B",
      req: 1,
      hands: 1,
      might: 11,
      crit: 9,
      price: 160,
      note: "キック強化",
    },
    {
      name: "アイアンナックル",
      cls: "格闘",
      rank: "B",
      req: 5,
      hands: 1,
      might: 5,
      crit: 11,
      price: 100,
      note: "パンチ強化",
    },
    {
      name: "ソリッドヒール",
      cls: "格闘",
      rank: "B",
      req: 5,
      hands: 1,
      might: 15,
      crit: 9,
      price: 240,
      note: "キック強化",
    },
    {
      name: "アイアンボックス",
      cls: "格闘",
      rank: "B",
      req: 10,
      hands: 1,
      might: 10,
      crit: 11,
      price: 230,
      note: "パンチ強化",
    },
    {
      name: "シンガード",
      cls: "格闘",
      rank: "B",
      req: 10,
      hands: 1,
      might: 20,
      crit: 9,
      price: 390,
      note: "キック強化",
    },
    {
      name: "シンプレート",
      cls: "格闘",
      rank: "B",
      req: 15,
      hands: 1,
      might: 25,
      crit: 9,
      price: 580,
      note: "キック強化",
    },
    {
      name: "ハードノッカー",
      cls: "格闘",
      rank: "A",
      req: 5,
      hands: 1,
      might: 10,
      crit: 11,
      price: 440,
      note: "パンチ強化",
    },
    {
      name: "パワーリスト",
      cls: "格闘",
      rank: "A",
      req: 5,
      hands: 1,
      might: 10,
      crit: 10,
      price: 460,
      note: "パンチ強化",
    },
    {
      name: "スタンパー",
      cls: "格闘",
      rank: "A",
      req: 5,
      hands: 1,
      might: 20,
      crit: 9,
      price: 520,
      note: "キック強化",
    },
    {
      name: "チェインスティック",
      cls: "格闘",
      rank: "A",
      req: 10,
      hands: 1,
      might: 15,
      crit: 11,
      price: 630,
      note: "パンチ強化",
    },
    {
      name: "パワーアンクル",
      cls: "格闘",
      rank: "A",
      req: 10,
      hands: 1,
      might: 20,
      crit: 10,
      price: 900,
      note: "キック強化",
    },
    {
      name: "ハードキッカー",
      cls: "格闘",
      rank: "A",
      req: 15,
      hands: 1,
      might: 30,
      crit: 9,
      price: 1290,
      note: "キック強化",
    },
    {
      name: "ストーン",
      cls: "投擲",
      rank: "B",
      req: 1,
      hands: 1,
      might: 1,
      crit: 12,
      price: 0,
      note: "射程10m",
    },
    {
      name: "シルバーストーン",
      cls: "投擲",
      rank: "B",
      req: 1,
      hands: 1,
      might: 1,
      crit: 12,
      price: 1,
      note: "射程10m, 銀製",
    },
    {
      name: "チャクラム",
      cls: "投擲",
      rank: "A",
      req: 1,
      hands: 1,
      might: 6,
      crit: 10,
      price: 100,
      note: "射程20m",
    },
    {
      name: "スリング",
      cls: "投擲",
      rank: "A",
      req: 2,
      hands: 1,
      might: 12,
      crit: 11,
      price: 220,
      note: "射程30m",
    },
    {
      name: "ダーク",
      cls: "投擲",
      rank: "A",
      req: 4,
      hands: 1,
      might: 9,
      crit: 10,
      price: 100,
      note: "射程20m",
    },
    {
      name: "ソリフェラム",
      cls: "投擲",
      rank: "A",
      req: 17,
      hands: 1,
      might: 27,
      crit: 9,
      price: 1070,
      note: "射程20m",
    },
    {
      name: "ショートボウ",
      cls: "ボウ",
      rank: "B",
      req: 2,
      hands: 2,
      might: 12,
      crit: 10,
      price: 60,
      note: "射程20m",
    },
    {
      name: "ノーマルボウ",
      cls: "ボウ",
      rank: "B",
      req: 7,
      hands: 2,
      might: 17,
      crit: 10,
      price: 120,
      note: "射程20m",
    },
    {
      name: "ロングボウ",
      cls: "ボウ",
      rank: "B",
      req: 12,
      hands: 2,
      might: 22,
      crit: 10,
      price: 170,
      note: "射程20m",
    },
    {
      name: "ヘビーボウ",
      cls: "ボウ",
      rank: "B",
      req: 17,
      hands: 2,
      might: 27,
      crit: 10,
      price: 220,
      note: "射程20m",
    },
    {
      name: "ライトボウ",
      cls: "ボウ",
      rank: "A",
      req: 5,
      hands: 2,
      might: 20,
      crit: 10,
      price: 610,
      note: "射程30m",
    },
    {
      name: "ラップドボウ",
      cls: "ボウ",
      rank: "A",
      req: 13,
      hands: 2,
      might: 28,
      crit: 10,
      price: 780,
      note: "射程30m",
    },
    {
      name: "ファストボウ",
      cls: "ボウ",
      rank: "A",
      req: 20,
      hands: 2,
      might: 35,
      crit: 10,
      price: 1200,
      note: "射程30m",
    },
    {
      name: "ライトクロスボウ",
      cls: "クロスボウ",
      rank: "B",
      req: 1,
      hands: 2,
      might: 16,
      crit: 10,
      price: 160,
      note: "射程30m",
    },
    {
      name: "ノーマルクロスボウ",
      cls: "クロスボウ",
      rank: "B",
      req: 5,
      hands: 2,
      might: 20,
      crit: 10,
      price: 260,
      note: "射程30m",
    },
    {
      name: "ヘビークロスボウ",
      cls: "クロスボウ",
      rank: "B",
      req: 10,
      hands: 2,
      might: 25,
      crit: 10,
      price: 530,
      note: "射程30m",
    },
    {
      name: "ボウガン",
      cls: "クロスボウ",
      rank: "A",
      req: 5,
      hands: 1,
      might: 15,
      crit: 10,
      price: 800,
      note: "射程20m",
    },
    {
      name: "アーバレスト",
      cls: "クロスボウ",
      rank: "A",
      req: 10,
      hands: 2,
      might: 30,
      crit: 10,
      price: 1000,
      note: "射程40m",
    },
    {
      name: "ティム",
      cls: "クロスボウ",
      rank: "A",
      req: 15,
      hands: 2,
      might: 35,
      crit: 10,
      price: 1280,
      note: "射程50m",
    },
    {
      name: "クレインクィン",
      cls: "クロスボウ",
      rank: "A",
      req: 20,
      hands: 2,
      might: 50,
      crit: 9,
      price: 1500,
      note: "射程40m",
    },
    {
      name: "サーペンタインガン",
      cls: "ガン",
      rank: "B",
      req: 1,
      hands: 1,
      might: 0,
      crit: 11,
      price: 360,
      note: "射程10m,装填数3",
    },
    {
      name: "トラドール",
      cls: "ガン",
      rank: "B",
      req: 5,
      hands: 2,
      might: 0,
      crit: 10,
      price: 800,
      note: "射程30m,装填数3",
    },
    {
      name: "ジェザイル",
      cls: "ガン",
      rank: "B",
      req: 10,
      hands: 2,
      might: 0,
      crit: 10,
      price: 1200,
      note: "射程50m,装填数3",
    },
    {
      name: "デリンジャー",
      cls: "ガン",
      rank: "A",
      req: 1,
      hands: 1,
      might: 0,
      crit: 10,
      price: 600,
      note: "射程10m,装填数2,ダメージ+1",
    },
    {
      name: "テンペスト",
      cls: "ガン",
      rank: "A",
      req: 10,
      hands: 2,
      might: 0,
      crit: 11,
      price: 2000,
      note: "射程30m,装填数6,ダメージ+1",
    },
    {
      name: "ロングバレル",
      cls: "ガン",
      rank: "A",
      req: 15,
      hands: 2,
      might: 0,
      crit: 10,
      price: 3500,
      note: "射程50m,装填数1,ダメージ+2",
    },
  ],
};
window.sw25_data.Regulations = [
  {
    label: "初期作成",
    growth: 0,
    exp: 3000,
    money: 1200,
    honor: 0,
    abyssShard: 0,
  },
  {
    label: "3～4",
    growth: 2,
    exp: 5500,
    money: 2500,
    honor: 30,
    abyssShard: 1,
  },
  {
    label: "4～5",
    growth: 5,
    exp: 10000,
    money: 6000,
    honor: 80,
    abyssShard: 2,
  },
  {
    label: "5～6",
    growth: 9,
    exp: 16000,
    money: 14000,
    honor: 150,
    abyssShard: 3,
  },
  {
    label: "6～7",
    growth: 13,
    exp: 23000,
    money: 24000,
    honor: 250,
    abyssShard: 5,
  },
  {
    label: "7～8",
    growth: 17,
    exp: 30000,
    money: 36000,
    honor: 350,
    abyssShard: 7,
  },
  {
    label: "8～9",
    growth: 22,
    exp: 40000,
    money: 54000,
    honor: 500,
    abyssShard: 9,
  },
  {
    label: "9～10",
    growth: 28,
    exp: 50000,
    money: 80000,
    honor: 700,
    abyssShard: 12,
  },
  {
    label: "10～11",
    growth: 34,
    exp: 65000,
    money: 120000,
    honor: 900,
    abyssShard: 15,
  },
  {
    label: "11～12",
    growth: 44,
    exp: 85000,
    money: 160000,
    honor: 1300,
    abyssShard: 21,
  },
  {
    label: "12～13",
    growth: 54,
    exp: 105000,
    money: 210000,
    honor: 1700,
    abyssShard: 30,
  },
  {
    label: "13～14",
    growth: 65,
    exp: 135000,
    money: 270000,
    honor: 2200,
    abyssShard: 39,
  },
  {
    label: "14～15",
    growth: 77,
    exp: 165000,
    money: 350000,
    honor: 2800,
    abyssShard: 48,
  },
  {
    label: "15+A",
    growth: 90,
    exp: 200000,
    money: 450000,
    honor: 3500,
    abyssShard: 57,
  },
  {
    label: "15+B",
    growth: 100,
    exp: 220000,
    money: 500000,
    honor: 4000,
    abyssShard: 66,
  },
  {
    label: "15+C",
    growth: 110,
    exp: 250000,
    money: 550000,
    honor: 4500,
    abyssShard: 75,
  },
];
